
(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

; // Specialists 
(define "Pattern_Orks_Orkboy_Burna_1"			("Skeleton" color(%color) skin(orkboy_burna_1)))
(define "Pattern_Orks_Orkboy_Dok_1"				("Skeleton" color(%color) skin(orkboy_dok_1)))
(define "Pattern_Orks_Orkboy_Kommando_1"		("Skeleton" color(%color) skin(orkboy_kommando_1)))
(define "Pattern_Orks_Orkboy_Loota_1"			("Skeleton" color(%color) skin(orkboy_loota_1)))
(define "Pattern_Orks_Orkboy_Mek_1"				("Skeleton" color(%color) skin(orkboy_mek_1)))
(define "Pattern_Orks_Orkboy_Tankbuster_1"		("Skeleton" color(%color) skin(orkboy_tankbuster_1)))
(define "Pattern_Orks_Orkboy_Psyker_1"			("Skeleton" color(%color) skin(orkboy_psyker_1)))
(define "Pattern_Orks_Orkboy_Shoota_1"			("Skeleton" color(%color) skin(orkboy_shoota_1)))
(define "Pattern_Orks_Orkboy_Shoota_Ardboy_1"	("Skeleton" color(%color) skin(orkboy_shoota_ardboy_1)))
(define "Pattern_Orks_Orkboy_Shoota_Big_1"		("Skeleton" color(%color) skin(orkboy_shoota_big_1)))
(define "Pattern_Orks_Orkboy_Stormboy_1"		("Skeleton" color(%color) skin(orkboy_stormboy_1)))
(define "Pattern_Orks_Orkboy_Tankman_1"			("Skeleton" color(%color) skin(orkboy_tankman_1)))

; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** EVIL SUNZ ***
(define "Skin_Evilsunz_Orkboy_Burna_1"					("Pattern_Orks_Orkboy_Burna_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Dok_1"					("Pattern_Orks_Orkboy_Dok_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Kommando_1"				("Pattern_Orks_Orkboy_Kommando_1"		color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Loota_1"					("Pattern_Orks_Orkboy_Loota_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Mek_1"					("Pattern_Orks_Orkboy_Mek_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Tankbuster_1"				("Pattern_Orks_Orkboy_Tankbuster_1"		color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Psyker_1"					("Pattern_Orks_Orkboy_Psyker_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Shoota_1"					("Pattern_Orks_Orkboy_Shoota_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Shoota_Ardboy_1"			("Pattern_Orks_Orkboy_Shoota_Ardboy_1"	color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Shoota_Big_1"				("Pattern_Orks_Orkboy_Shoota_Big_1"		color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Stormboy_1"				("Pattern_Orks_Orkboy_Stormboy_1"		color(Evilsunz)))
(define "Skin_Evilsunz_Orkboy_Tankman_1"				("Pattern_Orks_Orkboy_Tankman_1"		color(Evilsunz)))
	

; // *** GOFFS ***
(define "Skin_Goffs_Orkboy_Burna_1"						("Pattern_Orks_Orkboy_Burna_1"			color(Goffs)))
(define "Skin_Goffs_Orkboy_Dok_1"						("Pattern_Orks_Orkboy_Dok_1"			color(Goffs)))
(define "Skin_Goffs_Orkboy_Kommando_1"					("Pattern_Orks_Orkboy_Kommando_1"		color(Goffs)))
(define "Skin_Goffs_Orkboy_Loota_1"						("Pattern_Orks_Orkboy_Loota_1"			color(Goffs)))
(define "Skin_Goffs_Orkboy_Mek_1"						("Pattern_Orks_Orkboy_Mek_1"			color(Goffs)))
(define "Skin_Goffs_Orkboy_Tankbuster_1"				("Pattern_Orks_Orkboy_Tankbuster_1"		color(Goffs)))
(define "Skin_Goffs_Orkboy_Psyker_1"					("Pattern_Orks_Orkboy_Psyker_1"			color(Goffs)))
(define "Skin_Goffs_Orkboy_Shoota_1"					("Pattern_Orks_Orkboy_Shoota_1"			color(Goffs)))
(define "Skin_Goffs_Orkboy_Shoota_Ardboy_1"				("Pattern_Orks_Orkboy_Shoota_Ardboy_1"	color(Goffs)))
(define "Skin_Goffs_Orkboy_Shoota_Big_1"				("Pattern_Orks_Orkboy_Shoota_Big_1"		color(Goffs)))
(define "Skin_Goffs_Orkboy_Stormboy_1"					("Pattern_Orks_Orkboy_Stormboy_1"		color(Goffs)))
(define "Skin_Goffs_Orkboy_Tankman_1"					("Pattern_Orks_Orkboy_Tankman_1"		color(Goffs)))
	

; // *** BADMOONS ***
(define "Skin_Badmoons_Orkboy_Burna_1"					("Pattern_Orks_Orkboy_Burna_1"			color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Dok_1"					("Pattern_Orks_Orkboy_Dok_1"			color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Kommando_1"				("Pattern_Orks_Orkboy_Kommando_1"		color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Loota_1"					("Pattern_Orks_Orkboy_Loota_1"			color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Mek_1"					("Pattern_Orks_Orkboy_Mek_1"			color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Tankbuster_1"				("Pattern_Orks_Orkboy_Tankbuster_1"		color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Psyker_1"					("Pattern_Orks_Orkboy_Psyker_1"			color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Shoota_1"					("Pattern_Orks_Orkboy_Shoota_1"			color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Shoota_Ardboy_1"			("Pattern_Orks_Orkboy_Shoota_Ardboy_1"	color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Shoota_Big_1"				("Pattern_Orks_Orkboy_Shoota_Big_1"		color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Stormboy_1"				("Pattern_Orks_Orkboy_Stormboy_1"		color(Badmoons)))
(define "Skin_Badmoons_Orkboy_Tankman_1"				("Pattern_Orks_Orkboy_Tankman_1"		color(Badmoons)))
	
