
(Define "Base_Ironclad"
	{bone "Dread_Ironclad_Torso_2"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/Dread_Ironclad_Torso_2.ply"}
	}
	{bone "toes_reinforced"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/toes_reinforced.ply"}	
	}
	{bone "banner"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/banner_pole.ply"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/banner_banner_v1.ply"}
	}
)