
(Define "SL_Plasmacannon"
	{bone "l_plasmacannon"
		{parameters "ID=aux_turret3;"}
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			3.43486	-0.405666	0.483593
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/l_plasmacannon.ply"}
		{bone "foresight_l_plasmacannon"
			{Position 17.9187	0.734531	3.05023}
		}
		{bone "fx_l_plasmacannon"
			{Position 0.30574	0.621365	6.3675}
		}
	}
)