
; ############################################################################
; ########################## SC PLATAFORM MOD TALKS ##########################
; ############################################################################

(Include "SC_DLC_CODZ_voicelines_human.inc")
(Include "SC_DLC_HALO_voicelines_human.inc")
(Include "SC_DLC_LV40k_voicelines_human.inc")

{talk "alert_enemy" 							("human_phrases" args alert_enemy)}
{talk "alert_enemy_grenade" 					("human_phrases" args alert_enemy_grenade)}
;//{talk "alert_vhcl_turret"						("human_phrases" args alert_vhcl_turret)}
{talk "alert_wpn_sniper" 						("human_phrases" args alert_wpn_sniper)}
{talk "ally_die" 								("human_phrases" args ally_die)}
{talk "angry_brsrk" 							("human_phrases" args angry_brsrk)}
;//{talk "battle_ended_easy" 						("human_phrases" args battle_ended_easy)}
;//{talk "battle_ended_hard" 						("human_phrases" args battle_ended_hard)}
;//{talk "check_friend_body_dead" 					("human_phrases" args check_friend_body_dead)}
{talk "death_cry" 								("human_phrases" args death_cry)}
{talk "death_violent" 							("human_phrases" args death_violent)}
;//{talk "enemy_is_destroyed_vhcl_turret"			("human_phrases" args enemy_is_destroyed_vhcl_turret)}
{talk "enemy_is_destroyed_wpn_sniper"			("human_phrases" args enemy_is_destroyed_wpn_sniper)}
{talk "executing_an_order"						("human_phrases" args executing_an_order)}
;//{talk "executing_an_order_in_combat"			("human_phrases" args executing_an_order_in_combat)}
;//{ta/lk "executing_an_order_in_stealth"			("human_phrases" args executing_an_order_in_stealth)}

; // AURA TALKS.
;//{talk "group_ask_for_help"						("human_phrases" args group_ask_for_help)}
{talk "group_commend_friend"					("human_phrases" args group_commend_friend)}
;//{talk "group_join_squad"						("human_phrases" args group_join_squad)}
;//{talk "group_friend_betrayal"					("human_phrases" args group_friend_betrayal)}
{talk "group_friend_hurt_me"					("human_phrases" args group_friend_hurt_me)}
{talk "group_friend_killed_by_friend"			("human_phrases" args group_friend_killed_by_friend)}
{talk "group_friend_killed_by_me"				("human_phrases" args group_friend_killed_by_me)}
{talk "group_aura_leader_is_killed"				("human_phrases" args group_aura_leader_is_killed)}
;//{talk "group_aura_leader_raly_squad"			("human_phrases" args group_aura_leader_raly_squad)}
;//{talk "group_order_re_negative"					("human_phrases" args group_order_re_negative)}
;//{talk "group_order_re_positive"					("human_phrases" args group_order_re_positive)}
{talk "idle_out_of_combat"						("human_phrases" args idle_out_of_combat)}

; // COMBAT COMMS.
{talk "in_combat_comms"							("human_phrases" args in_combat_comms)}
{talk "in_combat_enemy_has_upper_hand"			("human_phrases" args in_combat_enemy_has_upper_hand)}
{talk "in_combat_group_has_upper_hand"	
	("human_phrases" args jubilation)
	("human_phrases" args in_combat_group_has_upper_hand)
}

{talk "jubilation_dead_enemy"					("human_phrases" args jubilation_dead_enemy)}
{talk "melee_strike"							("human_phrases" args melee_strike)}
{talk "panicking"								("human_phrases" args panicking)}
{talk "scream_of_pain_big"						("human_phrases" args scream_of_pain_big)}
{talk "scream_of_pain_small"					("human_phrases" args scream_of_pain_small)}
{talk "throwing_a_grenade"						("human_phrases" args throwing_a_grenade)}
{talk "wounded"									("human_phrases" args wounded)}

	
; // DLC Voicelines ------------------------------------------------------- }

(Include "SC_DLC_HALO_voicelines_human.inc")
(Include "SC_DLC_LV40k_voicelines_human.inc")
