;//{"Allies"
;//	{title "mp/alliance/allies"}
;//	{armies "rus"}
;//	{armies "usa"}
;//	{armies "eng"}
;//	{icon "/interface/pages/multi/flag_allies"}
;//}
;//{"Axis"
;//	{title "mp/alliance/axis"}
;//	{armies "ger"}
;//	{armies "fin"}
;//	{icon "/interface/pages/multi/flag_axis"}
;//}

; ============================================================== ;

(Include "Alliances_LV40k.inc")

; // (Include "Alliances_HALO.inc")