
(Define "Predator_Chassis_Ork"
	{bone "predator_ork"
		{bone "predator_ork_fuel"
			{parameters "ID=fuel;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/rhino_chassis/predator_ork/predator_ork_fuel.ply"}
		}
		{bone "predator_ork_base"
			{parameters "ID=body;"}
			{Position 4.52161	0.393701	42.9293}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/rhino_chassis/predator_ork/predator_ork_base.ply"}
		}
	}
)