
(Define "Aux_Kannon"
	{bone "l_base"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_base.ply"}
	}
	{bone "r_base"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_base.ply"}
	}
	{bone "r_kannon"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_kannon.ply"}
	}
	{bone "l_kannon"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_kannon.ply"}
	}
)