
{Volume "aux_turret1"
	{Cylinder 15.2078 29}
	{Bone "aux_turret1"}
	{Position 0	0	0.0638885}
}
{Volume "aux_turret2"
	{Cylinder 19.9602 29}
	{Bone "aux_turret2"}
	{Position -0.380955	0	0.648285}
}
{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Matrix34
		0	-1	0
		0	0	-1
		1	0	0
		-11.9852	-23.5013	20.6512
	}
}
{Volume "body2"
	{Polyhedron "body2.vol"}
	{Bone "body"}
	{Position -35.5011	0	112.398}
}
{Volume "engine"
	{Box 47.5 67.5 70}
	{Bone "engine"}
	{Position -115	8.28237	73.7227}
}
{Volume "fuel1"
	{Cylinder 12.3563 41}
	{Bone "body"}
	{Matrix34
		0	0	-1
		0	1	0
		1	0	0
		-110.235	-11.0697	25.6923
	}
}
{Volume "fuel2"
	{Cylinder 14.7325 62.5}
	{Bone "body"}
	{Position -125.511	-42.3826	60.429}
}
{Volume "shield"
	{Polyhedron "shield.vol"}
	{Bone "shield"}
	{Position 160.039	0.679867	29.4912}
}
{Volume "trackleft"
	{Polyhedron "trackl.vol"}
	{Bone "wheelsl"}
	{Position 4.78318	59.3455	-23.5}
}
{Volume "trackright"
	{Polyhedron "trackr.vol"}
	{Bone "wheelsr"}
	{Position 4.78318	-48.3453	-23.5}
}
{Volume "trackleft1"
	{Cylinder 25.1878 19}
	{Bone "wheell1"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	0	-0.199017
	}
}
{Volume "trackleft2"
	{Cylinder 16.1582 12}
	{Bone "wheell2"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		1.54019e-05	0	1.21813
	}
}
{Volume "trackleft3"
	{Cylinder 16.1582 12}
	{Bone "wheell3"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	0	0.636646
	}
}
{Volume "trackleft4"
	{Cylinder 16.1582 12}
	{Bone "wheell4"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	-1.00613e-05	-0.26543
	}
}
{Volume "trackleft5"
	{Cylinder 16.1582 12}
	{Bone "wheell5"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	0	-0.17461
	}
}
{Volume "trackleft6"
	{Cylinder 18.5344 19}
	{Bone "wheell6"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-3.0291e-05	-1.44204e-05	-1.33473
	}
}
{Volume "trackright1"
	{Cylinder 25.1878 19}
	{Bone "wheelr1"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	0	-0.0673676
	}
}
{Volume "trackright2"
	{Cylinder 16.1582 12}
	{Bone "wheelr2"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	0	-1.25027
	}
}
{Volume "trackright3"
	{Cylinder 16.1582 12}
	{Bone "wheelr3"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	0	-0.798313
	}
}
{Volume "trackright4"
	{Cylinder 16.1582 12}
	{Bone "wheelr4"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		1.15872e-05	0	-0.133762
	}
}
{Volume "trackright5"
	{Cylinder 16.1582 12}
	{Bone "wheelr5"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		3.44754e-05	0	-0.0429459
	}
}
{Volume "trackright6"
	{Cylinder 18.5344 19}
	{Bone "wheelr6"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0	-1.2513e-05	-1.20308
	}
}
