

(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

(define "Pattern_Tyr_Zoanthrope_1"	("Skeleton" color(%color) skin(+models_zoanthrope)))

; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** KRAKEN ***
(define "Skin_Kraken_Zoanthrope_1"		("Pattern_Tyr_Zoanthrope_1"	color(kraken)))

; // *** LEVIATHAN ***
(define "Skin_Leviathan_Zoanthrope_1"	("Pattern_Tyr_Zoanthrope_1"	color(leviathan)))
