(define "phrase_voice_rus_va_tank"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/rus/%3/v%2"}
		{text_dbg "(%1) rus/%3/v%2"}
	}
)

(define "phrase_voice_usa_va_tank"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/usa/%3/v%2"}
		{text_dbg "(%1) usa/%3/v%2"}
	}
)

(define "phrase_voice_ger_va_tank"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/ger/%3/v%2"}
		{text_dbg "(%1) ger/%3/v%2"}
	}
)

(define "phrase_voice_fin_va_tank"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/fin/%3/v%2"}
		{text_dbg "(%1) fin/%3/v%2"}
	}
)

(define "phrase_voice_eng_va_tank"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/eng/%3/v%2"}
		{text_dbg "(%1) eng/%3/v%2"}
	}
)

(define "phrase_voice_ita_va_tank"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/ita/%3/v%2"}
		{text_dbg "(%1) ita/%3/v%2"}
	}
)