(define "phrases_cannon"	; args: actor | language | voice | foldername
	("phrase_voice" args %0 rus 1 %1)

	("phrase_voice" args %0 ger 1 %1)

	("phrase_voice" args %0 fin 1 %1)
	("phrase_voice" args %0 fin 2 %1)
	("phrase_voice" args %0 fin 3 %1)

	("phrase_voice" args %0 usa 1 %1)
;	("phrase_voice" args %0 usa 2 %1)
;	("phrase_voice" args %0 usa 3 %1)
;	("phrase_voice" args %0 usa 4 %1)

	("phrase_voice" args %0 chi 1 %1)
	("phrase_voice" args %0 chi 2 %1)
	
;	("phrase_voice" args %0 fra 1 %1)

;new by ve mod

	("phrase_voice" args %0 rus 2 %1)

	("phrase_voice" args %0 ger 2 %1)

	("phrase_voice" args %0 usa 2 %1)

	("phrase_voice_rus_va_tank" args %0 rus_guards 1 %1)
	("phrase_voice_rus_va_tank" args %0 rus_guards 2 %1)
	("phrase_voice_rus_va_tank" args %0 rus_elite 1 %1)
	("phrase_voice_rus_va_tank" args %0 rus_elite 2 %1)
	("phrase_voice_rus_va_tank" args %0 rus_conscript 1 %1)
	("phrase_voice_rus_va_tank" args %0 rus_conscript 2 %1)
	("phrase_voice_rus_va_tank" args %0 rus_sniper 1 %1)
	("phrase_voice_rus_va_tank" args %0 rus_sniper 2 %1)
	("phrase_voice_rus_va_tank" args %0 rus_unique 1 %1)
	("phrase_voice_rus_va_tank" args %0 rus_unique 2 %1)

	("phrase_voice_ger_va_tank" args %0 ger_fallschirmjaeger 1 %1)
	("phrase_voice_ger_va_tank" args %0 ger_fallschirmjaeger 2 %1)
	("phrase_voice_ger_va_tank" args %0 ger_panzergrenadier 1 %1)
	("phrase_voice_ger_va_tank" args %0 ger_panzergrenadier 2 %1)
	("phrase_voice_ger_va_tank" args %0 ger_pzpio 1 %1)
	("phrase_voice_ger_va_tank" args %0 ger_pzpio 2 %1)
	("phrase_voice_ger_va_tank" args %0 ger_jaeger 1 %1)
	("phrase_voice_ger_va_tank" args %0 ger_jaeger 2 %1)
	("phrase_voice_ger_va_tank" args %0 ger_sttroop 1 %1)
	("phrase_voice_ger_va_tank" args %0 ger_sttroop 2 %1)

	("phrase_voice_usa_va_tank" args %0 usa_paratrooper 1 %1)
	("phrase_voice_usa_va_tank" args %0 usa_paratrooper 2 %1)
	("phrase_voice_usa_va_tank" args %0 usa_pathfinder 1 %1)
	("phrase_voice_usa_va_tank" args %0 usa_pathfinder 2 %1)
	("phrase_voice_usa_va_tank" args %0 usa_ranger 1 %1)
	("phrase_voice_usa_va_tank" args %0 usa_ranger 2 %1)
	("phrase_voice_usa_va_tank" args %0 usa_rifleman 1 %1)
	("phrase_voice_usa_va_tank" args %0 usa_rifleman 2 %1)
	("phrase_voice_usa_va_tank" args %0 usa_bazooka 1 %1)
	("phrase_voice_usa_va_tank" args %0 usa_bazooka 2 %1)
	("phrase_voice_usa_va_tank" args %0 usa_assault 1 %1)
	("phrase_voice_usa_va_tank" args %0 usa_assault 2 %1)

)