(define "phrases"	; args: actor | language | voice | foldername
	("phrase_voice" args %0 rus 1 %1)
	("phrase_voice" args %0 rus 2 %1)
	("phrase_voice" args %0 rus 3 %1)
	("phrase_voice" args %0 rus 4 %1)
	("phrase_voice" args %0 rus 5 %1)
	("phrase_voice" args %0 rus 6 %1)
	("phrase_voice" args %0 rus 7 %1)
	("phrase_voice" args %0 rus 8 %1)

	("phrase_voice" args %0 rus_fmsniper 1 %1)

	("phrase_voice" args %0 ger 1 %1)
	("phrase_voice" args %0 ger 2 %1)
	("phrase_voice" args %0 ger 3 %1)
	("phrase_voice" args %0 ger 4 %1)
	("phrase_voice" args %0 ger 5 %1)
	("phrase_voice" args %0 ger 6 %1)
	("phrase_voice" args %0 ger 7 %1)
	("phrase_voice" args %0 ger 8 %1)

	("phrase_voice" args %0 ger_officer 1 %1)
	("phrase_voice" args %0 ger_medic   1 %1)
;	("phrase_voice" args %0 ger_sniper  1 %1)

	("phrase_voice" args %0 spa 1 %1)

	("phrase_voice" args %0 fin 1 %1)
	("phrase_voice" args %0 fin 2 %1)
	("phrase_voice" args %0 fin 3 %1)
	("phrase_voice" args %0 fin 4 %1)
	("phrase_voice" args %0 fin 5 %1)

	("phrase_voice" args %0 usa 1 %1)
	("phrase_voice" args %0 usa 2 %1)
	("phrase_voice" args %0 usa 3 %1)
	("phrase_voice" args %0 usa 4 %1)
;	("phrase_voice" args %0 usa 5 %1)

	("phrase_voice" args %0 usa_officer 1 %1)
	("phrase_voice" args %0 usa_medic 1 %1)
	("phrase_voice" args %0 usa_medic 2 %1)
;	("phrase_voice" args %0 usa_sniper 1 %1)

;	("phrase_voice" args %0 fra 1 %1)

	("phrase_voice" args %0 chi 1 %1)	
	("phrase_voice" args %0 chi 2 %1)
	
	("phrase_voice" args %0 pol 1 %1)

;new by ve mod

	("phrase_voice" args %0 ger_fallschirmjaeger  1 %1)
	("phrase_voice" args %0 ger_fallschirmjaeger  2 %1)

	("phrase_voice" args %0 ger_jaeger  1 %1)

	("phrase_voice" args %0 ger_officer 2 %1)
	("phrase_voice" args %0 ger_officer 3 %1)
	("phrase_voice" args %0 ger_officer 4 %1)

	("phrase_voice" args %0 ger_panzergrenadier  1 %1)
	("phrase_voice" args %0 ger_panzergrenadier  2 %1)

	("phrase_voice" args %0 ger_pzpio 1 %1)

	("phrase_voice_target" args %0 ger_sniper 2 %1 ger_sniper 1)

	("phrase_voice" args %0 ger_sttroop 1 %1)

	("phrase_voice" args %0 rus_guards 1 %1)

	("phrase_voice" args %0 rus_conscript 1 %1)

	("phrase_voice" args %0 rus_sniper 1 %1)

	("phrase_voice" args %0 rus_unique 1 %1)
	("phrase_voice" args %0 rus_unique 2 %1)
	("phrase_voice" args %0 rus_unique 3 %1)
	("phrase_voice" args %0 rus_unique 4 %1)

	("phrase_voice" args %0 rus_elite 1 %1)

	("phrase_voice" args %0 usa_lt1 1 %1)
	("phrase_voice" args %0 usa_lt2 1 %1)
	("phrase_voice" args %0 usa_cpt 1 %1)
	("phrase_voice" args %0 usa_major 1 %1)

	("phrase_voice" args %0 usa_pathfinder 1 %1)

	("phrase_voice" args %0 usa_ranger 1 %1)
	("phrase_voice" args %0 usa_ranger 2 %1)

	("phrase_voice" args %0 usa_paratrooper 1 %1)
	("phrase_voice" args %0 usa_paratrooper 2 %1)

	("phrase_voice" args %0 usa_rifleman 1 %1)
	("phrase_voice" args %0 usa_rifleman 2 %1)
	("phrase_voice" args %0 usa_rifleman 3 %1)
	("phrase_voice" args %0 usa_rifleman 4 %1)

	("phrase_voice" args %0 usa_bazooka 1 %1)

	("phrase_voice_target" args %0 usa_sniper 2 %1 usa_sniper 1)

	("phrase_voice" args %0 usa_assault 1 %1)
	("phrase_voice" args %0 usa_assault 2 %1)
	("phrase_voice" args %0 usa_assault 3 %1)
	("phrase_voice" args %0 eng 1 %1)
	("phrase_voice" args %0 eng 2 %1)
	("phrase_voice" args %0 eng 3 %1)
;	("phrase_voice" args %0 eng 4 %1)
	("phrase_voice" args %0 eng 5 %1)
;	("phrase_voice" args %0 eng 6 %1)
	("phrase_voice" args %0 eng_pol 1 %1)
	("phrase_voice" args %0 sco 1 %1)
;	("phrase_voice" args %0 iri 1 %1)
;	("phrase_voice" args %0 can 1 %1)
	("phrase_voice" args %0 eng_officer 1 %1)
;	("phrase_voice" args %0 eng_medic 1 %1)
;	("phrase_voice" args %0 eng_sniper 1 %1)
)