(define "sonic_crack_s1"
	{start_sound "hit/shared/Sonic_Crack/s1/d1/" use_position}
	{start_sound "hit/shared/Sonic_Crack/s1/d2/" use_position}
)
(define "sonic_crack_s2"
	{start_sound "hit/shared/Sonic_Crack/s2/d1/" use_position}
	{start_sound "hit/shared/Sonic_Crack/s2/d2/" use_position}
)
(define "sonic_crack_s3"
	{start_sound "hit/shared/Sonic_Crack/s3/d1/" use_position}
	{start_sound "hit/shared/Sonic_Crack/s3/d2/" use_position}
)
(define "sonic_crack_s4"
	{start_sound "hit/shared/Sonic_Crack/s4/d1/" use_position}
	{start_sound "hit/shared/Sonic_Crack/s4/d2/" use_position}
)
(define "explosion_s1_dirt"
	{start_sound "detonation/s1/shockwave/Dirt/Impact/" use_position}
	{start_sound "detonation/s1/shockwave/Dirt/Trickle/" use_position}
)
(define "explosion_s1_rock"
	{start_sound "detonation/s1/shockwave/Stone/Impact/" use_position}
	{start_sound "detonation/s1/shockwave/Stone/Trickle/" use_position}
)
(define "explosion_s2_dirt"
	{start_sound "detonation/s2/shockwave/Dirt/Impact/" use_position}
	{start_sound "detonation/s2/shockwave/Dirt/Trickle/" use_position}
)
(define "explosion_s2_rock"
	{start_sound "detonation/s2/shockwave/Stone/Impact/" use_position}
	{start_sound "detonation/s2/shockwave/Stone/Trickle/" use_position}
)
(define "explosion_s3_dirt"
	{start_sound "detonation/s3/shockwave/Dirt/Impact/" use_position}
	{start_sound "detonation/s3/shockwave/Dirt/Trickle/" use_position}
)
(define "explosion_s3_rock"
	{start_sound "detonation/s3/shockwave/Stone/Impact/" use_position}
	{start_sound "detonation/s3/shockwave/Stone/Trickle/" use_position}
)
(define "explosion_AP_Shell"
	{start_sound "detonation/s1/d1/AP_Shell/" use_position}
	{start_sound "detonation/s1/d2/AP_Shell/" use_position}
	{start_sound "detonation/s1/d3/AP_Shell/" use_position}
)
(define "explosion_he_auto"
	{start_sound "detonation/s1/d1/20to30mm_Auto_HE/" use_position}
	{start_sound "detonation/s1/d2/20to30mm_Auto_HE/" use_position}
	{start_sound "detonation/s1/d3/20to30mm_Auto_HE/" use_position}
)
(define "explosion_grenade"
	{start_sound "detonation/s1/d1/Grenade/" use_position}
	{start_sound "detonation/s1/d2/Grenade/" use_position}
	{start_sound "detonation/s1/d3/Grenade/" use_position}
)
(define "explosion_HEAT_s1"
	{start_sound "detonation/s1/d1/Explosion_HEAT/" use_position}
	{start_sound "detonation/s1/d2/Explosion_HEAT/" use_position}
	{start_sound "detonation/s1/d3/Explosion_HEAT/" use_position}
)
(define "explosion_HEAT_s2"
	{start_sound "detonation/s2/d1/Explosion_HEAT/" use_position}
	{start_sound "detonation/s2/d2/Explosion_HEAT/" use_position}
	{start_sound "detonation/s2/d3/Explosion_HEAT/" use_position}
)
(define "explosion_HEAT_s3"
	{start_sound "detonation/s3/d1/Explosion_HEAT/" use_position}
	{start_sound "detonation/s3/d2/Explosion_HEAT/" use_position}
	{start_sound "detonation/s3/d3/Explosion_HEAT/" use_position}
)
(define "explosion_HEAT_s4"
	{start_sound "detonation/s3/d1/Explosion_HEAT/" use_position}
	{start_sound "detonation/s3/d2/Explosion_HEAT/" use_position}
	{start_sound "detonation/s3/d3/Explosion_HEAT/" use_position}
)
(define "explosion_HE_s1"
	{start_sound "detonation/s1/d1/Explosion_HE/" use_position}
	{start_sound "detonation/s1/d2/Explosion_HE/" use_position}
	{start_sound "detonation/s1/d3/Explosion_HE/" use_position}
)
(define "explosion_HE_s2"
	{start_sound "detonation/s2/d1/Explosion_HE/" use_position}
	{start_sound "detonation/s2/d2/Explosion_HE/" use_position}
	{start_sound "detonation/s2/d3/Explosion_HE/" use_position}
)
(define "explosion_HE_s3"
	{start_sound "detonation/s3/d1/Explosion_HE/" use_position}
	{start_sound "detonation/s3/d2/Explosion_HE/" use_position}
	{start_sound "detonation/s3/d3/Explosion_HE/" use_position}
)
(define "explosion_HE_s4"
	{start_sound "detonation/s4/d1/Explosion_HE/" use_position}
	{start_sound "detonation/s4/d2/Explosion_HE/" use_position}
	{start_sound "detonation/s4/d3/Explosion_HE/" use_position}
)
(define "explosion_HE_s5"
	{start_sound "detonation/s5/d1/Explosion_HE/" use_position}
	{start_sound "detonation/s5/d2/Explosion_HE/" use_position}
	{start_sound "detonation/s5/d3/Explosion_HE/" use_position}
)
(define "explosion_HE_s6"
	{start_sound "detonation/s6/d1/Explosion_HE/" use_position}
	{start_sound "detonation/s6/d2/Explosion_HE/" use_position}
	{start_sound "detonation/s6/d3/Explosion_HE/" use_position}
)

