{"firewood"
	{inflammation_time 10}
	{on spawn
		{link_sound "burn_small" "fire/loops/small"}
	}
	{on bullet_hit
		{if stuff "shell fg"
			{bullet_detonate}
		else stuff "ic hmgun"
			{fire radius 0.5 time 0.3 heating 3}
		else stuff "ic autocannon_small"
			{fire radius 0.5 time 0.3 heating 6}
		}
	}
	{on break_armor
		{call "break"}
	}
	{on contact
		{if can_crush
			{volumes disable contact}
			{call "break"}
		}
	}
	{on "break"
		{spawn "wood_crush_big" "root"}
		{delay 0.2 {delete}}
		{stop_sound "burn_small"}
	}
	{on "burn_volume"
		{if not burned
			{if volume "body"
				{burn volume fx "smoke_dead_tree1" time 15 2 even_law}
				{play_sound "burn_small" 1}
				{delay 8 "break_delay" {call "break"}}
			}
		}
	}
}

{"stack"
	{inflammation_time 0.3}
	{on spawn
		{link_sound "burn_large" "fire/loops/big"}
	}
	{on bullet_hit
		{if not stuff "proj_pointer"
			{if stuff "shell"
				{spawn "hay_hit_norm"}
			else stuff "bullet_fx size1"
				{if rand 0.3
					{spawn "hay_hit_small2"}
				}
			else stuff "bullet_fx size2"
				{if rand 0.6
					{spawn "hay_hit_small2"}
				}
			else stuff "bullet_fx size3"
				{spawn "hay_hit_small2"}
			else stuff "ic hmgun"
				{fire radius 0.5 time 0.3 heating 3}
			else stuff "ic autocannon_small"
				{fire radius 0.5 time 0.3 heating 6}
			}
		else stuff "usa_laser ammo"
			{spawn "proj_point_usa_laser_des" offset 0 0 5
			{tags add "laser_target"}
			{tags add "cwps_ground_attack"}
			
			(mod not "mp"{player 16})
			{delay 1 {delete}}}	
		else stuff "rus_laser ammo"
			{spawn "proj_point_rus_laser_des" offset 0 0 5
			{tags add "laser_target"}
			{tags add "cwps_ground_attack"}
			
			(mod not "mp"{player 16})
			{delay 1 {delete}}}
		}
	}
	{on break_armor
		{if name "blast"
			{set "crush" 0}
			{call "crush"}
		}
	}
	{on contact
		{if can_crush
			{set "crush" 1}
			{call "crush"}
		}
	}
	{on "crush"
		{volumes disable all}
		{call "crush_fx"}
		{set "fall" 1}
		{tex_morph "crushed" 0.1}
		{ani_play "crush" 10 callback}
	}
	{on "burn_volume"
		{if not burned
			{if volume "fire"
				{call "_burn"}
			}
		}
	}
	{on "_burn"
		{volumes disable visible bullet contact blast}
		{burn volume "fire0" fx "smoke_dead_hay" time 15 even_law}
		{burn volume "fire1" fx "smoke_dead_hay" time 10 even_law}
		{tex_morph "burned" 8}
		{play_sound "burn_large" 1}
		{delay 6.0
			{if not "fall"
				{set "fall" 1}
				{ani_play "crush" callback}
				{delay 4 {bone hide "body"} {delete}}
			}
		}
	}
	{on animation_end "crush"
		{update_shadow}
		{update_visibility_patch}
		{area disable}
	}
	{on "crush_fx"
		{delay 0.1 {bone hide "body"}}
		{if "crush"
			{spawn "hay_hit_norm"}
			{spawn "hay_hit_norm" "FX_haulm2"}
		else
			{spawn "hay_hit_big" no_position}
			{spawn "hay_hit_big" "FX_haulm1"}
			{stop_sound "burn_large"}
		}
		{delete}
	}
}

{"stack heap"
	{on "crush" overload}
}

{"stack tent"
	{on "crush_fx" overload}
}

{"stack straw"
	{on bullet_hit
		{if stuff "shell fg"
			{set "crush" 0}
			{call "crush"}
		else stuff "heat_shell"
			{set "crush" 0}
			{call "crush"}
		}
	}
}

{"gate"
	{on spawn
		;@note: the interaction flags and skeleton state are saved only in game mode
		;		so if we need the gate state to be saved in editor we have to check for tag and wind the animation if needed
		{if tagged "opened"
			{set "opened" 1}
			{ani_wind "open" end}
		}
		{call "update_area"}
	}
	{on "open"
		{if not "user_opened"
			{set "opened" 1}
			{ani_play "open" resume callback}
			{call "update_area"}
		}
	}
	{on "close"
		{if not "user_opened"
			{set "opened" 0}
			{ani_play "open" -1 resume}
			{call "update_area"}
		}
	}
	{on animation_end "open"
		{tags add "opened"}
	}
	{on "update_area"
		{if "opened"
			{area disable	"close"}
			{area enable	"left"}
			{area enable	"right"}
		else
			{area enable	"close"}
			{area disable	"left"}
			{area disable	"right"}
		}
	}
	{on "open_disable"
		{volumes "door_lock" disable touch}
	}
	{on "open_enable"
		{volumes "door_lock" enable touch}
	}
}

{"ferry"
	{on spawn
		{call "update_area"}
	}
	(define "update_area"
		{if "opened%0"
			{area disable	"close%0_%1"}
			{area enable	"left%0_%1"}
			{area enable	"right%0_%1"}

			{area disable	"close%0_%2"}
			{area disable	"left%0_%2"}
			{area disable	"right%0_%2"}
		else
			{area enable	"close%0_%1"}
			{area disable	"left%0_%1"}
			{area disable	"right%0_%1"}

			{area disable	"close%0_%2"}
			{area disable	"left%0_%2"}
			{area disable	"right%0_%2"}
		}
	)
	(define "door"
		{on "open%0"
			{set "opened%0" 1}
			{ani_play "open%0"}
			{call "update_area%0"}
		}
		{on "close%0"
			{set "opened%0" 0}
			{ani_play "close%0"}
			{call "update_area%0"}
		}
		{on "open_fast%0"
			{set "opened%0" 1}
			{ani_wind "open%0" end}
			{call "update_area%0"}
		}
		{on "close_fast%0"
			{set "opened%0" 0}
			{ani_wind "close%0" end}
			{call "update_area%0"}
		}
		{on "update_area%0"
			{if not "moved"
				("update_area" args %0 1 2)
				{area enable	"rectangle01"}
				{area enable	"rectangle02"}
				{area disable	"rectangle03"}
				{area disable	"rectangle04"}
			else
				("update_area" args %0 2 1)
				{area disable	"rectangle01"}
				{area disable	"rectangle02"}
				{area enable	"rectangle03"}
				{area enable	"rectangle04"}
			}
		}
	)
	("door" args 1)
	("door" args 2)
	{on "update_area"
		{call "update_area1"}
		{call "update_area2"}
	}
	{on "move_front"
		{set "moved" 1}
		{call "update_area"}
		{land off}
		{ani_play "move" callback}
	}
	{on "move_back"
		{set "moved" 0}
		{call "update_area"}
		{land off}
		{ani_play "move" -1 callback}
	}
	{on "update_land"
		{land off}
		{land on}
	}
	{on animation_end "move"
		{land on}
	}
}

{"tank_platform"
	{on "close"
		{land off}
		{ani_play "close1"}
		{ani_play "close2"}
	}
	{on "open"
		{land on}
		{ani_play "close1" -1}
		{ani_play "close2" -1}
	}

	{on "move"
		{ani_play "move"}
	}
}

{"switch"
	{on "switch"
		{tags add "switch"}
	}
}

{"dynamite_fuse"
	{on "switch"
		{tags add "switch"}
		{ani_play "move"}
	}
}


{"gate door_big"
	{on "open"
		{start_sound "vehicle/engine/door"}
	}
	{on "close"
		{start_sound "vehicle/engine/door"}
	}
}

{"gate lock"
	{on "open"
;		{start_sound "vehicle/engine/door"}
		{volumes "attach" enable touch}
	}
	{on bullet_hit
		{if volume "lock"
			{if not "opened"
				{call "open"}
				{set "user_opened" 1}
				{delay_ex 0
					{tear "piece_small_steel" bone "lock"
						{impulse up -1 0.7 dir 2.5 0.3 no_position}
					}
				}
			}
		}
	}
}

{"sand_bag"
	{on bullet_hit
		{if stuff "bullet_fx"
			{spawn "ex_air_sm"}
			{bullet_detonate}
		else stuff "shell"
			{spawn "sand_hit_small"}
			{bullet_detonate}
		}
	}
	{on contact
		{if can_crush
			{volumes disable contact}
			{delay 0
				{call "crush"}
			}
		}
	}
	{on "crush"
		{if not "crushed"
			{set "crushed" 1}
			{set_skeleton "_x"}
			{ani_play "crush1" callback}
			{call "update_fx"}
			{call "effects"}
		}
	}
	{on animation_end "crush1"
		{ani_play "crush2"}
	}
}

{"sand_bag_small"
	{on break_armor
		{spawn "sand_hit_small"}
		{delete}
	}
	{on contact
		{if can_crush
			{volumes disable contact}
			{spawn "sand_hit_small"}
			{delete}
		}
	}
}

{"sand_bag_big" ;// seems to be unused
	{on break_armor
		{spawn "wood_crush_big"}
		;{spawn "sandbags_crush"} //from CtA
		{delete}
	}
	{on contact
		{if can_crush
			{volumes disable contact}
			{spawn "wood_crush_big"}
			;{spawn "sandbags_crush"} //from CtA
			{delete}
		}
	}
}

{"showcase"
	{on "break_window"
		{area disable}
	}
}

{"fountain_small"
	{on spawn
		{add_view "drops_water_fountain" "water" "FX_water"}
		{add_view "drops_water_fountain" "water" "FX_water1"}
		{add_view "drops_water_fountain" "water" "FX_water2"}
		{add_view "drops_water_fountain" "water" "FX_water3"}
		{add_view "fountain_small" "water" "FX_water4"}
		{link_sound "water" "world/water/small"}
		{view start "water"}
		{play_sound "water" 1}
	}
	{on "cut_pieces"
		{stop_sound "water"}
	}
}

{"waterfall_big"
	{on spawn
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall1"	}
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall2"	}
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall3"	}
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall4"	}
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall5"	}
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall6"	}
		{add_view "waterfall_sm"	"wfall"	"FX_waterfall7"	}
		{view start "wfall"}
	}
}


{"steam_small"
	{on spawn
		{add_view "steam" "smoke" "FX_steam"}
		{view start "smoke"}
	}
}

{"steam_big"
	{on spawn
		{add_view "smoke_black" "smoke" "FX_steam"}
		{view start "smoke"}
	}
}

{"sewer"
	{on spawn
		{call "update_area"}
		{ani_play "open"}
	}
	{on "update_area"
		{if "opened"
			{area enable "sewer"}
		else
			{area disable "sewer"}
		}
	}
	{on "open"
		{ani_play "open" +1 resume}
		{set "opened" 1}
		{call "update_area"}
	}
	{on "close"
		{ani_play "open" -1 resume}
		{set "opened" 0}
		{call "update_area"}
	}
}

{"delete_after_crush"
	{on "break"
		{delete}
	}
}

{"boat_trap"
	{on "open"
		{land off}
		{ani_wind "land" end}
		{ani_play "open"}
		{delay 0.1
			{land on}
			{area disable "left"}
			{area disable "right"}
		}
	}
	{on "close"
		{land off}
		{ani_wind "land" begin}
		{ani_play "open" -1}
		{delay 5
			{land on}
			{area enable "left"}
			{area enable "right"}
		}
	}
}

{"oiltower"
	{on spawn
		{call "add_fire"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_fire" overload
		{add_view "smoke_dead_tree1"	"fx" "fx_fire"}
	}
}

{"animation"
	{on spawn
		{ani_play "animation" loop}
	}
}

{"animation2"
	{on spawn
		{ani_play "animation" loop}
		{ani_play "animation2" loop}
	}
}

{"tag_crushed"
	{on break_armor
		{if not "broken"
			{set "broken" 1}
			{tags add "crushed"}
			{spawn "smoke_black" "root"}
		}
	}
}
