
(Include "\[SC_Plataform]\SC_helpers\inventory_item\SC_inventory_item.inc")

; =====================================================
; // ENTITY/WEAPON/DEF
; =====================================================

(Define "SC/Entity/"
	("Entity" args tyr_kraken_t4_04)
)
; =====================================================
; // SET/STUFF/WEAPON
; =====================================================

(Define "SC/Stuff/"
	{from "sc_skin_inventory_item"	{entity "tyr_kraken_t4_04"}}
)






