
(Define "Deff_Dread"
	{bone "engine"
		{parameters "ID=engine;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/engine.ply"}
	}
	{bone "leftleg"
		{parameters "ID=trackleft;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/leftleg.ply"}
	}
	{bone "rightleg"
		{parameters "ID=trackright;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/rightleg.ply"}
	}
	{bone "leftarm"
		{parameters "ID=gun;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/leftarm.ply"}
	}
	{bone "rightarm"
		{parameters "ID=gun;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/rightarm.ply"}
	}
	{bone "body"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/body.ply"}
	}
	{bone "mad_dread"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/mad_dread.ply"}
	}
)