
; Check instructions in: "/set/breed/SC_Plataform/[MP]/SC_Skin_Selector.inc"

(Include "[Randomizer]/LV40k_ogryn.inc")
(Include "[Randomizer]/LV40k_guardsmen.inc")
(Include "[Randomizer]/LV40k_guardsmen_ultra.inc")

(Define "LV40k_MP_Breeds_IG"

;================================================================================================================================================;
; // Cadian
;================================================================================================================================================;

;//										skin_breed_name						skin_skeleton				randomizer_ID

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t1_01						GEM_Default					LV40k_Guardsmen_000)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t1_02						GEM_Default					LV40k_Guardsmen_000)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t1_03						GEM_Default					LV40k_Guardsmen_000)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t1_04						GEM_Default					LV40k_Guardsmen_000)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_01						GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_02						GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_03						GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_04						GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_05						GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_06						GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t2_sq_01					GEM_Default					LV40k_Guardsmen_002)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_01						GEM_Default					LV40k_Guardsmen_003)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_02						GEM_Default					LV40k_Guardsmen_003)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_03						GEM_Default					LV40k_Guardsmen_003)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_04						GEM_Default					LV40k_Guardsmen_003)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_05						GEM_Default					LV40k_Guardsmen_003)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_06						GEM_Default					LV40k_Guardsmen_007)	; // <- sniper 
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t3_sq_01					GEM_Default					LV40k_Guardsmen_004)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_01						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_02						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_03						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_04						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_05						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_06						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_07						GEM_Default					LV40k_Kasrkin_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_08						GEM_Default					LV40k_Scions_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_09						GEM_Default					LV40k_Scions_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_10						GEM_Default					LV40k_Scions_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_sq_01					GEM_Default					LV40k_Kasrkin_002)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t4_sq_02					GEM_Default					LV40k_Scions_002)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t5_01						LV40k_Ogryn					LV40k_Ogryn_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t5_02						LV40k_Ogryn					LV40k_Ogryn_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_t5_sq_01					LV40k_Ogryn					LV40k_Ogryn_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_assassin_01			GEM_Default					LV40k_A_Vindicare_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_assassin_02			GEM_Default					LV40k_A_Vindicare_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_assassin_03			GEM_Default					LV40k_A_Vindicare_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_assassin_04			GEM_Default					LV40k_A_Vindicare_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_assassin_05			GEM_Default					LV40k_A_Vindicare_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_Castellan_01			GEM_Default					LV40k_Castellan_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_lieutenant_01			GEM_Default					LV40k_Lieutenant_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_commissar_01			GEM_Default					LV40k_Commissar_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_commissar_02			GEM_Default					LV40k_Commissar_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_inquisitor_01			GEM_Default					LV40k_Inquisitor_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_inquisitor_02			GEM_Default					LV40k_Inquisitor_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_artilleryman_01		GEM_Default					LV40k_Guardsmen_005)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_at_01					GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_at_02					GEM_Default					LV40k_Guardsmen_003)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_flamer_01				GEM_Default					LV40k_Guardsmen_001)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_flamer_02				GEM_Default					LV40k_Guardsmen_003)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_medic_01				GEM_Default					LV40k_Guardsmen_008)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_medic_02				GEM_Default					LV40k_Guardsmen_008)
	
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_psyker_01				GEM_Default					LV40k_Psyker_001)
	
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_tankman_01				GEM_Default					LV40k_Guardsmen_009)
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_tankman_02				GEM_Default					LV40k_Guardsmen_009)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_pilot_01				GEM_Default					LV40k_Guardsmen_001)
	
("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_techpriest_01			GEM_Default					LV40k_Techpriest_001)

("SC_Skin_Tag_Selector"		args	%0	ig_cadian_tx_vox_01					GEM_Default					LV40k_Guardsmen_010)

;================================================================================================================================================;
; // Ultramar
;================================================================================================================================================;

;//										skin_breed_name						skin_skeleton				randomizer_ID

("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t1_01						GEM_Default					LV40k_Guardsmen_Ultra_001)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t1_02						GEM_Default					LV40k_Guardsmen_Ultra_001)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t1_03						GEM_Default					LV40k_Guardsmen_Ultra_001)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t1_04						GEM_Default					LV40k_Guardsmen_Ultra_001)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t1_sq_01					GEM_Default					LV40k_Guardsmen_Ultra_002)

("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t3_01						GEM_Default					LV40k_Guardsmen_Ultra_003)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t3_02						GEM_Default					LV40k_Guardsmen_Ultra_003)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t3_03						GEM_Default					LV40k_Guardsmen_Ultra_003)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t3_04						GEM_Default					LV40k_Guardsmen_Ultra_003)
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_t3_sq_01					GEM_Default					LV40k_Guardsmen_Ultra_004)

("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_tx_artilleryman_01			GEM_Default					LV40k_Guardsmen_005)

("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_tx_medic_01					GEM_Default					LV40k_Guardsmen_008)
	
("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_tx_tankman_01				GEM_Default					LV40k_Guardsmen_009)

("SC_Skin_Tag_Selector"		args	%0	ig_ultramar_tx_vox_01					GEM_Default					LV40k_Guardsmen_010)

)