
(Define "Base_Venerable"
	{bone "dread_venerable_torso"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/dread_venerable_torso.ply"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/marine_helmet.ply"}
	}
	{bone "leg_armor_venerable1"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/leg_armor_venerable1.ply"}
	}
	{bone "leg_armor_venerable2"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/leg_armor_venerable2.ply"}	{Visibility 0}
	}
	{bone "torso_venerable1"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/torso_venerable1.ply"}	{Visibility 0}
	}
	{bone "torso_venerable2"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/torso_venerable2.ply"}
	}
	{bone "torso_venerable3"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/torso_venerable3.ply"}	{Visibility 0}
	}
	{bone "toes"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/toes.ply"}
	}
	{bone "tabard"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/tabard.ply"}
	}
	{bone "banner"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/banner_pole.ply"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/banner_banner_v1.ply"}
	}
)