
(Define "T_Hydra"
	{bone "right_arm"
		{parameters "ID=gun;"}
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			2.88774	5.78621	36.0102
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/right_arm.ply"}
		{bone "barrel_r1"
			{parameters "ID=gun;"}
			{Position 55.9744	1.01361	9.7169}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/barrel_r1.ply"}
			{bone "barrel02"
				{Matrix34
					1	0	0
					0	1	0
					0	0	1
					40.5669	1.52588e-05	0
				}
			}
		}
		{bone "ammo_rot_r2"
			{parameters "ID=gun;"}
			{Position -3.04209	-4.42794	-7.16893}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/ammo_rot_r2.ply"}
		}
		{bone "ammo_rot_r1"
			{parameters "ID=gun;"}
			{Position -13.8726	-4.42794	12.3715}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/ammo_rot_r1.ply"}
		}
		{bone "barrel_r2"
			{parameters "ID=gun;"}
			{Position 67.5077	1.01361	-9.84352}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/barrel_r2.ply"}
			{bone "barrel03"
				{Matrix34
					1	0	0
					0	1	0
					0	0	1
					40.5041	2.28882e-05	-2.28882e-05
				}
			}
		}
		{bone "fxshell03"
			{Matrix34
				1	0	0
				0	1	0
				0	0	1
				14.5851	-2.78815	-12.0267
			}
		}
		{bone "fxshell02"
			{Matrix34
				1	0	0
				0	1	0
				0	0	1
				3.6377	-2.78819	7.60751
			}
		}
	}
	{bone "left_arm"
		{parameters "ID=gun;"}
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			2.8878	5.7861	-36.0098
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/left_arm.ply"}
		{bone "ammo_rot_l1"
			{parameters "ID=gun;"}
			{Position -13.8726	4.4289	12.3726}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/ammo_rot_l1.ply"}
		}
		{bone "ammo_rot_l2"
			{parameters "ID=gun;"}
			{Position -3.0421	4.4289	-7.16888}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/ammo_rot_l2.ply"}
		}
		{bone "barrel_l1"
			{parameters "ID=gun;"}
			{Position 55.9745	-1.0126	9.71693}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/barrel_l1.ply"}
			{bone "barrel00"
				{Matrix34
					1	0	0
					0	1	0
					0	0	1
					40.5669	3.8147e-05	0
				}
			}
		}
		{bone "barrel_l2"
			{parameters "ID=gun;"}
			{Position 67.5078	-1.0126	-9.84349}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hydra/barrel_l2.ply"}
			{bone "barrel01"
				{Matrix34
					1	0	0
					0	1	0
					0	0	1
					40.5041	2.67029e-05	0
				}
			}
		}
		{bone "fxshell01"
			{Matrix34
				1	0	0
				0	1	0
				0	0	1
				14.585	2.85435	-12.0265
			}
		}
		{bone "fxshell00"
			{Matrix34
				1	0	0
				0	1	0
				0	0	1
				3.63765	2.8543	7.60761
			}
		}
	}
	{bone "foresight3"
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			99.4292	3.83769	-0.00459921
		}
	}
)