
(Define "T_Imperial"
	{bone "t_imperial"
		{parameters "ID=turret;"}
		{Position 0.577053	0	-78.3599}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/t_imperial.ply"}
	}
	{bone "turret_decals"
		{Position 0.577053	0	-78.3599}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/turret_decals.ply"}
	}
	{bone "t_antenna"
		{parameters "ID=turret;"}
		{Position -29.0217	29.9022	49.2191}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/t_antenna.ply"}
	}
	{bone "antenna_animation_bone"
		{Position -31.4926	29.9022	79.5052}
	}
)