
(Define "Model_Path"
	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Heavy_Infantry/Tyr_Carnifex/%0.ply"} 
)

(Define "models_hellfex_devourers"
	{bone "Models"	
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		
		{bone "w_devourer_up"		("Model_Path" args w_devourer_up)		{Visibility 1}}
		{bone "w_devourer_down"		("Model_Path" args w_devourer_down)		{Visibility 1}}
	}
)
(Define "models_carnifex_oldoneeye"
	{bone "Models"
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "upper_talons"		("Model_Path" args upper_talons)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_crushing_claws"	("Model_Path" args w_crushing_claws)	{Visibility 1}}
		{bone "OOE_Thornback"		("Model_Path" args OOE_Thornback)		{Visibility 1}}
	}
)

(Define "models_carnifex_melee"
	{bone "Models"
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "upper_talons"		("Model_Path" args upper_talons)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_crushing_claws"	("Model_Path" args w_crushing_claws)	{Visibility 1}}
	}
)

(Define "models_carnifex_venom_cannon"
	{bone "Models"
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "upper_talons"		("Model_Path" args upper_talons)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_venom_cannon"		("Model_Path" args w_venom_cannon)		{Visibility 1}}
	}
)

(Define "models_carnifex_barbed_strangler"
	{bone "Models"	
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "upper_talons"		("Model_Path" args upper_talons)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_barbed_strangler"	("Model_Path" args w_barbed_strangler)	{Visibility 1}}
	}
)

(Define "models_carnifex_melee_dev"
	{bone "Models"
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "upper_talons"		("Model_Path" args upper_talons)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_devourer_down"		("Model_Path" args w_devourer_down)		{Visibility 1}}
	}
)

(Define "models_carnifex_venom_cannon_dev"
	{bone "Models"
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "w_devourer_up"		("Model_Path" args w_devourer_up)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_venom_cannon"		("Model_Path" args w_venom_cannon)		{Visibility 1}}
	}
)

(Define "models_carnifex_barbed_strangler_dev"
	{bone "Models"	
		{bone "body"				("Model_Path" args body)				{Visibility 1}}
		{bone "head"				("Model_Path" args head)				{Visibility 1}}
		{bone "w_devourer_up"		("Model_Path" args w_devourer_up)		{Visibility 1}}
		{bone "w_tail_end"			("Model_Path" args w_tail_end)			{Visibility 1}}
		{bone "w_barbed_strangler"	("Model_Path" args w_barbed_strangler)	{Visibility 1}}
	}
)