
(Define "Predator_Turret_Ork"
	{bone "predator_ork_turret"
		{parameters "ID=turret;"}
		{Position 0	-2.43863e-05	0.000152588}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/rhino_chassis/predator_ork/predator_ork_turret.ply"}
		{bone "ork_predator_smoke6"
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				-12.5422	-34.4642	42.5009
			}
		}
		{bone "ork_predator_smoke5"
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				-6.63768	43.2216	28.7942
			}
		}
	}
)