(define "phrase_voice_deal_rus"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/rus_unique/%3/v%2"}
		{text_dbg "(%1) rus_unique/%3/v%2"}
	}
)

(define "phrase_voice_deal_ger"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/ger_unique/%3/v%2"}
		{text_dbg "(%1) ger_unique/%3/v%2"}
	}
)

(define "phrase_voice_deal_usa"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/usa_assault/%3/v%2"}
		{text_dbg "(%1) usa_assault/%3/v%2"}
	}
)

(define "phrase_voice_dealva_rus"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/rus/%3/v%2"}
		{text_dbg "(%1) rus/%3/v%2"}
	}
)

(define "phrase_voice_dealva_ger"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/ger/%3/v%2"}
		{text_dbg "(%1) ger/%3/v%2"}
	}
)

(define "phrase_voice_dealva_usa"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/usa_rifleman/%3/v%2"}
		{text_dbg "(%1) usa_rifleman/%3/v%2"}
	}
)

(define "phrase_voice_dealva_eng"
	{phrase
		{language "%1"}
		{voice %2}
		{sound "talk/%0/eng/%3/v%2"}
		{text_dbg "(%1) eng/%3/v%2"}
	}
)