(define "phrases"	; args: actor | language | voice | foldername
	("phrase_voice_target" args %0 rus 1 %1 rus1 1)
	("phrase_voice_target" args %0 rus 2 %1 rus1 2)
	
	("phrase_voice" args %0 rus 1 %1)
	("phrase_voice" args %0 rus 2 %1)
	("phrase_voice" args %0 rus 3 %1)
	("phrase_voice" args %0 rus 4 %1)
	("phrase_voice" args %0 rus 5 %1)
	("phrase_voice" args %0 rus 6 %1)
	("phrase_voice" args %0 rus 7 %1)
	("phrase_voice" args %0 rus 8 %1)
	
	("phrase_voice" args %0 ger 1 %1)
	("phrase_voice" args %0 ger 2 %1)
	("phrase_voice" args %0 ger 3 %1)
	("phrase_voice" args %0 ger 4 %1)
	("phrase_voice" args %0 ger 5 %1)
	("phrase_voice" args %0 ger 6 %1)
	("phrase_voice" args %0 ger 7 %1)
	("phrase_voice" args %0 ger 8 %1)

	("phrase_voice" args %0 ger_officer 1 %1)
	("phrase_voice" args %0 ger_medic   1 %1)
	("phrase_voice" args %0 ger_sniper  1 %1)

	("phrase_voice" args %0 spa 1 %1)
	
	("phrase_voice" args %0 kor 1 %1)	
	("phrase_voice" args %0 kor 2 %1)
	("phrase_voice" args %0 kor2 1 %1)	
	("phrase_voice" args %0 kor2 2 %1)
	("phrase_voice" args %0 kor_med 1 %1)	
	("phrase_voice" args %0 kor_med 2 %1)	
	("phrase_voice" args %0 kor_ammo 1 %1)	
	("phrase_voice" args %0 kor_ammo 2 %1)		
	("phrase_voice" args %0 fin 1 %1)
	("phrase_voice" args %0 fin 2 %1)
	("phrase_voice" args %0 fin 3 %1)
	("phrase_voice" args %0 fin 4 %1)
	("phrase_voice" args %0 fin 5 %1)

	("phrase_voice" args %0 usa 1 %1)
	("phrase_voice" args %0 usa 2 %1)
	("phrase_voice" args %0 usa 3 %1)
	("phrase_voice" args %0 usa 4 %1)
;	("phrase_voice" args %0 usa 5 %1)

	("phrase_voice" args %0 usa_officer 1 %1)
	("phrase_voice" args %0 usa_medic 1 %1)
	("phrase_voice" args %0 usa_medic 2 %1)
	("phrase_voice" args %0 usa_sniper 1 %1)

	("phrase_voice" args %0 ukr 1 %1)
	("phrase_voice" args %0 ukr 2 %1)
	("phrase_voice" args %0 ukr 3 %1)

	("phrase_voice" args %0 yug 1 %1)

;	("phrase_voice" args %0 fra 1 %1)
	("phrase_voice" args %0 eng 1 %1)
	("phrase_voice" args %0 eng 2 %1)
	("phrase_voice" args %0 eng 3 %1)
	("phrase_voice" args %0 eng 4 %1)

	("phrase_voice" args %0 eng_para 1 %1)
	("phrase_voice" args %0 eng_para 2 %1)
	("phrase_voice" args %0 eng_para 3 %1)

	("phrase_voice_target" args %0 nato 1 %1 pol 1)
	("phrase_voice_target" args %0 nato 2 %1 pol 2)
	("phrase_voice_target" args %0 nato 3 %1 pol 3)
	("phrase_voice_target" args %0 nato 1 %1 fra 4)
	("phrase_voice_target" args %0 nato 2 %1 fra 5)
	("phrase_voice_target" args %0 nato 3 %1 fra 6)
	("phrase_voice_target" args %0 nato 1 %1 ita_vet 7)
	("phrase_voice_target" args %0 nato 2 %1 ita_vet 8)
	("phrase_voice_target" args %0 nato 1 %1 ita 9)
	("phrase_voice_target" args %0 nato 2 %1 ita 10)
	("phrase_voice_target" args %0 nato 3 %1 ita 11)
	("phrase_voice_target" args %0 nato 1 %1 can 12)
	("phrase_voice_target" args %0 nato 2 %1 can 13)
	("phrase_voice_target" args %0 nato 1 %1 ger 14)
	("phrase_voice_target" args %0 nato 2 %1 ger 15)
	("phrase_voice_target" args %0 nato 3 %1 ger 16)
	("phrase_voice_target" args %0 nato 1 %1 usa 17)
	("phrase_voice_target" args %0 nato 2 %1 usa 18)
	("phrase_voice_target" args %0 nato 1 %1 fin 19)
	("phrase_voice_target" args %0 nato 2 %1 fin 20)
	("phrase_voice_target" args %0 nato 3 %1 fin 21)
	("phrase_voice" args %0 chi 1 %1)	
	("phrase_voice" args %0 chi 2 %1)
		
;new by ve mod

	("phrase_voice" args %0 ger_fallschirmjaeger  1 %1)
	("phrase_voice" args %0 ger_fallschirmjaeger  2 %1)

	("phrase_voice" args %0 ger_jaeger  1 %1)

	("phrase_voice" args %0 ger_officer 2 %1)
	("phrase_voice" args %0 ger_officer 3 %1)
	("phrase_voice" args %0 ger_officer 4 %1)

	("phrase_voice" args %0 ger_panzergrenadier  1 %1)
	("phrase_voice" args %0 ger_panzergrenadier  2 %1)

	("phrase_voice" args %0 ger_pzpio 1 %1)

	("phrase_voice_target" args %0 ger_sniper 2 %1 ger_sniper 1)

	("phrase_voice" args %0 ger_sttroop 1 %1)

	("phrase_voice" args %0 rus_guards 1 %1)

	("phrase_voice" args %0 rus_conscript 1 %1)

	("phrase_voice" args %0 rus_sniper 1 %1)

	("phrase_voice" args %0 rus_unique 1 %1)
	("phrase_voice" args %0 rus_unique 2 %1)
	("phrase_voice" args %0 rus_unique 3 %1)
	("phrase_voice" args %0 rus_unique 4 %1)

	("phrase_voice" args %0 rus_elite 1 %1)

	("phrase_voice" args %0 usa_lt1 1 %1)
	("phrase_voice" args %0 usa_lt2 1 %1)
	("phrase_voice" args %0 usa_cpt 1 %1)
	("phrase_voice" args %0 usa_major 1 %1)

	("phrase_voice" args %0 usa_pathfinder 1 %1)

	("phrase_voice" args %0 usa_ranger 1 %1)
	("phrase_voice" args %0 usa_ranger 2 %1)

	("phrase_voice" args %0 usa_paratrooper 1 %1)
	("phrase_voice" args %0 usa_paratrooper 2 %1)

	("phrase_voice" args %0 usa_rifleman 1 %1)
	("phrase_voice" args %0 usa_rifleman 2 %1)
	("phrase_voice" args %0 usa_rifleman 3 %1)
	("phrase_voice" args %0 usa_rifleman 4 %1)

	("phrase_voice" args %0 usa_bazooka 1 %1)

	("phrase_voice_target" args %0 usa_sniper 2 %1 usa_sniper 1)

	("phrase_voice" args %0 usa_assault 1 %1)
	("phrase_voice" args %0 usa_assault 2 %1)
	("phrase_voice" args %0 usa_assault 3 %1)	
)