(define "phrases_cannon"	; args: actor | language | voice | foldername
	("phrase_voice" args %0 rus 1 %1)

	("phrase_voice_target" args %0 ukr 1 %1 rus 1)

	("phrase_voice" args %0 ger 1 %1)

	("phrase_voice" args %0 fin 1 %1)
	("phrase_voice" args %0 fin 2 %1)
	("phrase_voice" args %0 fin 3 %1)

	("phrase_voice" args %0 usa 1 %1)
;	("phrase_voice" args %0 usa 2 %1)
;	("phrase_voice" args %0 usa 3 %1)
;	("phrase_voice" args %0 usa 4 %1)

;	("phrase_voice" args %0 fra 1 %1)

	("phrase_voice" args %0 eng 1 %1)
	("phrase_voice_eng_va_tank" args %0 eng_para 1 %1)

	("phrase_voice_target" args %0 nato 1 %1 usa 1)
	("phrase_voice_target" args %0 nato 1 %1 ger 2)
	("phrase_voice_target" args %0 nato 1 %1 eng 3)
	("phrase_voice_target" args %0 nato 1 %1 fin 4)
)