
{"Xenos"
	{title "mp/alliance/Xenos"}
	{armies "ork"}
	{armies "tyr"}

;	{armies "eld"}	; // <- unreleased

	{icon "/interface/pages/multi/flag_Xenos"}
}

{"Imperium"
	{title "mp/alliance/Imperium"}
	{armies "sms"}
	
;	{armies "igc"}	; // <- unreleased
	
	{icon "/interface/pages/multi/flag_Imperium"}
}

{"Chaos"
	{title "mp/alliance/Chaos"}
	{armies "csm"}
	{armies "dch"}
	{armies "igt"}
	{icon "/interface/pages/multi/flag_Chaos"}
}
