
(Define "T_Wyvern"
	{bone "Wyvern"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/wyvern/wyvern.ply"}
		
		{bone "barrel00"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				31.8112	15.7295	35.2964
			}
		}
		{bone "barrel01"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				31.8112	15.7295	-35.2999
			}
		}
		{bone "barrel03"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				42.4858	-4.04943	-35.1424
			}
		}
		{bone "barrel04"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				42.4858	-4.04943	35.1332
			}
		}
	}
)