
(Define "SR_Lascannon"
	{bone "r_lascannon"
		{parameters "ID=aux_turret1;"}
		{Matrix34
			0	0	-1
			-1	0	0
			0	1	0
			14.3013	-0.219719	0.028862
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dorn_chassis/r_lascannon.ply"}
		{bone "fx_R_lascannon"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				0.191025	8.22082	4.40789
			}
		}
		{bone "foresight_R_lascannon"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-0.0210495	-21.3874	-0.8228
			}
		}
	}
)