(define "items_light"
	;{item "4x30"	"ammo" 100}
	;{item "5x39"	"ammo" 100}
	;{item "5x39"	"r7n10"	"ammo" 100}
	;{item "5x45"	"ammo" 100}
	;{item "5x45"	"m855a1"	"ammo" 100}
	;{item "7x39"	"ammo" 100}
	;{item "7x51"	"ammo" 100}
	;{item "7x51"	"m80a1"	"ammo" 100}
	;{item "7x54"	"ammo" 100}
	;{item "7x54"	"r7n1"	"ammo" 100}
	;{item "7x67"	"ammo" 100}
	;{item "9x18"	"ammo" 100}
	;{item "9x19"	"ammo" 100}
	;{item "9x39"	"ammo" 100}
	;{item "9x64"	"ammo" 100}
	;{item "11x23"	"ammo" 100}
	{item "12gauge"	"ammo" 100}
	{item "12x55"	"ammo" 100}
	;{item "12x99"	"ammo" 100}
	;{item "12x108"	"ammo" 100}

	{item "bekas-12m"						"ammo" 100}
        {item "m107a1"						"ammo" 100}
        {item "rpk16"						"ammo" 100}
        {item "asvk-m"						"ammo" 100}
        {item "g28"						"ammo" 100}
        {item "scar"						"ammo" 100}
        {item "m39"						"ammo" 100}

	{item "12gauge"	"no4"	"ammo" 100}
	{item "12gauge"	"slug"	"ammo" 100}
	
	{item "ks23_shell"	"ammo" 100}
	{item "ks23_shell"	"no4"	"ammo" 100}
	{item "ks23_shell"	"slug"	"ammo" 100}
	
	{item "4x30"	"mp7_mag"	"4-hk"	"ammo" 100}
	
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"m193"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"m193trless"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"m855a1"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"m855a1trless"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"trless"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"mk262"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"mk262trless"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"mk318"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"mk318trless"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"m995"	"ammo" 100}
	{item "5x45"	"5x45_belt"	"5-56_rifle"	"5-56_mg"	"m995trless"	"ammo" 100}
	
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"ammo" 100}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"m193"	"ammo" 100}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"m196"	"ammo" 100}
	{item	"5x45_mag"	"m855a1"	"ammo" 60}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"m856"	"ammo" 100}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"m856a1"	"ammo" 100}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"mk262"	"ammo" 100}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"mk318"	"ammo" 100}
	{item "5x45"	"5x45_mag"	"5-56_rifle"	"m995"	"ammo" 100}
	
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m80a1"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m80a1trless"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m118"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m118lr"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m118trless"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m118lrtrless"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"mk316"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"mk316trless"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"trless"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m959"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m959trless"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m993"	"ammo" 100}
	{item "7x51"	"7x51_belt"	"7-62_nato"	"7-62_mg"	"m993trless"	"ammo" 100}
	
	{item "7x51"	"7x51_clip"	"7-62_nato"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m80a1"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m62a1"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m118"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m118lr"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"mk316"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m62"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m948"	"ammo" 100}
	{item "7x51"	"7x51_clip"	"7-62_nato"	"m993"	"ammo" 100}
	
	{item "7x51"	"7x51_mag"	"7-62_nato"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m80a1"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m62a1"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m118"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m118lr"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"mk316"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m62"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m948"	"ammo" 100}
	{item "7x51"	"7x51_mag"	"7-62_nato"	"m993"	"ammo" 100}
	
	{item "7x67"	"awm_mag"	"300_wm"	"ammo" 100}
	
	{item "9x19"	"9x19_mag"	"9-smg"	"ammo" 100}
	{item "9x19"	"9x19_mag"	"9-smg"	"p"	"ammo" 100}
	{item "9x19"	"9x19_mag"	"9-smg"	"p2"	"ammo" 100}
	
	{item "9x19"	"9x19_pistol_mag"	"9-pistol"	"ammo" 100}
	{item "9x19"	"9x19_pistol_mag"	"9-pistol"	"p"	"ammo" 100}
	{item "9x19"	"9x19_pistol_mag"	"9-pistol"	"p2"	"ammo" 100}
	
	{item "9x19"	"uzi_mag"	"9-smg"	"ammo" 100}
	
	{item "11x23"	"45acp_mag"	"45-smg"	"ammo" 100}
	{item "11x23"	"45acp_pistol_mag"	"45-pistol"	"ammo" 100}
	
	{item "12x99"	"12x99_nato" "ammo" 100}
	{item "12x99"	"12x99_nato" "ap" "ammo" 100}
	{item "12x99"	"12x99_nato" "aphei" "ammo" 100}
	{item "12x99"	"12x99_nato" "api" "ammo" 100}
	{item "12x99"	"12x99_nato" "inc" "ammo" 100}
	{item "12x99"	"12x99_nato" "slap" "ammo" 100}
	{item "12x99"	"12x99_nato" "sn" "ammo" 100}
	
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"ammo" 100}
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"r7n6m"	"ammo" 100}
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"r7n10"	"ammo" 100}
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"r7n10tr"	"ammo" 100}
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"r7n22"	"ammo" 100}
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"r7t3"	"ammo" 100}
	{item "5x39"	"5x39_mag"	"5-45_rifle"	"r7t3m"	"ammo" 100}
	
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"ammo" 100}
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"r7n6m"	"ammo" 100}
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"r7n10"	"ammo" 100}
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"r7n10tr"	"ammo" 100}
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"r7n22"	"ammo" 100}
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"r7t3"	"ammo" 100}
	{item "5x39"	"rpk74_mag"	"5-45_rifle"	"r7t3m"	"ammo" 100}
	
	{item "7x39"	"7x39_belt"	"7x39_rifle"	"ammo" 100}
	{item "7x39"	"7x39_belt"	"7x39_rifle"	"m67"	"ammo" 100}
	{item "7x39"	"7x39_belt"	"7x39_rifle"	"r7n23"	"ammo" 100}
	{item "7x39"	"7x39_belt"	"7x39_rifle"	"r89"	"ammo" 100}
	{item "7x39"	"7x39_belt"	"7x39_rifle"	"ram2458"	"ammo" 100}
	{item "7x39"	"7x39_belt"	"7x39_rifle"	"t45m"	"ammo" 100}
	
	{item "7x39"	"7x39_drum"	"7x39_rifle"	"ammo" 100}
	{item "7x39"	"7x39_drum"	"7x39_rifle"	"m67"	"ammo" 100}
	{item "7x39"	"7x39_drum"	"7x39_rifle"	"r7n23"	"ammo" 100}
	{item "7x39"	"7x39_drum"	"7x39_rifle"	"r89"	"ammo" 100}
	{item "7x39"	"7x39_drum"	"7x39_rifle"	"ram2458"	"ammo" 100}
	{item "7x39"	"7x39_drum"	"7x39_rifle"	"t45m"	"ammo" 100}
	
	{item "7x39"	"7x39_clip"	"7x39_rifle"	"ammo" 100}
	
	{item "7x39"	"7x39_mag"	"7x39_rifle"	"ammo" 100}
	{item "7x39"	"7x39_mag"	"7x39_rifle"	"m67"	"ammo" 100}
	{item "7x39"	"7x39_mag"	"7x39_rifle"	"r7n23"	"ammo" 100}
	{item "7x39"	"7x39_mag"	"7x39_rifle"	"r89"	"ammo" 100}
	{item "7x39"	"7x39_mag"	"7x39_rifle"	"ram2458"	"ammo" 100}
	{item "7x39"	"7x39_mag"	"7x39_rifle"	"t45m"	"ammo" 100}
	
	{item "7x39"	"rpk_mag"	"7x39_rifle"	"ammo" 100}
	{item "7x39"	"rpk_mag"	"7x39_rifle"	"m67"	"ammo" 100}
	{item "7x39"	"rpk_mag"	"7x39_rifle"	"r7n23"	"ammo" 100}
	{item "7x39"	"rpk_mag"	"7x39_rifle"	"r89"	"ammo" 100}
	{item "7x39"	"rpk_mag"	"7x39_rifle"	"ram2458"	"ammo" 100}
	{item "7x39"	"rpk_mag"	"7x39_rifle"	"t45m"	"ammo" 100}
	
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7bt1"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7bt1trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"7bz3"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"7bz3trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n1"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n1trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n13"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n13trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n14"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n14trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n37"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"r7n37trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"trless"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"typed"	"ammo" 100}
	{item "7x54"	"7x54r_belt"	"7-62_rus"	"mg54r"	"typedtrless"	"ammo" 100}
	
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"r7bz3"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"r7n1"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"r7n13"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"r7n14"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"r7n37"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"r7t2"	"ammo" 100}
	{item "7x54"	"7x54r_mag"	"7-62_rus"	"typed"	"ammo" 100}
	
	{item "7x54"	"7x54r_clip"	"7-62_rus"	"ammo" 100}
	{item "7x54"	"7x54r_clip"	"7-62_rus"	"b30"	"ammo" 100}
	{item "7x54"	"7x54r_clip"	"7-62_rus"	"b32"	"ammo" 100}
	{item "7x54"	"7x54r_clip"	"7-62_rus"	"bs40"	"ammo" 100}
	{item "7x54"	"7x54r_clip"	"7-62_rus"	"pz"	"ammo" 100}
	{item "7x54"	"7x54r_clip"	"7-62_rus"	"r7n1"	"ammo" 100}
	
	{item "9x18"	"9x18_mag"	"makarov_pistol"	"ammo" 100}
	{item "9x18"	"ots02_mag"	"makarov_pistol"	"ammo" 100}
	{item "9x18"	"stechkin_mag"	"makarov_pistol"	"ammo" 100}
	
	{item "9x19"	"bizon_mag"	"9-smg"	"ammo" 100}
	{item "9x19"	"skorpion_mag"	"9-smg"	"ammo" 100}
	
	{item "9x39"	"9x39_mag"	"ammo" 100}
	{item "9x39"	"9x39_mag"	"bp"	"ammo" 100}
	{item "9x39"	"9x39_mag"	"r7n9"	"ammo" 100}
	{item "9x39"	"9x39_mag"	"spp"	"ammo" 100}
	
	{item "9x64"	"9x64_mag"	"9x64_rus"	"ammo" 100}
	
	{item "12x108"	"12x108_rus" "ap" "ammo" 100}
	{item "12x108"	"12x108_rus" "api" "ammo" 100}
	{item "12x108"	"12x108_rus" "api2" "ammo" 100}
	{item "12x108"	"12x108_rus" "hei" "ammo" 100}
	{item "12x108"	"12x108_rus" "sn" "ammo" 100}
	
	{item "14x114"	"atr" "14x114_rus" "api" "ammo" 10}
	{item "14x114"	"atr" "14x114_rus" "api2" "ammo" 10}
	{item "14x114"	"atr" "14x114_rus" "hei" "ammo" 10}
	
	{item "14x114" "14x114_rus" "api" "ammo" 100}
	{item "14x114" "14x114_rus" "api2" "ammo" 100}
	{item "14x114" "14x114_rus" "hei" "ammo" 100}

	{item "40x46"	"ammo" 2  {value 2}}
	{item "40x46"	"he"	"ammo" 2  {value 2}}
	{item "40x46"	"hedp"	"ammo" 2  {value 2}}
	{item "40x46"	"sm"	"ammo" 2  {value 2}}

	{item "vog25"	"ammo" 2  {value 2}}
	{item "vog25"	"he"	"ammo" 2  {value 2}}
	{item "vog25"	"he2"	"ammo" 2  {value 2}}
	{item "vog25"	"sm"	"ammo" 2  {value 2}}

	{item "carl_gustaf"	"he441d"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"heat551"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"heat551c"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"heat651"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"heat751"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"hedp502"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"mt756"	"ammo" 2  {value 2}}
	{item "carl_gustaf"	"smoke469c"	"ammo" 2  {value 2}}

	{item "fgm148_javelin"	"ammo" 1  {value 60}}

	{item "panzerfaust"	"ammo" 2  {value 2}}
	{item "panzerfaust"	"dm12a1"	"ammo" 2  {value 2}}
	{item "panzerfaust"	"dm22"	"ammo" 2  {value 2}}
	{item "panzerfaust"	"dm22i"	"ammo" 2  {value 2}}
	{item "panzerfaust"	"dm32"	"ammo" 2  {value 2}}

	{item "rpg7"	"ammo" 2  {value 2}}
	{item "rpg7"	"che"	"ammo" 2  {value 2}}
	{item "rpg7"	"chedp"	"ammo" 2  {value 2}}
	{item "rpg7"	"chei"	"ammo" 2  {value 2}}
	{item "rpg7"	"ct69heat"	"ammo" 2  {value 2}}
	{item "rpg7"	"ct69heati"	"ammo" 2  {value 2}}
	{item "rpg7"	"ct69heatii"	"ammo" 2  {value 2}}
	{item "rpg7"	"ct69heatiii"	"ammo" 2  {value 2}}
	{item "rpg7"	"ct84heat"	"ammo" 2  {value 2}}
	{item "rpg7"	"ctandem"	"ammo" 2  {value 2}}
	{item "rpg7"	"og7v"	"ammo" 2  {value 2}}
	{item "rpg7"	"pg7v"	"ammo" 2  {value 2}}
	{item "rpg7"	"pg7vl"	"ammo" 2  {value 2}}
	{item "rpg7"	"pg7vm"	"ammo" 2  {value 2}}
	{item "rpg7"	"pg7vr"	"ammo" 2  {value 2}}
	{item "rpg7"	"pg7vs"	"ammo" 2  {value 2}}
	{item "rpg7"	"pg7vs1"	"ammo" 2  {value 2}}
	{item "rpg7"	"tbg7v"	"ammo" 2  {value 2}}

	{item "rpg29"	"ammo" 2  {value 2}}
	{item "rpg29"	"pg29v"	"ammo" 2  {value 2}}
	{item "rpg29"	"tbg29v"	"ammo" 2  {value 2}}

	{item "pf98"	"dzp98"	"ammo" 2  {value 2}}
	{item "pf98"	"dzy98"	"ammo" 2  {value 2}}

	{item "smaw"	"ammo" 2  {value 2}}
	{item "smaw"	"heaa"	"ammo" 2  {value 2}}
	{item "smaw"	"hedp"	"ammo" 2  {value 2}}
	{item "smaw"	"ne"	"ammo" 2  {value 2}}

	{item "ags30"				"ammo" 2  {value 2}}
	{item "ags30"	"he"			"ammo" 2  {value 2}}
	{item "ags30"	"he2"			"ammo" 2  {value 2}}
	{item "ags30"	"he3"			"ammo" 2  {value 2}}
	{item "ags30"	"sm"			"ammo" 2  {value 2}}

	{item "mk19"				"ammo" 2  {value 2}}
	{item "mk19"	"he"			"ammo" 2  {value 2}}
	{item "mk19"	"he2"			"ammo" 2  {value 2}}
	{item "mk19"	"hedp"			"ammo" 2  {value 2}}
	{item "mk19"	"hedp2"			"ammo" 2  {value 2}}

	{item "spg9"		"heat"	"ammo" 1  {value 2}}
	{item "spg9"		"fg"	"ammo" 1  {value 2}}
	{item "bullet73"	"fg"	"ammo" 1  {value 5}}
	{item "bullet73"	"heat"	"ammo" 1  {value 5}}
	
	{item "bullet73"	"2a28"	"og15v"	"fg"	"ammo" 1  {value 5}}
	{item "bullet73"	"2a28"	"pg15v"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet73"	"2a28"	"pg15vnt"	"heatm3"	"ammo" 1  {value 5}}
	{item "bullet73"	"2a28"	"pg9n"	"heatm"	"ammo" 1  {value 5}}

	{item "napalm"	"ammo" 30  {value 15}}

	{item "81mm_mortar"			"fg" "ammo" 2 {value 2}}
	{item "81mm_mortar"			"sm" "ammo" 1 {value 2}}
	{item "82mm_mortar"			"fg" "ammo" 2 {value 2}}
	{item "82mm_mortar"			"sm" "ammo" 1 {value 2}}
	{item "120mm_2b11_mortar"	"fg" "ammo" 1 {value 2}}
	{item "120mm_krh40_mortar"	"fg" "ammo" 1 {value 2}}
	{item "120mm_m120_mortar"	"fg" "ammo" 1 {value 2}}
	{item "bandage" 2 {max 5}{value 1}}
)
(define "items_heavy"
	{item "bullet12"			"ammo" 50 {value 5}}
	{item "bullet12b"			"ammo" 50 {value 5}}
	{item "bullet15"			"ammo" 50 {value 5}}
	{item "bullet20"	"ap"	"ammo" 50 {value 5}}
	{item "bullet20"	"fg"	"ammo" 50 {value 5}}

	{item "bullet20"	"m61"	"zenite"	"m53"	"ap"	"ammo" 50 {value 5}}
	{item "bullet20"	"m61"	"zenite"	"m56"	"fg"	"ammo" 50 {value 5}}
	{item "bullet20"	"m61"	"zenite"	"mk149"	"apdsm"	"ammo" 50 {value 5}}
	{item "bullet20"	"m61"	"zenite"	"mk244"	"apdsm2"	"ammo" 50 {value 5}}
	{item "bullet20"	"m61"	"zenite"	"pgu28"	"ap2"	"ammo" 50 {value 5}}

	{item "bullet20"	"rh202"	"zenite"	"dm13a1"	"fg"	"ammo" 50 {value 5}}
	{item "bullet20"	"rh202"	"zenite"	"dm43"	"ap"	"ammo" 50 {value 5}}
	{item "bullet20"	"rh202"	"zenite"	"dm63"	"apdsm"	"ammo" 50 {value 5}}

	{item "bullet23"	"fg"	"ammo" 50 {value 5}}
	
	{item "bullet23"	"2a7"	"zenite"	"bzt"	"ap"	"ammo" 50 {value 5}}
	{item "bullet23"	"2a7"	"zenite"	"europ"	"apdsm"	"ammo" 50 {value 5}}
	{item "bullet23"	"2a7"	"zenite"	"ozt"	"fg"	"ammo" 50 {value 5}}
	{item "bullet23"	"2a7"	"zenite"	"pma276"	"apdsm2"	"ammo" 50 {value 5}}
	
	{item "bullet25"	"ap"	"ammo" 50 {value 5}}
	{item "bullet25"	"fg"	"ammo" 50 {value 5}}
	
	{item "bullet25"	"m242"	"zenite"	"m791"	"apdsm"	"ammo" 50 {value 5}}
	{item "bullet25"	"m242"	"zenite"	"m792"	"fg"	"ammo" 50 {value 5}}
	{item "bullet25"	"m242"	"zenite"	"m919"	"apfsds"	"ammo" 50 {value 5}}
	{item "bullet25"	"m242"	"zenite"	"saphei"	"ap"	"ammo" 50 {value 5}}
	
	{item "bullet30"	"ap"	"ammo" 50 {value 5}}
	{item "bullet30"	"fg"	"ammo" 50 {value 5}}
	
	{item "bullet30"	"2a42"	"zenite"	"m929"	"apfsds"	"ammo" 50 {value 5}}
	{item "bullet30"	"2a42"	"zenite"	"ubr11"	"apfsds"	"ammo" 50 {value 5}}
	{item "bullet30"	"2a42"	"zenite"	"ubr6"	"apbc"	"ammo" 50 {value 5}}
	{item "bullet30"	"2a42"	"zenite"	"ubr8"	"apdsm"	"ammo" 50 {value 5}}
	{item "bullet30"	"2a42"	"zenite"	"uof6"	"fg"	"ammo" 50 {value 5}}
	
	{item "bullet30"	"m230"	"m789"	"hedp"	"ammo" 50 {value 5}}
	
	{item "bullet30"	"mk44"	"zenite"	"abm"	"fg"	"ammo" 50 {value 5}}
	{item "bullet30"	"mk44"	"zenite"	"apdsm"	"ammo" 50 {value 5}}
	{item "bullet30"	"mk44"	"zenite"	"mk238"	"fg"	"ammo" 50 {value 5}}
	{item "bullet30"	"mk44"	"zenite"	"mk258"	"apfsds2"	"ammo" 50 {value 5}}
	{item "bullet30"	"mk44"	"zenite"	"nm225"	"apfsds"	"ammo" 50 {value 5}}
	{item "bullet30"	"mk44"	"zenite"	"pmc287"	"apfsds2"	"ammo" 50 {value 5}}
	{item "bullet30"	"mk44"	"zenite"	"pmc359"	"apfsds3"	"ammo" 50 {value 5}}

	{item "bullet40"	"365"	"zenite"	"abm"	"fg"	"ammo" 50 {value 5}}
	{item "bullet40"	"365"	"zenite"	"mk238"	"fg"	"ammo" 50 {value 5}}
	{item "bullet40"	"365"	"zenite"	"mk258"	"apfsds2"	"ammo" 50 {value 5}}
	{item "bullet40"	"365"	"zenite"	"pmc287"	"apfsds2"	"ammo" 50 {value 5}}
	
	{item "bullet70"	"fg"	"ammo" 1  {value 5}}
	{item "bullet73"	"fg"	"ammo" 1  {value 5}}
	{item "bullet73"	"heat"	"ammo" 1  {value 5}}
	
	{item "bullet73"	"2a28"	"og15v"	"fg"	"ammo" 1  {value 5}}
	{item "bullet73"	"2a28"	"pg15v"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet73"	"2a28"	"pg15vnt"	"heatm3"	"ammo" 1  {value 5}}
	{item "bullet73"	"2a28"	"pg9n"	"heatm"	"ammo" 1  {value 5}}

	{item "bullet76"	"d56t"	"bk350m"	"heatm"	"ammo" 1  {value 5}}
	{item "bullet76"	"d56t"	"bk354"	"aphe"	"ammo" 1  {value 5}}
	{item "bullet76"	"d56t"	"bk354n"	"apcr"	"ammo" 1  {value 5}}
	{item "bullet76"	"d56t"	"bk354p"	"apcr2"	"ammo" 1  {value 5}}
	{item "bullet76"	"d56t"	"of350m"	"fg"	"ammo" 1  {value 5}}
	
	{item "bullet80"	"fg"	"ammo" 1  {value 5}}
	{item "bullet100"	"fg"	"ammo" 1  {value 5}}
	{item "bullet100"	"atgm"	"ammo" 1  {value 15}}
	
	{item "bullet100"	"rus"	"2a70"	"arkan"	"atm3"	"ammo" 1  {value 15}}
	{item "bullet100"	"rus"	"2a70"	"bastion"	"atm"	"ammo" 1  {value 15}}
	{item "bullet100"	"rus"	"2a70"	"kan"	"atm2"	"ammo" 1  {value 15}}
	
	{item "bullet100"	"rus"	"aphe"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"aphebc"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"bk17m"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"bk5m"	"heatm"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"bm20"	"apfsds"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"bm25"	"apfsds2"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"bm8"	"apdsm"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of412"	"fg"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of17"	"fg"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of32"	"fg"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of70"	"fg"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of17"	"fg"	"2a70"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of32"	"fg"	"2a70"	"ammo" 1  {value 5}}
	{item "bullet100"	"rus"	"of70"	"fg"	"2a70"	"ammo" 1  {value 5}}
	
	{item "bullet105"	"ap"	"ammo" 1  {value 5}}
	{item "bullet105"	"fg"	"ammo" 1  {value 5}}
	{item "bullet105"	"heat"	"ammo" 1  {value 5}}
	
	{item "bullet105"	"m68"	"m68a1"	"dm12"	"heatm"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"dm13"	"apdsm"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"dm23"	"apfsds"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"dm33"	"apfsds2"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"dm502"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"dm63"	"apfsds3"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"fp105"	"apfsds9"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l28"	"apdsm"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l34"	"wp"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l35"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l35a3"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l36a1"	"apdsm2"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l52"	"apdsm3"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"l64a4"	"apfsds4"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m111"	"apfsds5"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m310"	"hedp"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m392"	"apdsm4"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m393a1"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m393a2"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m393a3"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m416"	"wp"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m426"	"apfsds6"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m428"	"apfsds7"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m456a1"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m456a2"	"heatm3"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m728"	"apdsm5"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m735"	"apfsds8"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m774"	"apfsds9"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"m833"	"apfsds10"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"me456a1"	"heatm4"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68"	"m68a1"	"nr132"	"heatm5"	"ammo" 1  {value 5}}
	{item "bullet105"	"m68a1"	"m900"	"apfsds11"	"ammo" 1  {value 5}}
	
	{item "bullet115"	"ap"	"ammo" 1  {value 5}}
	{item "bullet115"	"fg"	"ammo" 1  {value 5}}
	{item "bullet115"	"heat"	"ammo" 1  {value 5}}
	{item "bullet115"	"atgm"	"ammo" 1  {value 15}}
	
	{item "bullet115"	"2a20"	"bk15m"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bk4m"	"heatm"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bm21"	"apfsds4"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bm28"	"apfsds5"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bm36"	"apfsds6"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bm3"	"apfsds"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bm4"	"apfsds2"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"bm6"	"apfsds3"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"of11"	"fg"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"of18"	"fg"	"ammo" 1  {value 5}}
	{item "bullet115"	"2a20"	"of27"	"fg"	"ammo" 1  {value 5}}
	
	{item "bullet115"	"gun_missile"	"115mm_atgm"	"arkan"	"atm3"	"ammo" 1  {value 15}}
	{item "bullet115"	"gun_missile"	"115mm_atgm"	"bastion"	"atm"	"ammo" 1  {value 15}}
	{item "bullet115"	"gun_missile"	"115mm_atgm"	"kan"	"atm2"	"ammo" 1  {value 15}}
	
	{item "bullet120"	"ap"	"ammo" 1  {value 5}}
	{item "bullet120"	"fg"	"ammo" 1  {value 5}}
	{item "bullet120"	"heat"	"ammo" 1  {value 5}}
	
	{item "bullet120"	"l30"	"l15"	"apdsm"	"ammo" 1  {value 5}}
	{item "bullet120"	"l30"	"l23a1"	"apfsds"	"ammo" 1  {value 5}}
	{item "bullet120"	"l30"	"l26a1"	"apfsds2"	"ammo" 1  {value 5}}
	{item "bullet120"	"l30"	"l27a1"	"apfsds3"	"ammo" 1  {value 5}}
	{item "bullet120"	"l30"	"l28a1"	"apfsds4"	"ammo" 1  {value 5}}
	{item "bullet120"	"l30"	"l31a7"	"hesh"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet120"	"l30"	"l34"	"wp"	"indirect"	"ammo" 1  {value 5}}
	
	{item "bullet120"	"m256"	"l55a1"	"dm11"	"fg"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm12"	"heatm"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm12a1"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm13"	"apfsds"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm13a1"	"apfsds2"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm23"	"apfsds3"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm33"	"apfsds4"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm43"	"apfsds5"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm53"	"apfsds6"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"dm63"	"apfsds7"	"ammo" 1  {value 5}}
	{item "bullet120"	"l55a1"	"dm73"	"apfsds20"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"imhe"	"fg"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"k276"	"apfsds5"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"k277"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"k279"	"apfsds6"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"k279i"	"apfsds7"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"k280"	"hedp"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"kew"	"apfsds8"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"kewa1"	"apfsds9"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"kewa2"	"apfsds10"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"kewa3"	"apfsds18"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"kewa4"	"apfsds19"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m827"	"apfsds11"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m829"	"apfsds12"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m829a1"	"apfsds13"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m829a2"	"apfsds14"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m829a3"	"apfsds15"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m829a4"	"apfsds16"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m1147"	"amp"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m830"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m830a1"	"hedp"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"m908"	"heor"	"ammo" 1  {value 5}}
	{item "bullet120"	"m256"	"l55a1"	"ofl120f1"	"apfsds17"	"ammo" 1  {value 5}}
	
	{item "bullet125"	"ap"	"ammo" 1  {value 5}}
	{item "bullet125"	"fg"	"ammo" 1  {value 5}}
	{item "bullet125"	"heat"	"ammo" 1  {value 5}}
	{item "bullet125"	"atgm"	"ammo" 1  {value 15}}
	
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bk12m"	"heatm"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bk14m"	"heatm2"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bk18m"	"heatm3"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bk21b"	"heatm4"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bk29"	"heatm5"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bk31"	"heatm6"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm12"	"apfsds2"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm15"	"apfsds3"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm17"	"apfsds4"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm22"	"apfsds5"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm26"	"apfsds6"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm29"	"apfsds7"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm32"	"apfsds8"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm42"	"apfsds9"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm46"	"apfsds10"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"bm9"	"apfsds"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"dtb125"	"fg"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"dtp125"	"heatm7"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"eppsv97"	"apfsds20"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"m710"	"hedp"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"m711"	"apfsds18"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"m711mk2"	"apfsds22"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"of19"	"fg"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"of26"	"fg"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"of82"	"fg"	"indirect"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"p31"	"ap"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"pronit"	"apfsds19"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"type1"	"apfsds16"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"type2"	"apfsds17"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"type2m"	"apfsds21"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46m"	"2a82"	"bm44m"	"apfsds11"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46m"	"2a82"	"bm59"	"apfsds12"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a46m"	"2a82"	"bm60"	"apfsds13"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a82"	"bm69"	"apfsds14"	"ammo" 1  {value 5}}
	{item "bullet125"	"2a82"	"bm70"	"apfsds15"	"ammo" 1  {value 5}}
	
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"kobra"	"atm"	"ammo" 1  {value 15}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"kobram"	"atm2"	"ammo" 1  {value 15}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"refleks"	"atm4"	"ammo" 1  {value 15}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"refleksm"	"atm5"	"ammo" 1  {value 15}}
	{item "bullet125"	"2a46"	"2a46m"	"2a82"	"svir"	"atm3"	"ammo" 1  {value 15}}
	{item "bullet125"	"2a82"	"sprinter"	"atm6"	"ammo" 1  {value 15}}
	
	{item "bullet152"	"2a65"	"burnheretic"	"wp"	"ammo" 1  {value 15}}
	{item "bullet152"	"2a65"	"o23"	"icm"	"ammo" 1  {value 15}}
	{item "bullet152"	"2a65"	"of25"	"fg"	"ammo" 1  {value 15}}
	{item "bullet152"	"2a65"	"of39"	"gps"	"ammo" 1  {value 15}}
	{item "bullet152"	"2a65"	"of45"	"fg"	"ammo" 1  {value 15}}
	{item "bullet152"	"2a65"	"of61"	"fg"	"ammo" 1  {value 15}}

	{item "bullet155"	"m114"	"m107"	"fg"	"ammo" 1  {value 15}}
	{item "bullet155"	"m114"	"m110"	"wp"	"ammo" 1  {value 15}}
	{item "bullet155"	"m114"	"m483a1"	"dpicm"	"ammo" 1  {value 15}}
	{item "bullet155"	"m114"	"m549a1"	"fg"	"ammo" 1  {value 15}}
	{item "bullet155"	"m114"	"m795"	"fg"	"ammo" 1  {value 15}}
	{item "bullet155"	"m114"	"m982"	"gps"	"ammo" 1  {value 15}}

	{item "bullet125b"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet130"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet130b"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet130c"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet135"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet152"	"fg"	"ammo" 1  {value 15}}
	{item "bullet152"	"sm"	"ammo" 1  {value 15}}
	{item "bullet152"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet152b"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet155"	"fg"	"ammo" 1  {value 15}}
	{item "bullet155"	"sm"	"ammo" 1  {value 15}}
	{item "bullet159"	"atgm"	"ammo" 1  {value 15}}
	{item "bullet178"	"atgm"	"ammo" 1  {value 15}}
	{item "122mm_9m22u"			"ammo" 1  {value 5}}
	{item "grenade" "flare"	1 {value 5}}
	{item "grenade" "decoy"	1 {value 5}}
)


(define "supply_ammo"
	{extender "supply_zone"
		{resupply
			("items_light")
		}
		{radius 			8}		;resupply radius in meter
		{resupplyPeriod 	5}		;resupply period in seconds
		{regenerationPeriod 10}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				500}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "flag_ammo"
	{extender "supply_zone"
		{resupply
			("items_light")
		}
		{radius 			5}		;resupply radius in meter
		{resupplyPeriod 	5}		;resupply period in seconds
		{regenerationPeriod 10}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				500}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "flag_ammo_heavy"
	{extender "supply_zone"
		{resupply
			("items_light")
			("items_heavy")
		}
		{fuel {amount 50}{value 5}}
		{radius 			15}		;resupply radius in meter
		{resupplyPeriod 	5}		;resupply period in seconds
		{regenerationPeriod 10}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				750}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "bandage_ammo"
	{extender "supply_zone"
		{resupply
			{item "bandage" 2 {max 5}{value 1}}		
		}
		{radius 			10}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				500}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "fuel_ammo"
	{extender "supply_zone"
		{fuel {amount 20}{value 2}}
		{radius 			10}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				500}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "mbt_ammo"
	{extender "supply_zone"
		{resupply
			("items_light")
			("items_heavy")		
		}
		{radius 			10}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				75}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "ifv_ammo"
	{extender "supply_zone"
		{resupply
			("items_light")
			("items_heavy")		
		}
		{radius 			10}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				250}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "apc_ammo"
	{extender "supply_zone"
		{resupply
			("items_light")
			("items_heavy")		
		}
		{fuel {amount 20}{value 2}}
		{radius 			10}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				500}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "truck_ammo"
	{extender "supply_zone"
		{resupply
			("items_light")	
		}
		{fuel {amount 20}{value 2}}
		{radius 			15}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				500}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
(define "truck_ammo_heavy"
	{extender "supply_zone"
		{resupply
			("items_light")
			("items_heavy")		
		}
		{fuel {amount 20}{value 2}}
		{radius 			20}		;resupply radius in meter
		{resupplyPeriod 	2.5}	;resupply period in seconds
		{regenerationPeriod 15}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				750}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)