
(Define "Aux_Rokkit"
	{bone "R_Rokkit"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/R_rokkitlauncha.ply"}
	}
	{bone "r_ammo1"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_ammo1.ply"}
	}
	{bone "r_ammo2"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_ammo2.ply"}
	}
	{bone "r_ammo3"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_ammo3.ply"}
	}
	{bone "l_ammo1"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_ammo1.ply"}
	}
	{bone "l_ammo2"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_ammo2.ply"}
	}
	{bone "l_ammo3"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_ammo3.ply"}
	}
	{bone "L_Rokkit"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_rokkitlauncha.ply"}
	}
	{bone "l_base"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_base.ply"}
	}
	{bone "r_base"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_base.ply"}
	}
)