
(Define "C_HKM"
	{bone "hunter_killer_mount"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hunter_killer_mount.ply"}
		{bone "hunter_killer_missile"
			{Position 26.0404	35.812	62.4251}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/chimera_chassis/hunter_killer_missile.ply"}
		}
		{bone "fx_hkm"
			{Position 45.4396	31.367	57.826}
		}
		{bone "gun_rot3"
			{Position 54.0019	35.812	62.4251}
			{bone "foresight_hkm"
				{Matrix34
					1	0	0
					0	0	1
					0	-1	0
					-1.14441e-05	0	0
				}
			}
		}
	}
)