
{smooth 0}

{sequence "0_tear_hand1l"	{file "ASV5/0_tear_arm_l.anm"}}
{sequence "0_tear_hand1r"	{file "ASV5/0_tear_arm_r.anm"}}
{sequence "0_tear_head"		{file "ASV5/0_tear_head.anm"}}
{sequence "0_tear_Foot1l"	{file "ASV5/0_tear_leg_l.anm"}}
{sequence "0_tear_foot1r"	{file "ASV5/0_tear_leg_r.anm"}}

{sequence "SC_halo_flood_morph_test"	{file "sc_halo_flood_morph_test.anm"}}
{sequence "sc_hide_test"				{file "sc_hide_test.anm"} {Smooth 0}}

{sequence "SC_no_recoil"				{file "../z_dummy.anm"} {Smooth 0}}