
; ===========================================================================================================
; // SC LV40k DLC
; ===========================================================================================================

; // ORKS
{"evz_deff_dread_autocannon"				{vehicle_view "walker_one_gun"}}
{"evz_deff_dread_burna"						{vehicle_view "walker_one_gun"}}
{"evz_deff_dread_kannon"					{vehicle_view "walker_one_gun"}}
{"evz_deff_dread_megablasta"				{vehicle_view "walker_one_gun"}}
{"evz_deff_dread_rokkit"					{vehicle_view "walker_one_gun"}}
{"evz_deff_dread_shoota"					{vehicle_view "walker_one_gun"}}
{"evz_deff_dread_zzapgun"					{vehicle_view "walker_one_gun"}}

{"evz_gorkanaut"							{vehicle_view "walker_two_arms"}}
{"evz_morkanaut"							{vehicle_view "walker_two_arms"}}

{"evz_grot_sentry_turret"					{vehicle_view "vehicle_static_unarmed"}}

{"evz_gunwagon_flakk"						{vehicle_view "tank_turret_1gun"}}
{"evz_gunwagon_kannon"						{vehicle_view "tank_noturret_1gun"}}
{"evz_gunwagon_transport"					{vehicle_view "vehicle_tracks_unarmed"}}
{"evz_gunwagon_zzap"						{vehicle_view "tank_turret_1gun"}}

{"evz_grot_tank_shoota"						{vehicle_view "tank_turret_1gun"}}
{"evz_grot_tank_kannon"						{vehicle_view "tank_turret_1gun"}}
{"evz_grot_tank_rokkit"						{vehicle_view "tank_turret_1gun"}}

{"evz_kill_bursta_tank"						{vehicle_view "tank_noturret_1gun_2sponsons"}}

{"evz_ork_wartrakk"							{vehicle_view "tank_noturret_1gun"}}

{"evz_looted_lemanruss_rokkit_shoota"		{vehicle_view "tank_turret_1gun_3sponsons"}}
{"evz_looted_predator_zzap_hb_hb"			{vehicle_view "tank_turret_1gun_2sponsons"}}
{"evz_looted_predator_kannons_hb_hb"		{vehicle_view "tank_turret_2guns_2sponsons"}}

; // SPACE MARINES
{"ums_dread_HEL_assaultcannon"				{vehicle_view "walker_two_arms"}}
{"ums_dread_HEL_lascannon"					{vehicle_view "walker_two_arms"}}
{"ums_dread_IRC_hurricane"					{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_assaultcannon"				{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_autocannon"					{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_heavybolter"				{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_inferno"					{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_lascannon"					{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_multimelta"					{vehicle_view "walker_two_arms"}}
{"ums_dread_STD_plasmacannon"				{vehicle_view "walker_two_arms"}}
{"ums_dread_VEN_assaultcannon"				{vehicle_view "walker_two_arms"}}
{"ums_dread_VEN_plasmacannon"				{vehicle_view "walker_two_arms"}}

{"ums_droppod_dw"							{vehicle_view "vehicle_static_noturret_1gun"}}
{"ums_droppod"								{vehicle_view "vehicle_static_noturret_1gun"}}
{"ums_droppod_ammo"							{vehicle_view "vehicle_static_unarmed"}}
{"ums_droppod_dreadnought"					{vehicle_view "vehicle_static_unarmed"}}

{"UMS_landspeeder_HB_rocketpods"			{vehicle_view "gravtank_noturret_1gun"}}
{"UMS_landspeeder_HB_heavyflamer"			{vehicle_view "gravtank_noturret_1gun"}}
{"UMS_landspeeder_HB_multimelta"			{vehicle_view "gravtank_noturret_1gun"}}
{"UMS_landspeeder_MM_assaultcannon"			{vehicle_view "gravtank_noturret_1gun"}}

{"ums_predator_annihilator_lc_lc"			{vehicle_view "tank_turret_1gun_2sponsons"}}
{"ums_predator_autocannon_hb_hb"			{vehicle_view "tank_turret_1gun_2sponsons"}}
{"ums_predator_plasmacannon_hb_hb"			{vehicle_view "tank_turret_1gun_2sponsons"}}

{"ums_razorback_flamer"						{vehicle_view "tank_turret_1gun"}}
{"ums_razorback_hb"							{vehicle_view "tank_turret_1gun"}}
{"ums_razorback_lascannon"					{vehicle_view "tank_turret_1gun"}}

{"ums_whirlwind_artillery"					{vehicle_view "tank_turret_1gun"}}
{"ums_whirlwind_hunter"						{vehicle_view "tank_turret_1gun"}}

{"ums_rhino_damocles"						{vehicle_view "tank_turret_unarmed"}}
{"ums_rhino_h"								{vehicle_view "vehicle_tracks_unarmed"}}
{"ums_rhino_h_pintle"						{vehicle_view "vehicle_tracks_unarmed"}}
{"ums_rhino_h_sb"							{vehicle_view "vehicle_tracks_unarmed"}}
{"ums_rhino_u"								{vehicle_view "vehicle_tracks_unarmed"}}
{"ums_rhino_u_pintle"						{vehicle_view "vehicle_tracks_unarmed"}}
{"ums_rhino_u_sb"							{vehicle_view "vehicle_tracks_unarmed"}}
{"ums_rhino_vindicator"						{vehicle_view "tank_noturret_1gun"}}

{"ums_tarantula_beacon"						{vehicle_view "vehicle_static_unarmed"}}
{"ums_tarantula_hb"							{vehicle_view "vehicle_static_noturret_1gun"}}
{"ums_tarantula_ml"							{vehicle_view "vehicle_static_noturret_1gun"}}

{"freeblade_knight_crusader_1"				{vehicle_view "walker_two_arms"}}
{"freeblade_knight_errant_1"				{vehicle_view "walker_two_arms"}}
{"freeblade_knight_paladin_1"				{vehicle_view "walker_two_arms"}}
{"freeblade_knight_warden_1"				{vehicle_view "walker_two_arms"}}

{"UMS_landraider_redeemer"					{vehicle_view "tank_noturret_1gun_2sponsons"}}
{"UMS_landraider_crusader"					{vehicle_view "tank_noturret_1gun_2sponsons"}}
{"UMS_landraider_phobos"					{vehicle_view "tank_noturret_1gun_2sponsons"}}
{"UMS_landraider_prometheus"				{vehicle_view "tank_noturret_1gun_2sponsons"}}

; ~~~~~~~~~~~~~~~~~~~~ NEED UNIQUE VIEWS
;//{"evz_battlewagon_liftadrop"				{vehicle_view "tank_noturret_1gun"}}
;//{"evz_battlewagon_transport"	{vehicle_view "tank_noturret_1gun"}}
;//{"evz_battlewagon_kannon"	{vehicle_view "tank_noturret_1gun"}}

;//{"evz_ork_warbike"			{vehicle_view "tank_noturret_1gun"}}

;//{"evz_warbuggy_rokkits"		{vehicle_view "tank_noturret_1gun"}}
;//{"evz_warbuggy_shootas"		{vehicle_view "tank_noturret_1gun"}}
;//{"evz_warbuggy_zzap"			{vehicle_view "tank_noturret_1gun"}}

;//{"evz_wartrukk"								{vehicle_view "tank_noturret_1gun"}}
;//{"evz_wartrukk_ammo"						{vehicle_view "tank_noturret_1gun"}}
;//{"evz_wartrukk_burna"						{vehicle_view "tank_noturret_1gun"}}

;//{"UMS_landraider_helios"		{vehicle_view "tank_noturret_1gun"}}
;//{"UMS_landraider_terminus"	{vehicle_view "tank_noturret_1gun"}}

; // {"ums_thunderfire"							{vehicle_view "tank_noturret_1gun"}}

;//{"UMS_landspeeder_HB_multimelta_rocketpods"	{vehicle_view "tank_noturret_1gun"}}

;//{"ums_whirlwind_stalker"					{vehicle_view "tank_turret_1gun"}}



; ~~~~~~~~~~~~~~~~~~~~ USING VANILLA VIEWS
{"evz_ork_mekgun"	{vehicle_view "20mm_flakvierling38"}}
{"temp_ork_Flak_20mm_flakvierling38"	{vehicle_view "20mm_flakvierling38"}}
{"temp_ork_ammo_box"	{vehicle_view "inf_crate_ger"}}
{"temp_ork_76mm_m1927"	{vehicle_view "cannon_76mm_m1927"}}