
; // SORT IN INTERACTION ENTITY

(Define "Dread_Weapons_L_Missile_Launcher"
	{bone "weaponry_l"
		{bone "LW"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/L_Missile_Launcher.ply"}}
	}
)
(Define "Dread_Weapons_L_Claw"
	{bone "weaponry_l"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/l_claw.ply"} 
		{bone "LW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/claw_armflamer.ply"}}
	}
)
(Define "Dread_Weapons_L_Claw_Talons"
	{bone "weaponry_l"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/l_claw.ply"} 
		{bone "LW2"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/claw_talons.ply"}}
	}
)