
(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;


(define "Pattern_SM_Scouts_1"				("Skeleton" color(%color) skin(scout_tactical_1)))
(define "Pattern_SM_Scouts_2"				("Skeleton" color(%color) skin(scout_tactical_2)))
(define "Pattern_SM_Scouts_Sniper"			("Skeleton" color(%color) skin(scout_sniper)))
(define "Pattern_SM_Scouts_Sergeant"		("Skeleton" color(%color) skin(scout_sergeant)))


; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** ULTRAMARINES ***

(define "Skin_Ultramarines_Scout_1"			("Pattern_SM_Scouts_1"			color(loy_Ultramarines)))
(define "Skin_Ultramarines_Scout_2"			("Pattern_SM_Scouts_2"			color(loy_Ultramarines)))
(define "Skin_Ultramarines_Scout_Sniper"	("Pattern_SM_Scouts_Sniper"		color(loy_Ultramarines)))
(define "Skin_Ultramarines_Scout_Sergeant"	("Pattern_SM_Scouts_Sergeant"	color(loy_Ultramarines)))
