
(Define "Aux_Zzapgun"
	{bone "R_Zzapgun"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/R_Zzapgun.ply"}
	}
	{bone "L_Zzapgun"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/L_Zzapgun.ply"}
	}
	{bone "l_base"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_base.ply"}
	}
	{bone "r_base"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_base.ply"}
	}
)