
(Define "SR_Plasmacannon"
	{bone "r_plasmacannon"
		{parameters "ID=aux_turret1;"}
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			3.43486	-0.405666	0.6213
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/r_plasmacannon.ply"}
		{bone "foresight_r_plasmacannon"
			{Position 17.9187	0.734528	3.05023}
		}
		{bone "fx_r_plasmacannon"
			{Position 0.30574	0.621368	6.02293}
		}
	}	
)