	
; Just use the dummy as volume view, these are going to be loaded into human properties, not skin. 
	
(Define "Ork_Boy_Nob_Shared_Models"
	{bone "lv40k_ork%0_models"
	
		{bone "ork%0_body"						{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		
		{bone "ork%0_backpack_1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_backpack_2"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_backpack_3"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
	
		{bone "ork%0_body_D1"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_body_D2"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_body_D3"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_body_D4"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_body_D5"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_body_D6"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		
		{bone "ork%0_Armor_1"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_1_D1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_1_D2"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_1_D3"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_1_D4"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_1_D4"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			
		{bone "ork%0_Armor_2"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_2_D1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_2_D2"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_2_D3"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_2_D4"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_2_D5"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		
		{bone "ork%0_Armor_3"					{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_3_D1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_3_D2"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_3_D3"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_3_D4"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_Armor_3_D5"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			
		{Bone "G_Head"
			{bone "ork%0_head_1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_head_no_ear"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			
			{bone "ork%0_helmet_1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_2"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_3"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_4"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_5"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			
			{bone "ork%0_helmet_D1"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_D2"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_D3"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_D4"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_helmet_D5"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		}
		{bone "G_Hand1R"
			{bone "ork%0_arms_1R"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_arms_2R"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_arms_3R"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		}
		{bone "G_Hand1L"
			{bone "ork%0_arms_1L"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_arms_2L"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_arms_3L"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		}
		{bone "G_Foot1R"
			{bone "ork%0_legs_1R"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_2R"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_3R"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			
			{bone "ork%0_legs_1R_D1"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_2R_D1"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_3R_D1"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		}
		{bone "G_Foot1L"
			{bone "ork%0_legs_1L"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_2L"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_3L"				{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			
			{bone "ork%0_legs_1L_D1"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_2L_D1"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
			{bone "ork%0_legs_3L_D1"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		}
		
		; --------------------------------------------------------------------------------------------------- ; ---- // GOBBINS
		
		{bone "ork%0_weapon_loota_megablasta"	{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_weapon_loota_dakka"		{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_weapon_loota_beamy"		{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_weapon_pack_burna"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_weapon_painboy_fist"		{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
		{bone "ork%0_weapon_powerklaw"			{Extension "/[SC_Plataform]/SC_helpers/dummy_model/dummy.ext"} {visibility 0}}
	}
)