
(Define "Base_Morkanaut"
	{bone "gorkanaut_rockets"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/gorkanaut_rockets.ply"}
		
		{bone "ammo1"
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/ammo1.ply"}
		}
		{bone "ammo2"
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/ammo2.ply"}
		}
		{bone "ammo3"
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/ammo3.ply"}
		}
		{bone "ammo4"
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/ammo4.ply"}
		}
	}
	{bone "Morkanaut_body"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/Morkanaut_body.ply"}
	}
	{bone "gorkanaut_leg_right"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/gorkanaut_leg_right.ply"}
	}
	{bone "gorkanaut_leg_left"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/gorkanaut_leg_left.ply"}
	}
	{bone "Morkanaut_r_arm"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/Morkanaut_r_arm.ply"}
	}
	{bone "Morkanaut_l_arm"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/Morkanaut_l_arm.ply"}
	}
	{bone "Morkanaut_torsogun"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/gorkanaut_Chassis/Morkanaut_torsogun.ply"}
	}
)