
(Define "W_Pintle_MM"
	{bone "sec_melta_gun"
		{Matrix34
			0	0	-1
			-1	0	0
			0	1	0
			-9.85555	-35.3342	-10.561
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/landspeeder_Chassis/sec_melta_gun.ply"}
		{bone "foresight_pintle_mm"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-10.2008	-31.1492	41.8883
			}
		}
		{bone "barrel_pintle_mm00"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-10.2008	-31.1492	39.8779
			}
		}
		{bone "barrel_pintle_mm01"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-10.2008	-31.1492	43.8605
			}
		}
	}
)