
(Define "Gun_Zzap"
	{bone "w_zzapgun"
		{parameters "ID=turret;"}
		{Position -3.29491	3.88036	-0.0836572}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/warbuggy_chassis/w_zzapgun.ply"}
		{bone "foresight_zzap"
			{Position 30.5256	-1.79179	-1.06316e-05}
		}
		{bone "fx_zzap01"
			{Position 9.48339	-0.960258	-3.25953}
		}
		{bone "fx_zzap02"
			{Position 9.4834	-0.960258	3.2677}
		}
		{bone "fx_zzap03"
			{Position 26.3266	-1.72705	-2.75592}
		}
		{bone "fx_zzap04"
			{Position 26.3266	-1.72705	2.75589}
		}
	}
)