
(Include "\[SC_Plataform]\SC_helpers\inventory_item\SC_inventory_item.inc")

; =====================================================
; // ENTITY/WEAPON/DEF
; =====================================================

(Define "SC/Entity/"
	("Entity" args sm_ultramarines_t3_14)
)
; =====================================================
; // SET/STUFF/WEAPON
; =====================================================

(Define "SC/Stuff/"
	{from "sc_skin_inventory_item"	{entity "sm_ultramarines_t3_14"}}
)




