; This file contains animations and poses for vehicle crew and boarding/emiting vehicles.


;==================POSES begin==============================

	{smooth 0.5}
	{blend "steam_locomotive_driver1"			{pose "steam_locomotive_driver" begin}}
	{blend "pose_squat_mortar" 					{pose "squat_load_mortar" begin}}
	{blend "pose_pak40_gunlayer"				{pose "cannon_pak40_gunlayer" end}}
	{blend "pose_pak40_charger" 				{pose "cannon_pak40_charger" begin}}
	{blend "pose_vickers_gunlayer"				{pose "cannon_vickers_gunlayer" end}}
	{blend "stand_on_lci" 	  					{pose "stand_look_around_gun_1" begin}}
	{blend "pose_mgun_pz6" 		  				{pose "pose_mgun_tank_pz6_sherman" begin}}
	{blend "pose_mgun_sherman" 	  				{pose "pose_mgun_tank_pz6_sherman" end}}
	{blend "pose_maxson" 		  				{pose "cannon_maxson_charger" begin}}
	{blend "pose_pdr25_gunlayer"  				{pose "cannon_pdr25_gunlayer" begin}}
	{blend "pose_pdr25_charger"  				{pose "cannon_pdr25_charger" begin}}
	{blend "pose_m5_gunlayer"  					{pose "cannon_m5_gunlayer" begin}}
	{blend "pose_m5_charger"  					{pose "cannon_m5_charger" begin}}
	{blend "pose_155gpf_gunlayer"  				{pose "cannon_155gpf_gunlayer" begin}}
	{blend "pose_155gpf_charger"  				{pose "cannon_155gpf_charger" begin}}
	{blend "pose_kpvt_charger"  				{pose "cannon_kpvt_charger" begin}}
	{blend "pose_mg42_gunner"  					{pose "cannon_mg42_gunner" begin}}
	{blend "pose_mg42_charger"  				{pose "cannon_mg42_charger" begin}}
	{blend "pose_kpvt_gunlayer"  				{pose "cannon_kpvt_charger_fire" begin}}
	{blend "pose_m8_charger"  					{pose "cannon_m8_charger" begin}}
	{blend "pose_m8_gunlayer"  					{pose "cannon_m8_gunlayer" begin}}
	{blend "pose_m42_charger"  					{pose "cannon_m42_charger" begin}}
	{blend "pose_m42_gunlayer"  				{pose "cannon_m42_gunlayer" begin}}
	{blend "pose_flak38_charger_right"  		{pose "cannon_flak38_charger_right" begin}}
	{blend "pose_flak38_charger_left"  			{pose "cannon_flak38_charger_left" begin}}
	{blend "pose_flak38_gunlayer"  				{pose "cannon_flak38_gunlayer" begin}}
	{blend "pose_flak38-1_charger"  			{pose "cannon_flak38-1_charger" begin}}
	{blend "pose_flak38-1_gunlayer"  			{pose "cannon_flak38-1_gunlayer" begin}}
	{blend "pose_oerlikon_charger"  			{pose "cannon_oerlikon_charger" begin}}
	{blend "pose_nebel42_gunlayer"  			{pose "cannon_nebel42_gunlayer" begin}}
	{blend "pose_flak41_gunlayer"  				{pose "cannon_flak41_gunlayer" begin}}
	{blend "pose_flak41_gunlayer_1" 			{pose "cannon_flak41_gunlayer_fire-alert_1" end}}
	{blend "pose_k18_gunlayer_l1" 				{pose "cannon_k18_gunlayer_l1" begin}}
	{blend "pose_k18_gunlayer_l2" 				{pose "cannon_k18_gunlayer_l2" begin}}
	{blend "pose_k18_gunlayer_r1" 				{pose "cannon_k18_gunlayer_r1" begin}}
	{blend "pose_k18_gunlayer_r2" 				{pose "cannon_k18_gunlayer_r2" begin}}
	{blend "pose_vickers_gunlaeyr-l" 			{pose "cannon_vickers_gunlaeyr-l" begin}}
	{blend "pose_vickers_gunlaeyr-r" 			{pose "cannon_vickers_gunlaeyr-r" begin}}
	{blend "pose_61k_gunlayer_left" 			{pose "cannon_61k_gunlayer_left" begin}}
	{blend "pose_61k_gunlayer_right" 			{pose "cannon_61k_gunlayer_right" begin}}
	{blend "pose_mgun_stan" 					{pose "mgun_stan_charger" begin}}
	{blend "pose_mgun_stan1" 					{pose "mgun_stan_charger1" begin}}
	{blend "pose_mgun_dot"	 					{pose "mgun_stan_charger2" begin}}

	{blend "pose_seat_cannon_left" 				{pose "seat_crew_cannon" begin}}
	{blend "pose_seat_cannon_right" 			{pose "seat_crew_cannon" end}}
	{blend "pose_seat_cannon1_left" 			{pose "seat_crew_cannon1" begin}}
	{blend "pose_seat_cannon1_right" 			{pose "seat_crew_cannon1" end}}
	{blend "pose_seat_armor_1" 					{pose "seat_armor1" begin}}
	{blend "pose_seat_armor_2" 					{pose "seat_armor1" end}}
	{blend "pose_mg_stan_charger" 				{pose "mgun_stan_down" begin}}
	{blend "pose_maxim_gunlaeyr" 				{pose "cannon_maxim_pose" begin}}
	{blend "pose_maxim_driver" 					{pose "cannon_maxim_move" begin}}
	{blend "pose_thor_charger1" 				{pose "pose_thor_gunner2" begin}}
	{blend "pose_thor_charger2" 				{pose "pose_thor_gunner2" end}}
	{blend "pose_thor_gunlayer" 				{pose "board_thor_gunner1" end}}
	{blend "pose_ktiger" 				  		{pose "mgun_stan_charger_pz6b" begin}}
	{blend "pose_vicers_gunner" 		  		{pose "vicers_mgun_pose" begin}}
	{blend "pose_vicers_commander"		  		{pose "vicers_mgun_charger" end}}
	{blend "pose_lg40_gunner" 			  		{pose "cannon_lg40_gunlayer" end}}
	{blend "pose_lg40_commander"		  		{pose "cannon_lg40_charger" end}}
	{blend "pose_paratruper_flight" 			{pose "paratruper_flight" begin}}
	{blend "pose_dodge_sg1" 					{pose "pose_dodge_sg" begin}}
	{blend "pose_dodge_sg2"						{pose "pose_dodge_sg" end}}

	;// NEW
	{blend "pose_flak30_gunner"					{pose "flak30_gunner" end}}
	{blend "pose_flak30_loader"					{pose "flak30_loader" end}}
	{blend "pose_flak37_gunner"					{pose "flak37_gunner" end}}
	{blend "pose_flak37_loader"					{pose "flak37_loader" end}}
	{blend "pose_nebelwerfer41_gunner"			{pose "nebelwerfer41_gunner_aim" begin}}
	{blend "pose_nebelwerfer41_loader"			{pose "cannon_pak40_charger" begin}}
	{blend "pose_mgun_251"						{pose "pose_mgun_251" begin}}

	{blend "pose_pz3_left"						{pose "pose_pz3f_left" end}}
	{blend "pose_pz3_mid1"						{pose "pose_pz3f_mid1" end}}
	{blend "pose_pz3_mid2"						{pose "pose_pz3f_mid2" end}}
	{blend "pose_pz3_right"						{pose "pose_pz3f_right" end}}

	{blend "pose_maxim_gunner"					{pose "pose_maxim_gunner" end}}
	{blend "pose_maxim_commander"				{pose "pose_maxim_commander" end}}
	{blend "pose_maxim_gunner_stand"			{pose "maxim_gunner_stand_fire" end}}
	{blend "pose_maxim_commander_stand"			{pose "maxim_commander_stand_fire" end}}
	
	
	{blend "pose_t26_driver" 					{pose "board_t26_driver" end}}
	
	{blend "pose_new_cannon_gunner_fire"  		{pose "new_cannon_gunner_fire" begin}}
	{blend "pose_new_cannon_commander_fire"  	{pose "new_cannon_commander_fire" begin}}
	{blend "pose_new_cannon_charger_fire"  		{pose "new_cannon_charger_fire" begin}}
	{blend "pose_new_cannon_charger2_fire"  	{pose "new_cannon_charger2_fire" begin}}

;==================POSES end==============================

;================== BOARDING ANIMATIONS begin=========================
	{smooth 0}
	{sequence "board_m26"}
	{sequence "board_thor_gunner1"}
	{sequence "board_thor_driver"}
	{sequence "board_bigcar" {speed 0.5}}
	{sequence "board_tank" {speed 0.5}}
	{sequence "board_plane_right"}
	{sequence "board_plane_left"}
	{sequence "board_rubber_boat"}
	{sequence "board_torpedo_boat"}
	{sequence "board_steam_locomotive"}
	{sequence "board_ju-52"}
	{sequence "board_big-midcar_driver"}
	{sequence "board_big-midcar"}
	{sequence "board_big-highcar_driver"}
	{sequence "board_big-highcar"}
	{sequence "board_willis"}
	{sequence "board_willis_driver"}
	{sequence "board_willysat_driver"}
	{sequence "board_gaz-m"}
	{sequence "board_gaz-m_driver"}
	{sequence "board_pz4_driver"}
	{sequence "board_jtiger_driver"}
	{sequence "board_hummel_driver"}
	{sequence "board_kv2_driver" {speed 0.5}}
	{sequence "board_hummel"{dynamicSpeed {134 147 1.2}}}
	{sequence "board_t34_driver"}
	{sequence "board_pz-6"}
	{sequence "board_t-34"}
	{sequence "board_sherman_left"}
	{sequence "board_sherman_right"}
	{sequence "board_cromwell"}
	{sequence "board_kv"}
	{sequence "board_sdkfz7"}
	{sequence "board_sdkfz251-1"}
	{sequence "board_body"}
	{sequence "board_kv-85"}
	{sequence "board_is-2"}
	{sequence "board_su76"}
	{sequence "board_tank_right"}
	{sequence "board_tank_left"}
	{sequence "board_horch_passanger_left"}
	{sequence "board_ba-20m_driver"}
	{sequence "board_ba-20m"}
	{sequence "board_sd222_driver"}
	{sequence "board_sd222_gunner_1"}
	{sequence "board_sd222_gunner_2"}
	{sequence "board_daimler_gunner"}
	{sequence "board_sd232_driver"}
	{sequence "board_lowtank_left"}
	{sequence "board_lowarmor"}
	{sequence "board_lowtank_stand"}
	{sequence "board_lowtank_stand_1"}
	{sequence "board_higharmor"}
	{sequence "board_dodge"}
	{sequence "board_dodge_body"}
	{sequence "board_dodge_bodyback"}
	{sequence "board_middlearmor"}	
	{sequence "board_hetzer"}
	{sequence "board_isu-152"}
	
	;// NEW
	{sequence "board_kubel_driver"}
	{sequence "board_kubel_commander"}
	{sequence "board_kubel_leftpassenger"}
	{sequence "board_kubel_rightpassenger"}

	{sequence "board_opel_driver" {speed 0.5}} 
	
	{sequence "board_sdkfz10_driver" {speed 0.3}}
	{sequence "board_sdkfz10_all" {speed 0.3}}
	{sequence "board_t26_driver" {speed 0.25}}
	
	
	{sequence "halftrack_commander_board"}
	{sequence "halftrack_commander_board_seat"}
	{sequence "halftrack_driver_board"}
	{sequence "halftrack_driver_board_seat"}
	{sequence "halftrack_gunner_board"}
	{sequence "halftrack_gunner_board_seat"}
	{sequence "halftrack_pass_l_01_board"}
	{sequence "halftrack_pass_l_01_board_seat"}
	{sequence "halftrack_pass_l_02_board"}
	{sequence "halftrack_pass_l_02_board_seat"}
	{sequence "halftrack_pass_l_03_board"}
	{sequence "halftrack_pass_l_03_board_seat"}
	{sequence "halftrack_pass_l_04_board"}
	{sequence "halftrack_pass_l_04_board_seat"}
	{sequence "halftrack_pass_r_01_board"}
	{sequence "halftrack_pass_r_01_board_seat"}
	{sequence "halftrack_pass_r_02_board"}
	{sequence "halftrack_pass_r_02_board_seat"}
	{sequence "halftrack_pass_r_03_board"}
	{sequence "halftrack_pass_r_03_board_seat"}
	{sequence "halftrack_pass_r_04_board"}
	{sequence "halftrack_pass_r_04_board_seat"}

;================== BOARDING ANIMATIONS end=========================


;================== MORTAR ANIMATIONS begin=========================

	{sequence "mortar_gunner_aim" {resume}}
	{sequence "mortar_gunner_fire" {speed 0.6}}
	{sequence "mortar_gunner_reload" {speed 0.5}}

	{sequence "mortar_commander_aim" {resume}}
	{sequence "mortar_commander_fire" {speed 0.6}}
	{sequence "mortar_commander_reload" {speed 0.5}}

	{blend "pose_mortar_commander" 					{pose "mortar_commander_aim" begin}}
	{blend "pose_mortar_gunner" 					{pose "mortar_gunner_reload" begin}}
	
	
	
	{sequence "mortar_120sgrw42_gunner_aim" {resume} {speed 0.6}}
	{sequence "mortar_120sgrw42_gunner_fire" {speed 0.6}}
	{sequence "mortar_120sgrw42_gunner_reload" {speed 0.5}}

	{sequence "mortar_120sgrw42_commander_aim" {resume} {speed 0.6}}
	{sequence "mortar_120sgrw42_commander_fire" {speed 0.6}}
	{sequence "mortar_120sgrw42_commander_reload" {speed 0.5}}

	{blend "pose_mortar_120sgrw42_commander" 					{pose "mortar_120sgrw42_commander_fire" begin}}
	{blend "pose_mortar_120sgrw42_gunner" 					{pose "mortar_120sgrw42_gunner_fire" begin}}

;================== MORTAR ANIMATIONS end=========================

;================== MG ANIMATIONS begin=========================


	{sequence "mg_lafette_gunner_aim" {resume}}
	{sequence "mg_lafette_gunner_fire" {speed 1}}
	{sequence "mg_lafette_gunner_reload" {speed 0.5}}

	{sequence "mg_lafette_commander_aim" {resume}}
	{sequence "mg_lafette_commander_fire" {speed 1}}
	{sequence "mg_lafette_commander_reload" {speed 0.5}}

	{blend "pose_mg_lafette_commander" 					{pose "mg_lafette_commander_fire" begin}}
	{blend "pose_mg_lafette_gunner" 					{pose "mg_lafette_gunner_fire" begin}}



;================== MG ANIMATIONS end=========================


;================== FLAK CANNON ANIMATIONS begin=========================

	{sequence "flak_gunner_aim" {resume} {speed 1}}
	{sequence "flak_gunner_fire" {speed 1}}
	{sequence "flak_gunner_reload" {speed 1}}

	{sequence "flak_gunner2_aim" {resume}}
	{sequence "flak_gunner2_fire" {speed 1}}
	{sequence "flak_gunner2_reload" {speed 1}}

	{sequence "flak_charger_aim" {resume}}
	{sequence "flak_charger_fire" {speed 1}}
	{sequence "flak_charger_reload" {speed 1}}

	{sequence "flak_charger2_aim" {resume}}
	{sequence "flak_charger2_fire" {speed 1}}
	{sequence "flak_charger2_reload" {speed 1}}

	{sequence "flak_commander_aim" {resume}}
	{sequence "flak_commander_fire" {speed 1}}
	{sequence "flak_commander_reload" {speed 1}}

	{blend "pose_flak_commander" 					{pose "flak_commander_fire" begin}}
	{blend "pose_flak_gunner" 						{pose "flak_gunner_aim" begin}}
	{blend "pose_flak_gunner2" 						{pose "flak_gunner2_aim" begin}}
	{blend "pose_flak_charger" 						{pose "flak_charger_fire" begin}}
	{blend "pose_flak_charger2" 					{pose "flak_charger2_fire" begin}}
	
	
	
	
	;-------------72k AA Gun-------------------
	
	
	
	{sequence "AAgun_72k_charger_aim" {resume} {speed 0.7}}
	{sequence "AAgun_72k_charger_fire" {speed 1}}
	{sequence "AAgun_72k_charger_reload" {speed 0.5}}

	{sequence "AAgun_72k_commander_aim" {resume} {speed 0.7}}
	{sequence "AAgun_72k_commander_fire" {speed 1}}
	{sequence "AAgun_72k_commander_reload" {speed 0.5}}

	{sequence "AAgun_72k_gunner_aim" {resume} {speed 0.7}}
	{sequence "AAgun_72k_gunner_fire" {speed 1}}
	{sequence "AAgun_72k_gunner_reload" {speed 0.5}}

	{blend "AAgun_72k_charger" 					{pose "AAgun_72k_charger_fire" begin}}
	{blend "AAgun_72k_commander" 				{pose "AAgun_72k_commander_fire" begin}}
	{blend "AAgun_72k_gunner" 					{pose "AAgun_72k_gunner_fire" begin}}
	
	
	
	
	;-------------3.7cm FlaK 37-------------------
	
	
	
	{sequence "AAgun_flak37_charger_aim" {resume} {speed 0.7} {smooth 0.7}}
	{sequence "AAgun_flak37_charger_fire" {speed 1} {smooth 0.7}}
	{sequence "AAgun_flak37_charger_reload" {speed 0.5} {smooth 0.7}}

	{sequence "AAgun_flak37_commander_aim" {resume} {speed 0.7} {smooth 0.7}}
	{sequence "AAgun_flak37_commander_fire" {speed 1} {smooth 0.7}}
	{sequence "AAgun_flak37_commander_reload" {speed 0.5} {smooth 0.7}}

	{sequence "AAgun_flak37_gunner_aim" {resume} {speed 0.7} {smooth 0.7}}
	{sequence "AAgun_flak37_gunner_fire" {speed 1} {smooth 0.7}}
	{sequence "AAgun_flak37_gunner_reload" {speed 0.5} {smooth 0.7}}

	{blend "AAgun_flak37_charger" 					{pose "AAgun_flak37_charger_fire" begin}}
	{blend "AAgun_flak37_commander" 				{pose "AAgun_flak37_commander_fire" begin}}
	{blend "AAgun_flak37_gunner" 					{pose "AAgun_flak37_gunner_fire" begin}}

	

;================== FLAK CANNON ANIMATIONS end=========================


;================== EMIT ANIMATIONS begin=========================
	
	{sequence "emit_tank_1"}
	{sequence "emit_tank_1_hold"}
	{sequence "emit_tank_2_hold"}
	{sequence "emit_tank_2"}
	{sequence "emit_torpedo_boat"}
	{sequence "emit_body" {movement}}
	{sequence "emit_cg-4a"}	
	{sequence "emit_bk1124" {file "getover_middle.anm"}}
	{sequence "emit_lcvp" {file "getover_middle_1.anm"} {movement}}
	{sequence "emit_sd222_driver"}
	{sequence "emit_t34_hold"}
	{sequence "emit_seat_nkl_passenger"}
	
;================== BOARDING ANIMATIONS end=========================
	
;================== SEATS begin=========================
	{smooth 0.2}
	{sequence "seat_armor"}
	{sequence "seat_armor1"}
	{sequence "seat_crew_cannon"}
	{sequence "seat_crew_cannon1"}
	{sequence "seat_driver_car"}
	{sequence "seat_driver_moto"}
	{sequence "seat_gunner_moto"}
	{sequence "seat_gunner_stand"}
	
	;// NEW
	{sequence "seat_bm13_gunner"}
	{sequence "seat_commander_hatch"}
	{sequence "seat_kubel_commander"}
	{sequence "seat_kubel_driver"}
	{sequence "seat_kubel_gunner1"}
	{sequence "seat_kubel_gunner2"}
	{sequence "seat_kubel_passenger1"}
	{sequence "seat_kubel_passenger2"}
	{sequence "seat_opel_driver"}
	{sequence "seat_opel_commander"}
	{sequence "seat_nkl_driver"}
	{sequence "seat_nkl_gunner"}
	{sequence "seat_nkl_passenger1"}
	{sequence "seat_nkl_passenger2"}
	{sequence "seat_nkl_passenger3"}
	{sequence "seat_nkl_passenger4"}
	{sequence "seat_sdkfz10_driver"}
	{sequence "seat_sdkfz10_commander"}
	{sequence "seat_sdkfz10_passl1"}
	{sequence "seat_sdkfz10_passl2"}
	{sequence "seat_sdkfz10_passr1"}
	{sequence "seat_sdkfz10_passr2"}
	{sequence "seat_ammo_tr_1"}
	{sequence "seat_ammo_tr_2"}
	{sequence "pose_flak30_seatr"}
	{sequence "seat_kettenkrad_driver"}	
	
	{sequence "seat_passenger"}
	{sequence "seat_willis_driver"}
	{sequence "seat_willis_passenger"}
	{sequence "seat_willysat_driver"}
	{sequence "pose_mgun_tank_pz6_sherman"}
	{sequence "seat_sd222_gunner_1"}
	{sequence "seat_sd222_gunner_2"}
	{sequence "seat_sd223_gunner"}
	{sequence "seat_tankturret_gunner_1"} 
	{sequence "seat_tankturret_gunner_2"} 
	{sequence "seat_m7_mgunner"}
	{sequence "seat_m7_gunner"}
	{sequence "seat_m7_com"}
	{sequence "seat_wc55_mgunner"}
	{sequence "seat_wc55_com"}
	{sequence "seat_sd251_mgunner"}
	{sequence "seat_willysat_basooker"}
	{blend 	  "seat_torpedo" {pose "lie_holdback_gun" end}}			
	
;================== SEATS end=========================

;================== CANNON CREW begin=========================
	{sequence "cannon_pak40_charger"  {speed 0.9}  {smooth 0.1}}
	{sequence "cannon_pak40_gunlayer" {speed 0.95} {resume} {smooth 0.03}}
	{sequence "cannon_pak40_pusher_right" {speed 1.2}  {resume}}
	{sequence "cannon_pak40_pusher_left"  {speed 1.2}  {resume}}
	{sequence "squat_load_mortar"     {speed 0.8}}
	{sequence "squat_load_mortar_begin"     {speed 0.8}}
	{sequence "squat_load_mortar_end"     {speed 0.8}}

	{smooth 0.025}
	{sequence "mgun_stan_charger"        {speed 0.7}}
	{sequence "mgun_stan_charger1"       {speed 0.7}}
	{sequence "mgun_stan_charger2"       {speed 0.7}}
	{sequence "cannon_zis3_charger_test"    {speed 0.9}}
	{sequence "cannon_pdr25_gunlayer_fire-alert"  {speed 0.7}}
	{sequence "cannon_zis3_gunlayer"        {speed 0.9} {resume}}
	{sequence "cannon_zis3_charger_fire"    {speed 1.5}}
	{sequence "cannon_zis3_charger"         {speed 1.1} {smooth 0.1}}
	{sequence "cannon_gunlayer_fire-alert"  {speed 0.9}  {smooth 0.05}}
	{sequence "cannon_pdr25_gunlayer"       {speed 0.9} {resume}}
	{sequence "cannon_pdr25_charger"        {speed 1}} 
	{sequence "cannon_pdr25_charger_fire"   {speed 1.1} {dynamicSpeed {0 7 2}}}
	{sequence "cannon_m5_gunlayer"          {speed 0.9} {resume}}
	{sequence "cannon_m5_charger"           {speed 0.9}}
	{sequence "cannon_155gpf_gunlayer"      {speed 0.9} {resume}}
	{sequence "cannon_155gpf_charger"       {speed 0.9}}
	{sequence "cannon_flak41_gunlayer"      {speed 0.9} {resume}}
	{sequence "cannon_flak41_gunlayer_fire-alert"   {speed 0.7}}
	{sequence "cannon_flak41_gunlayer_fire-alert_1"  {speed 0.7}}
	{sequence "cannon_kpvt_charger"         {speed 0.9}}
	{sequence "cannon_kpvt_charger_fire"    {speed 1.4}}
	{sequence "cannon_m8_gunlayer"          {speed 0.9} {resume}}
	{sequence "cannon_m8_charger"           {speed 1.1}}
	{sequence "cannon_m8_charger_fire"      {speed 0.9}}
	{sequence "cannon_m42_gunlayer"          {speed 0.9} {resume}}
	{sequence "cannon_m42_charger"           {speed 1.1}}
	{sequence "cannon_m42_charger_fire"      {speed 1.3}}
	{sequence "cannon_flak38_gunlayer"      {speed 0.9} {resume}}
	{sequence "cannon_flak38_charger_right" {speed 0.9} {dynamicSpeed {1 2 0.05} {2 30 0.8}} }
	{sequence "cannon_flak38_charger_left"  {speed 0.9} {dynamicSpeed {1 2 0.05} {2 30 2}} }
	{sequence "cannon_flak38_gunlayer_fire" {speed 0.9}}
	{sequence "cannon_flak38_rcharger_fire-alert"  {speed 0.9}}
	{sequence "cannon_flak38-1_charger"  {speed 0.9}{dynamicSpeed {1 2 0.05}} }
	{sequence "cannon_flak38_lcharger_fire-alert"  {speed 0.9}}
	{sequence "cannon_flak38-1_gunlayer"  {speed 0.9} {resume}}
	{sequence "cannon_flak38-1_gunlayer_fire"  {speed 0.9}}
	{sequence "cannon_maxson_charger"  {speed 0.9}}
	{sequence "cannon_nebel42_gunlayer"  {speed 0.9} {resume}}
	{sequence "cannon_k18_gunlayer_l1"  {speed 0.9} {resume}}
	{sequence "cannon_k18_gunlayer_l2"  {speed 0.9} {resume}}
	{sequence "cannon_k18_gunlayer_r1"  {speed 0.9} {resume}}
	{sequence "cannon_k18_gunlayer_r2"  {speed 0.9} {resume}}
	{sequence "cannon_vickers_gunlaeyr-l"  				{speed 0.9} {resume}}
	{sequence "cannon_vickers_gunlaeyr-l_fire-alert"  	{speed 0.9}}
	{sequence "cannon_vickers_gunlaeyr-r"  				{speed 0.9} {resume}}
	{sequence "cannon_vickers_gunlaeyr-r_fire-alert"  	{speed 0.9}}
	{sequence "cannon_oerlikon_charger"  {speed 0.9}}
	{sequence "turret_charger"              {speed 0.9}}
	{sequence "cannon_vickers_gunlayer"     {speed 0.95}}
	{sequence "mgun_stan_down"     			{speed 0.5}{resume}}
	{sequence "cannon_maxim_pose"     		{speed 0.5}}
	{sequence "cannon_maxim_move" 			{speed 0.5}{resume}}
	{sequence "maxim_commander_stand_fire" 	{speed 0.5}}
	{sequence "maxim_commander_stand_reload" {speed 0.3}}
	{sequence "maxim_gunner_stand_fire" 	{speed 0.5}}
	{sequence "maxim_gunner_stand_reload" 	{speed 0.3}}
	{sequence "cannon_61k_gunlayer_left" {resume}}
	{sequence "cannon_61k_gunlayer_right"{resume}}
	{sequence "mgun_browning_driver_l" 		{speed 0.9}{resume}}
	{sequence "mgun_browning_driver_r" 		{speed 0.9}{resume}}
	{sequence "mortar_driver_r" 		{file "mortar_commander_move.anm"} {speed 0.36}{resume}}
	{sequence "mortar_driver_l" 		{file "mortar_gunner_move.anm"} {speed 0.36}{resume}}
	{sequence "steam_locomotive_driver" 		{speed 0.9}}
	{sequence "pose_thor_gunner2" 		{speed 0.9}}
	{sequence "mgun_stan_charger_pz6b"}
	{sequence "vicers_mgun_pose"}
	{sequence "cannon_lg40_charger"}
	{sequence "cannon_lg40_charger_fire-alert_1"}
	{sequence "cannon_lg40_driver1"				{speed 0.85}{resume}}
	{sequence "cannon_lg40_driver2"				{speed 1}{resume}}
	{sequence "cannon_lg40_gunlayer"				{resume}}
	{sequence "cannon_lg40_gunlayer_fire-alert_1"}
	{sequence "vicers_mgun_charger"}
	{sequence "pose_dodge_sg"				{speed 0.7}}
	{sequence "board_dodge_sg"				{speed 1}}
	{sequence "dodge_sg_reload_bazooka"		{speed 1}}
	{sequence "dodge_sg_reload_mgun"		{speed 1}}
	
	;// NEW
	{sequence "flak30_aim"		{speed 0.5}}
	{sequence "flak30_gunner"	{speed 0.5} {resume}}
	{sequence "flak30_loader"	{speed 0.4}}
	{sequence "flak37_gunner"	{speed 0.5} {resume}}
	{sequence "flak37_loader"	{speed 0.5} {resume}}
	{sequence "nebelwerfer41_gunner_aim"	{speed 0.7} {resume}}
	{sequence "nebelwerfer41_gunner_fire"	{speed 0.5} {resume}}
	
	{sequence "new_cannon_gunner_fire"		{speed 0.7}}
	{sequence "new_cannon_charger_fire"		{speed 0.7}}
	{sequence "new_cannon_charger2_fire"	{speed 0.7}}
	{sequence "new_cannon_commander_fire"	{speed 0.7}}
	
	{sequence "new_cannon_gunner_reload"	{speed 0.8}}
	{sequence "new_cannon_charger_reload"	{speed 0.8}}
	{sequence "new_cannon_charger2_reload"	{speed 0.8}}
	{sequence "new_cannon_commander_reload"	{speed 0.8}}
	
;================== CANNON CREW end=========================

;================== Other begin=========================

	{sequence "paratruper_flight"			{speed 0.5}}
	{sequence "paratruper_landing"			{speed 0.8}}
	{sequence "flag_lift"					{speed 0.7}}
	
;================== Other end=========================