
(Define "SL_HB"
	{bone "l_hb"
		{parameters "ID=aux_turret2;"}
		{Matrix34
			0	0	-1
			-1	0	0
			0	1	0
			11.4802	-1.18942	0.425568
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dorn_chassis/l_hb.ply"}
		{bone "foresight_L_heavybolter"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				0.497002	-13.4835	0.340656
			}
		}
		{bone "fx_L_heavybolter"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				0.497002	-9.18007	4.8579
			}
		}
	}
)