
{Volume "trackleft"
	{Polyhedron "trackleft.vol"}
	{Bone "trackl"}
	{Position 3.01628	-42.5334	0}
}
{Volume "trackright"
	{Polyhedron "trackright.vol"}
	{Bone "trackr"}
	{Position 3.01628	-42.5334	0}
}
{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Position 48.8429	-12.2869	10.2435}
}
{Volume "body2"
	{Polyhedron "body2.vol"}
	{Bone "body_tracks"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		-42.5334	-3.01624	0
	}
}
{Volume "body3"
	{Polyhedron "body3.vol"}
	{Bone "body_tracks"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		42.5394	-3.01625	0
	}
}
{Volume "body4"
	{Box 78.7402 64.9606 21.6535}
	{Bone "body"}
	{Position -24.8603	0	21.0703}
}
{Volume "body5"
	{Polyhedron "body5.vol"}
	{Bone "body"}
	{Position 46.0623	17.5708	10.2435}
}
{Volume "turret1"
	{Cylinder 27.5591 17.7165}
	{Bone "turret"}
	{Position 0	0	-2.80219}
}
{Volume "turret2"
	{Box 19.685 48.2283 44.2913}
	{Bone "turret"}
	{Matrix34
		0.969275	0	0.24598
		0	1	0
		-0.24598	0	0.969275
		25.5309	0.00785384	33.9896
	}
}
