
; Presets for health and stamina levels

(include "/set/breed/presets/perks/vision.inc")


;/*=========== Standard Presets Begin ===========*/

(define "health_rank_1"		;// concripts or replacement soldiers
	{"health" "225%"}
	{"health_regeneration" "5%"}
	{"stamina" "75%"}
	{"stamina_regeneration" "75%"}
	{"personage" 0}
	("standard_vision")
)

(define "health_rank_2"		;// standard soldier, most infantry use this level
	{"health" "250%"}
	{"health_regeneration" "5%"}
	{"stamina" "125%"}
	{"stamina_regeneration" "100%"}
	{"personage" 0}
	("standard_vision")
)

(define "health_rank_2.5"		;// standard soldier, most infantry use this level
	{"health" "325%"}
	{"health_regeneration" "5%"}
	{"stamina" "150%"}
	{"stamina_regeneration" "100%"}
	{"personage" 0}
	("standard_vision")
)

(define "health_rank_3"		;// elite soldier with better training
	{"health" "275%"}
	{"health_regeneration" "15%"}
	{"stamina" "200%"}
	{"stamina_regeneration" "150%"}
	{"personage" 0}
	("standard_vision")
)

(define "health_rank_4"		;// super elite units
	{"health" "300%"}
	{"health_regeneration" "20%"}
	{"stamina" "250%"}
	{"stamina_regeneration" "200%"}
	{"personage" 0}
	("elite_vision")
)

(define "health_rank_5"		;// super elite units
	{"health" "325%"}
	{"health_regeneration" "25%"}
	{"stamina" "300%"}
	{"stamina_regeneration" "250%"}
	{"personage" 0}
	("elite_vision")
)



;/*=========== Standard Presets End ===========*/