
{sc_trooper_attack_mode
	{position 2 0}	{condition "SC_plataform_prop_misc_melee single disabled"}
}

{sc_callin_activate
	{position 2 0}	{condition "SC_Plataform_prop_mp_callin single disabled"}
}

; ========================================================================= ; 

; // SPACE MARINES
{lv40k_human_special_ability_sm_apothecary_heal
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_sm_chaplain_zeal
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_sm_commander_warcry
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_sm_librarian_mindwar
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

;{lv40k_human_special_ability_sm_techmarine_machinespirits
;	{position 3 0}	{condition "SC_prop_infantry_generic single"}
;}

{lv40k_human_special_ability_sm_terminator_tp
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

;{lv40k_vehicle_special_ability_sm_venerable_dreadnought_aura
;	{position 3 0}	{condition "SM_dreadnought_venerable single"}
;}

{lv40k_vehicle_special_ability_sm_knight_warhorn
	{position 3 0}	{condition "IG_knight single"}
}

{lv40k_vehicle_special_ability_sm_landraider_spirit
	{position 3 0}	{condition "SM_landraider single"}
}



; // ORKZ
{lv40k_human_special_ability_ork_waaagh
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_ork_painboy_da_juice
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_ork_warp_shield
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_ork_warboss
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}


; // TYRANIDS
{lv40k_human_special_ability_tyr_synapse
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_lictor_cloak
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_hiveguard_heal
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_swarmlord
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_hivetyrant
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_venomthrope
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_oldoneeye
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_tervigon
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}

{lv40k_human_special_ability_tyr_prime_warrior
	{position 3 0}	{condition "SC_prop_infantry_generic single"}
}






























