
; ##################################################################################
; ########################## SC DLC MOD: LV40k VOICELINES ##########################
; ##################################################################################

; ============ FACTION BASED TALKS

; // ALERT ENEMY SPECIFIC WEAPON
{talk "alert_wpn_ork_explosive" 				("human_phrases" args alert_wpn_ork_explosive)}
{talk "alert_wpn_ork_mgun" 						("human_phrases" args alert_wpn_ork_mgun)}

{talk "alert_wpn_sm_loyalist_explosive" 		("human_phrases" args alert_wpn_sm_loyalist_explosive)}
{talk "alert_wpn_sm_loyalist_mgun" 				("human_phrases" args alert_wpn_sm_loyalist_mgun)}

; // ALERT ENEMY SPECIFIC FOE
{talk "alert_enemy_igc" 						("human_phrases" args alert_enemy_igc)}
{talk "alert_enemy_orks" 						("human_phrases" args alert_enemy_orks)}
{talk "alert_enemy_xenos" 						("human_phrases" args alert_enemy_xenos)}			; // <- HUMANS ONLY, BOTH CHAOS AND LOYALIST
{talk "alert_enemy_humans" 						("human_phrases" args alert_enemy_humans)}			; // <- ANY XENOS
{talk "alert_enemy_sm_chaos" 					("human_phrases" args alert_enemy_sm_chaos)}
{talk "alert_enemy_sm_loyalist" 				("human_phrases" args alert_enemy_sm_loyalist)}
{talk "alert_enemy_tyr" 						("human_phrases" args alert_enemy_tyr)}

; // KILLED AN SPECIFIC FOE
{talk "enemy_is_destroyed_igc"					("human_phrases" args enemy_is_destroyed_igc)}
{talk "enemy_is_destroyed_orks"					("human_phrases" args enemy_is_destroyed_orks)}
{talk "enemy_is_destroyed_xenos"				("human_phrases" args enemy_is_destroyed_xenos)}	; // <- HUMANS ONLY, BOTH CHAOS AND LOYALIST
{talk "enemy_is_destroyed_humans" 				("human_phrases" args enemy_is_destroyed_humans)}	; // <- ANY XENOS
{talk "enemy_is_destroyed_sm_chaos"				("human_phrases" args enemy_is_destroyed_sm_chaos)}
{talk "enemy_is_destroyed_sm_loyalist"			("human_phrases" args enemy_is_destroyed_sm_loyalist)}
{talk "enemy_is_destroyed_tyr" 					("human_phrases" args enemy_is_destroyed_tyr)}

; ============ AURA TALKS

{talk "group_aura_hail_loyalist_astartes"		("human_phrases" args group_aura_hail_loyalist_astartes)}
{talk "group_aura_leader_astartes_raly_guard"	("human_phrases" args group_aura_leader_astartes_raly_guard)}
