
; #############################################################################################
; ########################## SC DLC MOD: LV40k NATIONALITIES PHRASES ##########################
; #############################################################################################

(Define "SC_DLC_LV40k_Phrases_cannon"	
)

(Define "SC_DLC_LV40k_Phrases_tank"	
	("phrase_voice" args %0 lv40k_ork_boy 1 %1)				("phrase_voice_DLC_talks" args %0 lv40k_ork_boy 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_ork_grot 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_ork_grot 1 %1 DLC_40k)
	
	("phrase_voice" args %0 lv40k_guardsmen 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_guardsmen 1 %1 DLC_40k)
	
	("phrase_voice" args %0 lv40k_marine_tac 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_marine_tac 1 %1 DLC_40k)
)

(Define "SC_DLC_LV40k_Phrases_human"	

	; // CHAOS MARINES
	("phrase_voice" args %0 lv40k_csm_tac 1 %1)

	; // LOYALIST MARINES
	("phrase_voice" args %0 lv40k_marine_scout 1 %1)		("phrase_voice_DLC_talks" args %0 lv40k_marine_scout 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_marine_scout_mask 1 %1)	("phrase_voice_DLC_talks" args %0 lv40k_marine_scout_mask 1 %1 DLC_40k)
	
	("phrase_voice" args %0 lv40k_marine_chaplain 1 %1)		
	("phrase_voice" args %0 lv40k_marine_tac 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_marine_tac 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_marine_commander 1 %1)	("phrase_voice_DLC_talks" args %0 lv40k_marine_commander 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_marine_librarian 1 %1)	("phrase_voice_DLC_talks" args %0 lv40k_marine_librarian 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_marine_tech 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_marine_tech 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_marine_apothecary 1 %1)	("phrase_voice_DLC_talks" args %0 lv40k_marine_apothecary 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_marine_sternguard 1 %1)	("phrase_voice_DLC_talks" args %0 lv40k_marine_sternguard 1 %1 DLC_40k)

	; // ORKS
	("phrase_voice" args %0 lv40k_ork_boy 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_ork_boy 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_ork_boy 3 %1)			("phrase_voice_DLC_talks" args %0 lv40k_ork_boy 3 %1 DLC_40k)
	
	("phrase_voice" args %0 lv40k_ork_grot 1 %1)		("phrase_voice_DLC_talks" args %0 lv40k_ork_grot 1 %1 DLC_40k)
	
	("phrase_voice" args %0 lv40k_ork_weirdboy 1 %1)	("phrase_voice_DLC_talks" args %0 lv40k_ork_weirdboy 3 %1 DLC_40k)

	("phrase_voice" args %0 lv40k_ork_nob 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_ork_nob 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_ork_nob 2 %1)			("phrase_voice_DLC_talks" args %0 lv40k_ork_nob 2 %1 DLC_40k)
	
	("phrase_voice" args %0 lv40k_ork_nob_gitz 1 %1)		
	
	("phrase_voice" args %0 lv40k_ork_dok 1 %1)
	
	("phrase_voice" args %0 lv40k_ork_mekboy 1 %1)
	
	; // TYRANIDS
	("phrase_voice" args %0 lv40k_tyr_small 1 %1)
	("phrase_voice" args %0 lv40k_tyr_med 1 %1)
	("phrase_voice" args %0 lv40k_tyr_big 1 %1)
	
	; // IMPERIAL GUARD
	("phrase_voice" args %0 lv40k_guardswoman 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_guardswoman 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_guardsmen 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_guardsmen 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_commissar 1 %1)			("phrase_voice_DLC_talks" args %0 lv40k_commissar 1 %1 DLC_40k)
	("phrase_voice" args %0 lv40k_guardsmen_ultra 1 %1)		("phrase_voice_DLC_talks" args %0 lv40k_guardsmen_ultra 1 %1 DLC_40k)
	
	; // ADMECH
	("phrase_voice" args %0 lv40k_servitor 1 %1)
	
	; // CHAOS CULTISTS
	("phrase_voice" args %0 lv40k_heretic 1 %1)
)