
(Include "\[SC_Plataform]\SC_helpers\inventory_item\SC_inventory_item.inc")

; =====================================================
; // ENTITY/WEAPON/DEF
; =====================================================

(Define "SC/Entity/"
	("Entity" args ig_ultramar_t0_07)
)
; =====================================================
; // SET/STUFF/WEAPON
; =====================================================

(Define "SC/Stuff/"
	{from "sc_skin_inventory_item"	{entity "ig_ultramar_t0_07"}}
)




