
(Define "SL_Melta"
	{bone "l_melta"
		{parameters "ID=aux_turret3;"}
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			-16.5916	-49.3827	64.081
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/l_melta.ply"}
		{bone "barrel_l_melta01"
			{Position 42.1773	64.081	47.5294}
		}
		{bone "fx_l_melta"
			{Position 33.4745	64.0102	54.9725}
		}
		{bone "barrel_l_melta00"
			{Position 42.1773	64.081	51.6292}
		}
		{bone "foresight_l_melta"
			{Position 42.1773	64.081	49.6413}
		}
	}
)