
(Define "Base_Default"
	{bone "toes"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/toes.ply"}
	}
	{bone "Chest_torsoA"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/details3_torso.ply"}	{Visibility 0}
	}
	{bone "Chest_torsoB"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/details2_torso.ply"}	{Visibility 0}
	}
	{bone "Chest_torsoC"
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dreadnought_Chassis/SM/details1_torso.ply"}	{Visibility 0}
	}
)