
; // SORT IN INTERACTION ENTITY

(Define "Dread_Weapons_R_Autocannon"
	{bone "weaponry_r"	{bone "RW"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_autocannon.ply"}}}
)
(Define "Dread_Weapons_R_Hurricane"
	{bone "weaponry_r"	{bone "RW"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_hurricane_bolters.ply"}}}
)
(Define "Dread_Weapons_R_Plasmacannon"
	{bone "weaponry_r"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_arm_weapon_base.ply"} 
		{bone "RW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_plasmacannon.ply"}}
	}
)
(Define "Dread_Weapons_R_Multimelta"
	{bone "weaponry_r"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_arm_weapon_base.ply"} 
		{bone "RW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_multimelta.ply"}}
	}
)
(Define "Dread_Weapons_R_Lascannon"
	{bone "weaponry_r"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_arm_weapon_base.ply"} 
		{bone "RW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_lascannon.ply"}}
	}
)
(Define "Dread_Weapons_R_Inferno"
	{bone "weaponry_r"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_arm_weapon_base.ply"} 
		{bone "RW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_inferno.ply"}}
	}
)
(Define "Dread_Weapons_R_Heavybolter"
	{bone "weaponry_r"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_arm_weapon_base.ply"} 
		{bone "RW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_twin_hb.ply"}}
	}
)
(Define "Dread_Weapons_R_Assaultcannon"
	{bone "weaponry_r"	{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_arm_weapon_base.ply"} 
		{bone "RW"		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/Dreadnought_Chassis/SM/r_assaultcannon.ply"}}
	}
)

