
(Define "Aux_Autocannon"
	{bone "R_Autocannon"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/R_Autocannon.ply"}
	}
	{bone "L_Autocannon"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/L_Autocannon.ply"}
	}
	{bone "l_base"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_base.ply"}
	}
	{bone "r_base"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_base.ply"}
	}
)