
{Volume "body"
	{Polyhedron "body.vol"}
	{Bone "rig_spine2"}
	{Position -10.4563	0.764412	0.000155782}
}
{Volume "foot1l"
	{Polyhedron "foot1l.vol"}
	{Bone "rig_l_thigh"}
	{Position 0	7.82013e-05	-8.01086e-05}
}
{Volume "foot1r"
	{Polyhedron "foot1r.vol"}
	{Bone "rig_r_thigh"}
	{Position 0	-1.90735e-05	8.10623e-05}
}
{Volume "foot2l"
	{Polyhedron "foot2l.vol"}
	{Bone "rig_l_calf"}
	{Position -0.00556946	-0.1528	0.439037}
}
{Volume "foot2r"
	{Polyhedron "foot2r.vol"}
	{Bone "rig_r_calf"}
	{Position -0.00551224	-0.152799	-0.439117}
}
{Volume "hand1l"
	{Polyhedron "hand1l.vol"}
	{Bone "rig_l_upperarm"}
	{Position 1.03351	0.616627	-1.51887}
}
{Volume "hand1r"
	{Polyhedron "hand1r.vol"}
	{Bone "rig_r_upperarm"}
	{Position 1.23243	0.589829	1.66422}
}
{Volume "hand2l"
	{Polyhedron "hand2l.vol"}
	{Bone "rig_l_forearm"}
	{Position 1.42757	0.599676	-1.01944}
}
{Volume "hand2r"
	{Polyhedron "hand2r.vol"}
	{Bone "rig_r_forearm"}
	{Position 2.82871	-0.476068	-0.990921}
}
{Volume "head"
	{Polyhedron "head.vol"}
	{Bone "rig_head"}
	{Position -7.73458	5.91438	-0.000155782}
}
{Volume "shield_hand1l"
	{Polyhedron "shield_hand1l.vol"}
	{Bone "rig_spine2"}
	{Position 10.6449	-1.44765	10.3893}
}
{Volume "shield_hand1r"
	{Polyhedron "shield_hand1r.vol"}
	{Bone "rig_spine2"}
	{Position 10.6449	-1.44765	-10.3893}
}
