
(Include "\[SC_Plataform]\SC_helpers\inventory_item\SC_inventory_item.inc")

; =====================================================
; // ENTITY/WEAPON/DEF
; =====================================================

(Define "SC/Entity/"
	("Entity" args ork_goffs_t3_sq_02)
)
; =====================================================
; // SET/STUFF/WEAPON
; =====================================================

(Define "SC/Stuff/"
	{from "sc_skin_inventory_item"	{entity "ork_goffs_t3_sq_02"}}
)



