
; spot
{sequence "walk_spot_gun_down" 				{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}	
{sequence "walk_spot_gun_up" 				{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_gun_up_1" 				{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_gun_down_1" 			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}
{sequence "walk_spot_gun_up_2" 				{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_gun_down_2" 			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_gun_belt_down" 		{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}	
{sequence "walk_spot_gun_belt_up" 			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_gun_half-mast_down"	{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}
{sequence "walk_spot_gun_half-mast_up" 		{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_mgun_down" 			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}	
{sequence "walk_spot_mgun_up" 				{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_mgun_down_1"			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}	
{sequence "walk_spot_mgun_up_1"				{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
{sequence "walk_spot_pistol_down" 			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}	{events {0 "SC_H_Request_Anm_Walk_Spot"}}}
{sequence "walk_spot_pistol_up" 			{resume} {file "/[SC_Plataform]/SC_animations/human/z_dummy.anm"}}	
				
; // Mask
{sequence "walk_spot_gun_down_mask"				{file "walk_spot_gun_down.anm"} 			{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_up_mask"				{file "walk_spot_gun_up.anm"} 				{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_up_1_mask"				{file "walk_spot_gun_up_1.anm"} 			{speed 0.37} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_down_1_mask"			{file "walk_spot_gun_down_1.anm"} 			{speed 0.37} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_up_2_mask"				{file "walk_spot_gun_up_2.anm"} 			{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_down_2_mask"			{file "walk_spot_gun_down_2.anm"} 			{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_belt_down_mask"		{file "walk_spot_gun_belt_down.anm"} 		{speed 0.35} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_belt_up_mask"			{file "walk_spot_gun_belt_up.anm"} 			{speed 0.35} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_half-mast_down_mask"	{file "walk_spot_gun_half-mast_down.anm"}	{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_gun_half-mast_up_mask"		{file "walk_spot_gun_half-mast_up.anm"} 	{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_mgun_down_mask"			{file "walk_spot_mgun_down.anm"} 			{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_mgun_up_mask"				{file "walk_spot_mgun_up.anm"} 				{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_mgun_down_1_mask"			{file "walk_spot_mgun_down_1.anm"}			{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_mgun_up_1_mask"			{file "walk_spot_mgun_up_1.anm"}			{speed 0.45} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_pistol_down_mask"			{file "walk_spot_pistol_down.anm"} 			{speed 0.37} {resume} {events {10 "leg_left"} {40 "leg_right"}}}
{sequence "walk_spot_pistol_up_mask"			{file "walk_spot_pistol_up.anm"} 			{speed 0.37} {resume}}
