
(Define "W_Main_MM"
	{bone "melta_gun"
		{Matrix34
			0	0	-1
			-1	0	0
			0	1	0
			0	0	0
		}
		{parameters "ID=gun;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/landspeeder_Chassis/melta_gun.ply"}
		{bone "foresight_melta"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-0.0258339	-24.1716	-6.55408
			}
		}
		{bone "barrel_melta01"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-0.0258339	-24.1695	-4.4403
			}
		}
		{bone "barrel_melta00"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-0.0258362	-24.1693	-8.52723
			}
		}
	}
)