
(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

(define "Pattern_Orks_Orknob_Burna_1"				("Skeleton" color(%color) skin(orknob_burna_1)))
(define "Pattern_Orks_Orknob_Bigmek_1"				("Skeleton" color(%color) skin(orknob_bigmek_1)))
(define "Pattern_Orks_Orknob_Flashgit_1"			("Skeleton" color(%color) skin(orknob_flashgit_1)))
(define "Pattern_Orks_Orknob_Kommando_1"			("Skeleton" color(%color) skin(orknob_kommando_1)))
(define "Pattern_Orks_Orknob_Shoota_1"				("Skeleton" color(%color) skin(orknob_shoota_1)))
(define "Pattern_Orks_Orknob_Shoota_Ardboy_1"		("Skeleton" color(%color) skin(orknob_shoota_ardboy_1)))
(define "Pattern_Orks_Orknob_Stormnob_1"			("Skeleton" color(%color) skin(orknob_stormnob_1)))
	
; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** EVIL SUNZ ***
(define "Skin_Evilsunz_Orknob_Burna_1"					("Pattern_Orks_Orknob_Burna_1"				color(Evilsunz)))
(define "Skin_Evilsunz_Orknob_Bigmek_1"					("Pattern_Orks_Orknob_Bigmek_1"				color(Evilsunz)))
(define "Skin_Evilsunz_Orknob_Flashgit_1"				("Pattern_Orks_Orknob_Flashgit_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orknob_Kommando_1"				("Pattern_Orks_Orknob_Kommando_1"			color(Evilsunz)))
(define "Skin_Evilsunz_Orknob_Shoota_1"					("Pattern_Orks_Orknob_Shoota_1"				color(Evilsunz)))
(define "Skin_Evilsunz_Orknob_Shoota_Ardboy_1"			("Pattern_Orks_Orknob_Shoota_Ardboy_1"		color(Evilsunz)))
(define "Skin_Evilsunz_Orknob_Stormnob_1"				("Pattern_Orks_Orknob_Stormnob_1"			color(Evilsunz)))


; // *** BADMOONS ***
(define "Skin_Badmoons_Orknob_Burna_1"					("Pattern_Orks_Orknob_Burna_1"				color(Badmoons)))
(define "Skin_Badmoons_Orknob_Bigmek_1"					("Pattern_Orks_Orknob_Bigmek_1"				color(Badmoons)))
(define "Skin_Badmoons_Orknob_Flashgit_1"				("Pattern_Orks_Orknob_Flashgit_1"			color(Badmoons)))
(define "Skin_Badmoons_Orknob_Kommando_1"				("Pattern_Orks_Orknob_Kommando_1"			color(Badmoons)))
(define "Skin_Badmoons_Orknob_Shoota_1"					("Pattern_Orks_Orknob_Shoota_1"				color(Badmoons)))
(define "Skin_Badmoons_Orknob_Shoota_Ardboy_1"			("Pattern_Orks_Orknob_Shoota_Ardboy_1"		color(Badmoons)))
(define "Skin_Badmoons_Orknob_Stormnob_1"				("Pattern_Orks_Orknob_Stormnob_1"			color(Badmoons)))


; // *** GOFFS ***
(define "Skin_Goffs_Orknob_Burna_1"						("Pattern_Orks_Orknob_Burna_1"				color(Goffs)))
(define "Skin_Goffs_Orknob_Bigmek_1"					("Pattern_Orks_Orknob_Bigmek_1"				color(Goffs)))
(define "Skin_Goffs_Orknob_Flashgit_1"					("Pattern_Orks_Orknob_Flashgit_1"			color(Goffs)))
(define "Skin_Goffs_Orknob_Kommando_1"					("Pattern_Orks_Orknob_Kommando_1"			color(Goffs)))
(define "Skin_Goffs_Orknob_Shoota_1"					("Pattern_Orks_Orknob_Shoota_1"				color(Goffs)))
(define "Skin_Goffs_Orknob_Shoota_Ardboy_1"				("Pattern_Orks_Orknob_Shoota_Ardboy_1"		color(Goffs)))
(define "Skin_Goffs_Orknob_Stormnob_1"					("Pattern_Orks_Orknob_Stormnob_1"			color(Goffs)))


