
(Define "SL_Ork_Shoota"
	{bone "l_ork_deffgun"
		{parameters "ID=aux_turret3;"}
		{Matrix34
			1	0	0
			0	0	-1
			0	1	0
			-16.5916	-49.3827	64.081
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/russ_chassis/l_ork_deffgun.ply"}
		{bone "foresight_l_ork_deffgun"
			{Position 34.0106	64.0811	48.4985}
			{bone "barrel_l_ork_deffgun00"
				{Position -1.76805	0	2.79154}
			}
			{bone "barrel_l_ork_deffgun01"
				{Position -1.76805	0	-2.89189}
			}
		}
	}
)