
; // Orks
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(ork_grottank)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01))
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(ork_battlewagon)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01))
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(ork_gunwagon)			t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01))
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(Ork_Kill_Tank)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01))
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(Ork_Russ)				t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01))
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(Ork_Rhino)			t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01))

; // Space Marines
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(SM_landraider)		t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02))
("SC_H_Crew_Define_Skin_T_Crew_Bailout"	v(SM_rhino)				t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02))