

; // ================================== ##### @@ [ ORKS / "EVILSUNZ" ] @@ ##### ================================== \\

; // GROT TANK
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_grottank) p(commander)	t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_mo4_seat03))

; // AMMO BOX
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_ammo_box) p(gunner)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(ammo_box_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_ammo_box) p(commander)	t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(ammo_box_commander))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_ammo_box) p(driver1)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(ammo_box_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_ammo_box) p(driver2)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(ammo_box_commander))

; // WARBUGGY - DRIVER AND COMMANDER SEATS ARE SHARED BETWEEN VARIANTS
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_warbuggy) p(driver)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(seat_opel_driver))
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_warbuggy) p(commander)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_dodge_sg2))

; // GUNWAGON - KANNON
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_kannon) p(gunner)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_mo4_mg_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_kannon) p(commander)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_m5_charger))

; // GUNWAGON - FLAKK
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_flakk) p(gunner)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_seat_drifter12))
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_flakk) p(commander)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_seat_drifter14))

; // GUNWAGON - ZZAP
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_zzap) p(gunner)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_mo4_charger))
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_zzap) p(commander)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_mo4_commander))

; // WARTRAKK 
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_wartrakk) p(driver)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_mo4_driver))

; // WARBIKE
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_ork_warbike) p(driver)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_kfz70_driver))

; // GUNWAGON - CARRIER
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(gunner)			t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_mo4_mg_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger01)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_01) a())	; dakka nobz
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger02)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_01) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger03)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_01) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger04)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_01) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger05)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_02) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger06)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_02) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger07)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_02) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_gunwagon_transport) p(passenger08)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_03) a())

; // BATTLEWAGON
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_battlewagon) p(gunner5)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_dshk_aa_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_battlewagon) p(gunner4)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_dshk_aa_gunner))

; // FLAKKGUN
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_flak_20mm_flakvierling38) p(gunner)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(seat_flakvierling_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_flak_20mm_flakvierling38) p(charger)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(seat_flakvierling_charger))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_flak_20mm_flakvierling38) p(commander)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(seat_flakvierling_commander))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_flak_20mm_flakvierling38) p(driver1)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_pak40_pusher_right))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_flak_20mm_flakvierling38) p(driver2)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_pak40_pusher_left))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_flak_20mm_flakvierling38) p(driver3)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(mortar_driver_l))

; // MEKGUN
("SC_H_Crew_Define_Skin_T_Crew"	v(Ork_mekgun) p(charger)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_kpvt_charger))
("SC_H_Crew_Define_Skin_T_Crew"	v(Ork_mekgun) p(gunner)			t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_nebel42_gunlayer))
("SC_H_Crew_Define_Skin_T_Crew"	v(Ork_mekgun) p(commander)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_mo4_seat02))
("SC_H_Crew_Define_Skin_T_Crew"	v(Ork_mekgun) p(driver1)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_kpvt_charger))
("SC_H_Crew_Define_Skin_T_Crew"	v(Ork_mekgun) p(driver2)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_nebel42_gunlayer))
("SC_H_Crew_Define_Skin_T_Crew"	v(Ork_mekgun) p(driver3)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(pose_mo4_seat02))

; // GROT KANNON
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(gunner)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(charger)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_charger))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(charger2)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_charger2))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(commander)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_commander))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(driver1)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_gunner))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(driver2)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_charger))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(driver3)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_charger2))
("SC_H_Crew_Define_Skin_T_Crew"	v(temp_ork_76mm_m1927) p(driver4)		t(sc_skin_tag_lv40k_orkgrot_ork_evilsunz_t0_01) a(cannon_small_commander))

; // WARTRUKK - DRIVER AND COMMANDER SEATS ARE SHARED BETWEEN VARIANTS
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_Wartrukk) p(driver)		t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(seat_opel_driver))
("SC_H_Crew_Define_Skin_T_Crew"	v(ork_wartrukk) p(commander)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_tx_tankman_01) a(pose_kfz70_driver))

("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger00)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_09) a())	; // <- Flashgitz
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger01)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_09) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger02)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_09) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger03)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_09) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger04)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_10) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger05)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_10) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger06)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_10) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk_burna) p(passenger07)	t(sc_skin_tag_lv40k_orknob_ork_evilsunz_t3_11) a())

("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger00)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_01) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger01)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_01) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger02)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_02) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger03)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_02) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger04)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_03) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger05)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_03) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger06)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_04) a())
("SC_H_Crew_Define_Skin_T_Crew"	v(evz_Wartrukk) p(passenger07)	t(sc_skin_tag_lv40k_orkboy_ork_evilsunz_t1_04) a())

; // LANDRAIDER
("SC_H_Crew_Define_Skin_T_Crew"	v(SM_landraider) p(gunner)		t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02) a(pose_seat_drifter12))

; // RHINO/PREDATOR
("SC_H_Crew_Define_Skin_T_Crew"	v(SM_rhino) p(gunner)			t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02) a(pose_seat_drifter12))
("SC_H_Crew_Define_Skin_T_Crew"	v(SM_rhino) p(gunner1)			t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02) a(pose_seat_drifter12))

; // LAND SPEEDER
("SC_H_Crew_Define_Skin_T_Crew"	v(sm_Landspeeder) p(driver)		t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02) a(lv40k_sms-land_speeder_Driver))
("SC_H_Crew_Define_Skin_T_Crew"	v(sm_Landspeeder) p(commander)	t(sc_skin_tag_lv40k_spacemarine_sm_ultramarines_tx_tankman_02) a(lv40k_sms-land_speeder_Gunner))