
("SC_H_Crew_Define_Vehicle_Restriction_Only_Crew" v(ork_grottank) tag(sc_h_skin_tag_skeleton_lv40k_orkgrot))
("SC_H_Crew_Define_Vehicle_Restriction_Only_Crew" v(ork_mekgun) tag(sc_h_skin_tag_skeleton_lv40k_orkgrot))
("SC_H_Crew_Define_Vehicle_Restriction_Only_Crew" v(temp_ork_flak_20mm_flakvierling38) tag(sc_h_skin_tag_skeleton_lv40k_orkgrot))

("SC_H_Crew_Define_Vehicle_Restriction_Only_Crew" v(ork_warbuggy) tag(sc_h_skin_tag_skeleton_lv40k_orkboy))
("SC_H_Crew_Define_Vehicle_Restriction_Only_Crew" v(ork_warbike) tag(sc_h_skin_tag_skeleton_lv40k_orkboy))
("SC_H_Crew_Define_Vehicle_Restriction_Only_Crew" v(ork_wartrakk) tag(sc_h_skin_tag_skeleton_lv40k_orkboy))

; // ("SC_H_Crew_Define_Vehicle_Restriction_Allow_Passenger" v(vehicle) tag(team2))
; // ("SC_H_Crew_Define_Vehicle_Restriction" v(ork_gunwagon) tag(team3))