

(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

(define "Pattern_Ogryn_1"			("Skeleton" color(%color) skin(+models_Ogryn)))
(define "Pattern_Bonehead_1"		("Skeleton" color(%color) skin(+models_Bonehead)))
(define "Pattern_Bullgryn_1"		("Skeleton" color(%color) skin(+models_Bullgryn)))

; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** DEFAULT ***

(define "Skin_Ogryn_1"			("Pattern_Ogryn_1"			color(default)))
(define "Skin_Ogryn_Bonehead_1"		("Pattern_Bonehead_1"		color(default)))
(define "Skin_Ogryn_Bullgryn_1"		("Pattern_Bullgryn_1"		color(default)))

; // *** KRIEG ***

; // *** CHAOS ***

