
(Define "Entities_LV40k_human")

(Define "Entities_LV40k_Troopers_S1"

	; // ORKS
	{entity "HI_orkboy_slugga_badmoons_1"}	
	{entity "HI_orkboy_slugga_evilsunz_1"}	
	{entity "HI_orkboy_slugga_goffs_1"}	
	{entity "HI_orkboy_ardboy_badmoons_1"}		
	{entity "HI_orkboy_ardboy_evilsunz_1"}		
	{entity "HI_orkboy_ardboy_goffs_1"}	

	; // TYRANIDS
	{entity "HI_tyr_hormagaunt_leviathan_1"}	
	{entity "HI_tyr_hormagaunt_leviathan_2"}	
	{entity "HI_tyr_hormagaunt_kraken_1"}	
	{entity "HI_tyr_hormagaunt_kraken_2"}
	{entity "HI_tyr_warrior_bs_kraken_1"}	
	{entity "HI_tyr_warrior_bs_leviathan_1"}	
	{entity "HI_tyr_warrior_tl_kraken_1"}
	{entity "HI_tyr_warrior_tl_leviathan_1"}				
	{entity "HI_tyr_hivenode_kraken_1"}	
	{entity "HI_tyr_hivenode_leviathan_1"}	
)

(Define "Entities_LV40k_Troopers_S2"
	
	; // ORKS	
	{entity "HI_orknob_badmoons_1"}	
	{entity "HI_orknob_evilsunz_1"}	
	{entity "HI_orknob_goffs_1"}			
	{entity "HI_meganob_evilsunz_1"}
	{entity "HI_meganob_evilsunz_2"}		
	{entity "HI_meganob_badmoons_1"}	
	{entity "HI_meganob_badmoons_2"}
	{entity "HI_meganob_goffs_1"}
	{entity "HI_meganob_goffs_2"}
	
	; // TYRANIDS
	{entity "HI_tyr_biovore_leviathan_1"}
	{entity "HI_tyr_biovore_kraken_1"}
	{entity "HI_tyr_pyrovore_leviathan_1"}	
	{entity "HI_tyr_pyrovore_kraken_1"}	
	{entity "HI_tyr_genestealer_leviathan_1"}
	{entity "HI_tyr_genestealer_kraken_1"}		
	{entity "HI_tyr_lictor_leviathan_1"}	
	{entity "HI_tyr_lictor_kraken_1"}	
	{entity "HI_tyr_hiveguard_kraken_1"}
	{entity "HI_tyr_hiveguard_kraken_imp_1"}	
	{entity "HI_tyr_hiveguard_kraken_shk_1"}	
	{entity "HI_tyr_hiveguard_leviathan_1"}	
	{entity "HI_tyr_hiveguard_leviathan_imp_1"}	
	{entity "HI_tyr_hiveguard_leviathan_shk_1"}		
)

(Define "Entities_LV40k_Troopers_S3"
	
	; // SPACE MARINES
	{entity "HI_term_assaultcannon_UMS_1"}
	{entity "HI_term_assaultcannon_UMS_2"}
	{entity "HI_term_commander_ac_UMS_1"}
	{entity "HI_term_commander_hf_UMS_1"}
	{entity "HI_term_commander_sb_UMS_1"}
	{entity "HI_term_commander_th_UMS_1"}
	{entity "HI_term_heavyflamer_UMS_1"}
	{entity "HI_term_heavyflamer_UMS_2"}
	{entity "HI_term_stormbolter_UMS_1"}
	{entity "HI_term_stormbolter_UMS_2"}
	{entity "HI_term_thunderhammer_UMS_1"}
	{entity "HI_term_thunderhammer_UMS_2"}
	
	; // ORKS	
	{entity "HI_warboss_badmoons_1"}
	{entity "HI_warboss_evilsunz_1"}
	{entity "HI_warboss_goffs_1"}
	
	; // TYRANIDS
	{entity "HI_tyr_exocrine_leviathan_1"}	
	{entity "HI_tyr_exocrine_kraken_1"}	
	{entity "HI_tyr_hivetyrant_melee_kraken_1"}	
	{entity "HI_tyr_hivetyrant_melee_leviathan_1"}	
	{entity "HI_tyr_hivetyrant_vc_kraken_1"}	
	{entity "HI_tyr_hivetyrant_vc_leviathan_1"}	
	{entity "HI_tyr_tervigon_kraken_1"}	
	{entity "HI_tyr_tervigon_leviathan_1"}	
	{entity "HI_tyr_tyrannofex_kraken_1"}	
	{entity "HI_tyr_tyrannofex_leviathan_1"}
	{entity "HI_tyr_swarmlord_kraken_1"}	
	{entity "HI_tyr_swarmlord_leviathan_1"}		
	{entity "HI_tyr_carnifex_brbstr_kraken_1"}	
	{entity "HI_tyr_carnifex_brbstr_kraken_2"}	
	{entity "HI_tyr_carnifex_brbstr_leviathan_1"}	
	{entity "HI_tyr_carnifex_brbstr_leviathan_2"}	
	{entity "HI_tyr_carnifex_melee_kraken_1"}	
	{entity "HI_tyr_carnifex_melee_kraken_2"}	
	{entity "HI_tyr_carnifex_melee_leviathan_1"}	
	{entity "HI_tyr_carnifex_melee_leviathan_2"}
	{entity "HI_tyr_carnifex_vmcn_kraken_1"}	
	{entity "HI_tyr_carnifex_vmcn_kraken_2"}	
	{entity "HI_tyr_carnifex_vmcn_leviathan_1"}	
	{entity "HI_tyr_carnifex_vmcn_leviathan_2"}	
	{entity "HI_tyr_hellfex_dev_kraken_1"}	
	{entity "HI_tyr_hellfex_dev_leviathan_1"}	
	{entity "HI_tyr_oldoneeye_kraken_1"}	
	{entity "HI_tyr_oldoneeye_leviathan_1"}
)