
(Define "Gun_Shootas"
	{bone "w_twinshoota"
		{parameters "ID=turret;"}
		{Matrix34
			0	1	0
			-1	0	0
			0	0	1
			0	0	-1.57207e-05
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/warbuggy_chassis/w_twinshoota.ply"}
		{bone "barrel00"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				3.45309	-23.2389	2.71361
			}
		}
		{bone "barrel01"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				3.45309	-23.2389	-2.74421
			}
		}
		{bone "foresight_shoota"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				3.55304	-24.1781	-0.0836545
			}
		}
		{bone "fxshell00"
			{Matrix34
				0	0	1
				1	0	0
				0	1	0
				4.66965	0.55121	5.35373
			}
		}
		{bone "fxshell01"
			{Matrix34
				0	0	-1
				1	0	0
				0	-1	0
				4.66965	0.55121	-5.50183
			}
		}
	}
)