
(Define "Aux_Megablasta"
	{bone "R_Megablasta"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/R_Megablasta.ply"}
	}
	{bone "L_Megablasta"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/L_Megablasta.ply"}
	}
	{bone "l_base"
		{parameters "ID=aux_turret1;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/l_base.ply"}
	}
	{bone "r_base"
		{parameters "ID=aux_turret2;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Deffdread_Chassis/r_base.ply"}
	}
)