
(Define "Base"
	{bone "rocket_battery"
		{bone "shield_rocket_launcher"
			{parameters "ID=body;"}
			{Position 9.93057	-0.320563	20.9577}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/ig_artillery/shield_rocket_launcher.ply"}
			{bone "fx_rl1"
				{Position 1.70969	-0.0355725	7.01171}
			}
		}
		{bone revolute "gun_rot"
			{Matrix34
				1	0	0
				0	0	1
				0	-1	0
				-2.7474	-0.406256	29.8634
			}
			{bone "w_rocket_launcher"
				{parameters "ID=gun;"}
				{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/ig_artillery/w_rocket_launcher.ply"}
			}
			{bone "foresight_rl"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					26.545	-0.13698	-0.292839
				}
			}
			{bone "barrel_rl00"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	4.48459	-12.3361
				}
				{bone "smoke_rl00"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl01"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	2.25419	-8.32903
				}
				{bone "smoke_rl01"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl02"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23893	-2.285	-8.41595
				}
				{bone "smoke_rl02"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl03"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23893	-2.285	-16.3284
				}
				{bone "smoke_rl03"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl04"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	2.25419	-16.2415
				}
				{bone "smoke_rl04"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl05"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23893	-4.56882	-12.3361
				}
				{bone "smoke_rl05"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl06"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	4.48459	12.2424
				}
				{bone "smoke_rl06"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl07"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	2.25419	16.2494
				}
				{bone "smoke_rl07"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl08"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	-2.285	16.1625
				}
				{bone "smoke_rl08"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl09"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	-2.285	8.25007
				}
				{bone "smoke_rl09"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl10"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	2.25419	8.33699
				}
				{bone "smoke_rl10"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
			{bone "barrel_rl11"
				{Matrix34
					1	0	0
					0	0	-1
					0	1	0
					8.23892	-4.56882	12.2424
				}
				{bone "smoke_rl11"
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						-17.014	0	0
					}
				}
			}
		}
	}
)