
{Volume "wheelfront"
	{Cylinder 35.4331 115.157}
	{Bone "wheelfront1"}
	{Matrix34
		-1	0	0
		0	-1	0
		0	0	1
		0	-5.30938e-05	-0.218224
	}
}
{Volume "shield_front"
	{Box 44.2913 118.11 68.8976}
	{Bone "body_front1"}
	{Matrix34
		0.906308	0	0.422618
		0	1	0
		-0.422618	0	0.906308
		126.036	0	38.6867
	}
}

; ======================================================================== ;

{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Matrix34
		1	0	0
		0	0	-1
		0	1	0
		46.8232	88.6345	2.42035
	}
}
{Volume "body2"
	{Polyhedron "body2.vol"}
	{Bone "body"}
	{Matrix34
		1	0	0
		0	0	-1
		0	1	0
		0	12.2876	-2.67029e-05
	}
}
{Volume "body3"
	{Polyhedron "body3.vol"}
	{Bone "body"}
	{Matrix34
		1	0	0
		0	0	-1
		0	1	0
		-76.6213	58.2361	52.4378
	}
}
{Volume "body4"
	{Polyhedron "body4.vol"}
	{Bone "body"}
	{Matrix34
		1	0	0
		0	0	-1
		0	1	0
		-69.0784	58.2364	-51.6162
	}
}
{Volume "body5"
	{Polyhedron "body5.vol"}
	{Bone "body"}
	{Matrix34
		1	0	0
		0	0	-1
		0	1	0
		-77.2587	54.1541	1.58145
	}
}
{Volume "trackleft1"
	{Polyhedron "trackleft1.vol"}
	{Bone "wheell3"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		0	0.000106812	-9.38029
	}
}
{Volume "trackleft2"
	{Polyhedron "trackleft2.vol"}
	{Bone "wheell4"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		-9.53674e-05	5.34058e-05	-12.106
	}
}
{Volume "trackleft3"
	{Polyhedron "trackleft3.vol"}
	{Bone "wheell5"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		-9.91821e-05	8.01086e-05	-9.64266
	}
}
{Volume "trackleft"
	{Polyhedron "trackleft.vol"}
	{Bone "wheelsl"}
	{Position -63.5863	49.6415	0}
}
{Volume "trackright1"
	{Polyhedron "trackright1.vol"}
	{Bone "wheelr3"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		9.72748e-05	-5.34058e-05	-9.42724
	}
}
{Volume "trackright2"
	{Polyhedron "trackright2.vol"}
	{Bone "wheelr4"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		0.000152588	2.67029e-05	-12.0669
	}
}
{Volume "trackright3"
	{Polyhedron "trackright3.vol"}
	{Bone "wheelr5"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		-0.000434875	-0.000133514	-9.74085
	}
}
{Volume "trackright"
	{Polyhedron "trackright.vol"}
	{Bone "wheelsr"}
	{Position -63.5863	-49.6378	0}
}
{Volume "wheelleft1"
	{Polyhedron "wheelleft1.vol"}
	{Bone "wheelleft1"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		-0.00605774	-0.546305	-22.1367
	}
}
{Volume "wheelleft2"
	{Polyhedron "wheelleft2.vol"}
	{Bone "wheelleft2"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		-0.000244141	-0.546246	-22.1398
	}
}
{Volume "wheelright1"
	{Polyhedron "wheelright1.vol"}
	{Bone "wheelright1"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		0	-0.546309	-2.65432
	}
}
{Volume "wheelright2"
	{Polyhedron "wheelright2.vol"}
	{Bone "wheelright2"}
	{Matrix34
		-1	0	0
		0	0	1
		0	1	0
		0	-0.546457	-2.65433
	}
}
