{"NATO"
	{title "mp/army/nato"}
	{armies "nato"}
	{icon "/interface/pages/multi/flag_nato"}
}
{"Ukraine"
	{title "mp/army/ukr"}
	{armies "ukr"}
	{icon "/interface/pages/multi/flag_ukr"}
}
{"Russia"
	{title "mp/army/rusa"}
	{armies "rusa"}
	{icon "/interface/pages/multi/flag_rusa"}
}
{"PRC"
	{title "mp/army/prc"}
	{armies "prc"}
	{icon "/interface/pages/multi/flag_prc"}
}
{"Imperium"
	{title "mp/alliance/imperium"}
	{armies "imp"}
	{icon "/interface/pages/multi/flag_imp"}
}
{"Tyranids"
	{title "mp/alliance/tyranids"}
	{armies "tyr"}
	{icon "/interface/pages/multi/flag_tyr"}
}
{"Orks"
	{title "mp/alliance/orks"}
	{armies "ork"}
	{icon "/interface/pages/multi/flag_ork"}
}
