
(Define "SL_Lascannon"
	{bone "l_lascannon"
		{parameters "ID=aux_turret2;"}
		{Matrix34
			0	0	-1
			-1	0	0
			0	1	0
			14.3013	-0.219707	-0.0286865
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/dorn_chassis/l_lascannon.ply"}
		{bone "foresight_L_lascannon"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				0.0427475	-21.3874	-0.822823
			}
		}
		{bone "fx_L_lascannon"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				-0.172791	8.22081	4.4079
			}
		}
	}
)