
; Check instructions in: "/set/breed/SC_Plataform/[MP]/SC_Skin_Selector.inc"

(Include "[Randomizer]/LV40k_orkboys.inc")
(Include "[Randomizer]/LV40k_orknobs.inc")
(Include "[Randomizer]/LV40k_orkgrots.inc")

(Define "LV40k_MP_Breeds_Orks"

;================================================================================================================================================;
; // EVILSUNZ
;================================================================================================================================================;

;//										skin_breed_name			skin_skeleton				randomizer_ID

; ------------------------------------------------------------------------------------ ; 
; // [T0] - Grots
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t0_01		LV40k_Orkgrot				LV40k_Orkgrot_001)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t0_02		LV40k_Orkgrot				LV40k_Orkgrot_001)

; ------------------------------------------------------------------------------------ ; 
; // [T1] - Boys
; ------------------------------------------------------------------------------------ ;

; // SHOOTA BOYZ
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t1_01		LV40k_Orkboy				LV40k_Orkboy_001)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t1_02		LV40k_Orkboy				LV40k_Orkboy_001)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t1_03		LV40k_Orkboy				LV40k_Orkboy_011)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t1_04		LV40k_Orkboy				LV40k_Orkboy_001)

; // TANKBUSTAS
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t1_05		LV40k_Orkboy				LV40k_Orkboy_003)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t1_06		LV40k_Orkboy				LV40k_Orkboy_003)

; // LOOTAS
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t1_07		LV40k_Orkboy				LV40k_Orkboy_004)

; ------------------------------------------------------------------------------------ ; 
; // [T2] - 'Ard Boys
; ------------------------------------------------------------------------------------ ;

; // SHOOTA ARDBOYZ
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t2_01		LV40k_Orkboy				LV40k_Orkboy_002)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t2_02		LV40k_Orkboy				LV40k_Orkboy_002)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t2_03		LV40k_Orkboy				LV40k_Orkboy_002b)

; // STORMBOYS
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t2_04		LV40k_Orkboy				LV40k_Orkboy_007)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t2_05		LV40k_Orkboy				LV40k_Orkboy_007)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t2_06		LV40k_Orkboy				LV40k_Orkboy_007)

; // KOMMANDO BOYZ
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t2_07		LV40k_Orkboy				LV40k_Orkboy_005)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t2_08		LV40k_Orkboy				LV40k_Orkboy_005)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_t2_09		LV40k_Orkboy				LV40k_Orkboy_005)

; ------------------------------------------------------------------------------------ ; 
; // [T3] - Nobs 
; ------------------------------------------------------------------------------------ ;

; // SHOOTA NOBZ
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_01		LV40k_Orknob				LV40k_Orknob_001)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_02		LV40k_Orknob				LV40k_Orknob_001)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_03		LV40k_Orknob				LV40k_Orknob_001)

; // STORMNOBS
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_04		LV40k_Orknob				LV40k_Orknob_002)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_05		LV40k_Orknob				LV40k_Orknob_002)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_06		LV40k_Orknob				LV40k_Orknob_002)

; // KOMMANDO NOBS
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_07		LV40k_Orknob				LV40k_Orknob_003)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_08		LV40k_Orknob				LV40k_Orknob_003)

; // FLASH GITZ
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_09		LV40k_Orknob				LV40k_Orknob_004)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_10		LV40k_Orknob				LV40k_Orknob_004)
("SC_Skin_Tag_Selector"		args	%0	ork_evilsunz_t3_11		LV40k_Orknob				LV40k_Orknob_004)

; ------------------------------------------------------------------------------------ ; 
; // [TX] - Oddboys 
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_tx_at_01			LV40k_Orkboy		LV40k_Orkboy_004)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_tx_flamer_01		LV40k_Orkboy		LV40k_Orkboy_008)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_tx_medic_01		LV40k_Orkboy		LV40k_Orkboy_009)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_tx_psyker_01		LV40k_Orkboy		LV40k_Orkboy_006)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_tx_tankman_01		LV40k_Orkboy		LV40k_Orkboy_012)
("SC_Skin_Tag_Selector"		args	%0 	ork_evilsunz_tx_mekboy_01		LV40k_Orkboy		LV40k_Orkboy_013)

;================================================================================================================================================;
; // GOFFS
;================================================================================================================================================;

; ###### // GOFFS GET NO KOMMANDOZ!

; ------------------------------------------------------------------------------------ ; 
; // [T0] - Grots
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t0_01		LV40k_Orkgrot				LV40k_Orkgrot_001)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t0_02		LV40k_Orkgrot				LV40k_Orkgrot_001)

; ------------------------------------------------------------------------------------ ; 
; // [T1] - Boys
; ------------------------------------------------------------------------------------ ;

; // SHOOTA BOYZ
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t1_01		LV40k_Orkboy				LV40k_Orkboy_001)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_t1_02		LV40k_Orkboy				LV40k_Orkboy_001)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t1_03		LV40k_Orkboy				LV40k_Orkboy_011)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_t1_04		LV40k_Orkboy				LV40k_Orkboy_001)

; // TANKBUSTAS
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t1_05		LV40k_Orkboy				LV40k_Orkboy_003)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_t1_06		LV40k_Orkboy				LV40k_Orkboy_003)

; // LOOTAS
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t1_07		LV40k_Orkboy				LV40k_Orkboy_004)

; ------------------------------------------------------------------------------------ ; 
; // [T2] - 'Ard Boys
; ------------------------------------------------------------------------------------ ;

; // SHOOTA ARDBOYZ
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t2_01		LV40k_Orkboy				LV40k_Orkboy_002)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_t2_02		LV40k_Orkboy				LV40k_Orkboy_002)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t2_03		LV40k_Orkboy				LV40k_Orkboy_002b)

; // STORMBOYS
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t2_04		LV40k_Orkboy				LV40k_Orkboy_007)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t2_05		LV40k_Orkboy				LV40k_Orkboy_007)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t2_06		LV40k_Orkboy				LV40k_Orkboy_007)

; ------------------------------------------------------------------------------------ ; 
; // [T3] - Nobs 
; ------------------------------------------------------------------------------------ ;

; // SHOOTA NOBZ
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_01		LV40k_Orknob				LV40k_Orknob_001)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_02		LV40k_Orknob				LV40k_Orknob_001)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_03		LV40k_Orknob				LV40k_Orknob_001)

; // STORMNOBS
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_04		LV40k_Orknob				LV40k_Orknob_002)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_05		LV40k_Orknob				LV40k_Orknob_002)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_06		LV40k_Orknob				LV40k_Orknob_002)

; // FLASH GITZ
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_09		LV40k_Orknob				LV40k_Orknob_004)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_10		LV40k_Orknob				LV40k_Orknob_004)
("SC_Skin_Tag_Selector"		args	%0	ork_goffs_t3_11		LV40k_Orknob				LV40k_Orknob_004)

; ------------------------------------------------------------------------------------ ; 
; // [TX] - Oddboys 
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_at_01			LV40k_Orkboy		LV40k_Orkboy_004)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_flamer_01		LV40k_Orkboy		LV40k_Orkboy_008)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_medic_01		LV40k_Orkboy		LV40k_Orkboy_009)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_psyker_01		LV40k_Orkboy		LV40k_Orkboy_006)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_tankman_01		LV40k_Orkboy		LV40k_Orkboy_012)

;//("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_mekboy_01		LV40k_Orkboy		LV40k_Orkboy_013)
("SC_Skin_Tag_Selector"		args	%0 	ork_goffs_tx_mekboy_01		LV40k_Orknob		LV40k_Orknob_005)

;================================================================================================================================================;
; // BADMOONS
;================================================================================================================================================;

; ###### // BADMOONS GET NO DAKKA-NOBS! ONLY FLASH GITZ!

)