
; Check instructions in: "/set/breed/SC_Plataform/[MP]/SC_Skin_Selector.inc"

(Include "[Randomizer]/LV40k_tyranids.inc")

(Define "LV40k_MP_Breeds_Tyr"

;================================================================================================================================================;
; // KRAKEN
;================================================================================================================================================;

;//										skin_breed_name			skin_skeleton				randomizer_ID

; ------------------------------------------------------------------------------------ ; 
; // [T0] - Gaunts
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t0_01		LV40k_Tyranidgaunt			LV40k_Termagaunt_001)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t0_02		LV40k_Tyranidgaunt			LV40k_Termagaunt_001)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t0_03		LV40k_Tyranidgaunt			LV40k_Termagaunt_001)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t0_04		LV40k_Tyranidgaunt			LV40k_Termagaunt_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t0_05		LV40k_Tyranidgaunt			LV40k_Termagaunt_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t0_06		LV40k_Tyranidgaunt			LV40k_Termagaunt_002)

; ------------------------------------------------------------------------------------ ; 
; // [T1] - Warriors
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_01		LV40k_Tyranidwarrior		LV40k_Warrior_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_02		LV40k_Tyranidwarrior		LV40k_Warrior_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_03		LV40k_Tyranidwarrior		LV40k_Warrior_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_04		LV40k_Tyranidwarrior		LV40k_Warrior_002)

; // Adapted Brood
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_05		LV40k_Tyranidwarrior		LV40k_Warrior_003)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_06		LV40k_Tyranidwarrior		LV40k_Warrior_003)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_07		LV40k_Tyranidwarrior		LV40k_Warrior_003)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_08		LV40k_Tyranidwarrior		LV40k_Warrior_003)

; // Tyranid Prime
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_09		LV40k_Tyranidwarrior		LV40k_Warrior_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_10		LV40k_Tyranidwarrior		LV40k_Warrior_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_11		LV40k_Tyranidwarrior		LV40k_Warrior_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t1_12		LV40k_Tyranidwarrior		LV40k_Warrior_004)

; ------------------------------------------------------------------------------------ ; 
; // [T2] - Zoanthropes
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t2_01		LV40k_Tyranidzoanthrope		LV40k_Zoanthrope_003)

; ------------------------------------------------------------------------------------ ; 
; // [T3] - Raveners
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t3_01		LV40k_Tyranidravener		LV40k_Ravener_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t3_02		LV40k_Tyranidravener		LV40k_Ravener_005)

; ------------------------------------------------------------------------------------ ; 
; // [T4] - Venomthrope
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_kraken_t4_01		LV40k_Tyranidvenomthrope	LV40k_Venomthrope_006)

;================================================================================================================================================;
; // BEHEMOTH
;================================================================================================================================================;

;================================================================================================================================================;
; // LEVIATHAN
;================================================================================================================================================;

; ------------------------------------------------------------------------------------ ; 
; // [T0] - Gaunts
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t0_01		LV40k_Tyranidgaunt			LV40k_Termagaunt_001)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t0_02		LV40k_Tyranidgaunt			LV40k_Termagaunt_001)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t0_03		LV40k_Tyranidgaunt			LV40k_Termagaunt_001)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t0_04		LV40k_Tyranidgaunt			LV40k_Termagaunt_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t0_05		LV40k_Tyranidgaunt			LV40k_Termagaunt_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t0_06		LV40k_Tyranidgaunt			LV40k_Termagaunt_002)


; ------------------------------------------------------------------------------------ ; 
; // [T1] - Warriors
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_01		LV40k_Tyranidwarrior		LV40k_Warrior_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_02		LV40k_Tyranidwarrior		LV40k_Warrior_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_03		LV40k_Tyranidwarrior		LV40k_Warrior_002)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_04		LV40k_Tyranidwarrior		LV40k_Warrior_002)

; // Adapted Brood
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_05		LV40k_Tyranidwarrior		LV40k_Warrior_003)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_06		LV40k_Tyranidwarrior		LV40k_Warrior_003)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_07		LV40k_Tyranidwarrior		LV40k_Warrior_003)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_08		LV40k_Tyranidwarrior		LV40k_Warrior_003)

; // Tyranid Prime
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_09		LV40k_Tyranidwarrior		LV40k_Warrior_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_10		LV40k_Tyranidwarrior		LV40k_Warrior_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_11		LV40k_Tyranidwarrior		LV40k_Warrior_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t1_12		LV40k_Tyranidwarrior		LV40k_Warrior_004)

; ------------------------------------------------------------------------------------ ; 
; // [T2] - Zoanthropes
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t2_01		LV40k_Tyranidzoanthrope		LV40k_Zoanthrope_003)

; ------------------------------------------------------------------------------------ ; 
; // [T3] - Raveners
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t3_01		LV40k_Tyranidravener		LV40k_Ravener_004)
("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t3_02		LV40k_Tyranidravener		LV40k_Ravener_005)

; ------------------------------------------------------------------------------------ ; 
; // [T4] - Venomthrope
; ------------------------------------------------------------------------------------ ;

("SC_Skin_Tag_Selector"		args	%0	tyr_leviathan_t4_01		LV40k_Tyranidvenomthrope	LV40k_Venomthrope_006)

)