(define "common_fg"
	else stuff "fx_proj_pointer"
	else stuff "fx_bul_small"
	else stuff "fx_bul_med"
	else stuff "fx_10_15 fx_ap"
	else stuff "fx_10_15"
	{spawn "ex_air_norm"}
	else stuff "fx_16_24 fx_ap"
	else stuff "fx_16_24"
	{spawn "ex_air_norm"}
	else stuff "fx_25_40 fx_ap"
	else stuff "fx_25_40"
	{spawn "ex_air_norm"}
	else stuff "fx_gren fx_ap"
	else stuff "fx_gren fx_cm"
	{spawn "ex_air_big"}
	else stuff "fx_gren"
	{spawn "ex_air_norm"}	
	else stuff "fx_45_89 fx_ap"
	else stuff "fx_45_89 fx_cm"
	{spawn "ex_air_cmnorm"}	
	else stuff "fx_45_89 fx_cl"
	;{spawn "ex_air_big"}
	{spawn "ex_air_he_size5"}
	else stuff "fx_45_89"
	{spawn "ex_air_norm2"}	
	else stuff "fx_90_110 fx_ap"
	else stuff "fx_90_110 fx_cm"
	{spawn "ex_air_cmnorm"}	
	else stuff "fx_90_110"
	{spawn "ex_air_big"}
	else stuff "fx_111_145 fx_ap"
	else stuff "fx_111_145 fx_cm"
	{spawn "ex_air_cmbig"}
	else stuff "fx_111_145"
	{spawn "ex_air_big2"}
	else stuff "fx_146_299 fx_ap"
	else stuff "fx_146_299 fx_cm"
	{spawn "ex_air_cmbig"}
	else stuff "fx_146_299"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto15kg fx_cm"
	{spawn "ex_air_cmbig"}
	else stuff "fx_upto15kg"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto50kg"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto250kg"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto1000kg"
	{spawn "ex_air_extrabig"}
	else stuff "molotov_coctail"
	{spawn "ex_molot"}
	else stuff "big sm"
	{spawn "ex_air_norm2"}	
	else stuff "sm"	
	{spawn "ex_air_norm"}	
	else stuff "fx_tos"
	{spawn "ex_bomb_250kg"}
	else stuff "fx_shmel"
	{spawn "ex_shmel"}
)
(define "metal"	
	else stuff "fx_proj_pointer"
	else stuff "fx_bul_small"
	{spawn "metal_hit_bul"}	
	else stuff "fx_bul_med"	
	{spawn "metal_hit_bul"}
	else stuff "fx_10_15 fx_ap"
	{spawn "metal_hit_bul"}	
	else stuff "fx_10_15"
	{spawn "ex_air_norm"}
	else stuff "fx_16_24 fx_ap"
	{spawn "metal_hit_br_small"}
	else stuff "fx_16_24"
	{spawn "ex_air_norm"}
	else stuff "fx_25_40 fx_ap"
	{spawn "metal_hit_br_small"}
	else stuff "fx_25_40"
	{spawn "ex_air_norm"}
	else stuff "fx_gren fx_ap"
	{spawn "metal_hit_br"}
	else stuff "fx_gren fx_cm"
	{spawn "ex_air_big"}
	else stuff "fx_gren"
	{spawn "ex_air_norm"}
	else stuff "fx_45_89 fx_ap"
	{spawn "metal_hit_br"}	
	else stuff "fx_45_89 fx_cm"
	{spawn "metal_hit_fg"}	
	else stuff "fx_45_89 fx_cl"
	{spawn "ex_air_he_size5"}
	else stuff "fx_45_89"
	{spawn "metal_hit_fg"}	
	else stuff "fx_90_110 fx_ap"
	{spawn "metal_hit_br"}
	else stuff "fx_90_110 fx_cm"
	{spawn "metal_hit_fg"}
	else stuff "fx_90_110"
	{spawn "metal_hit_fg"}
	else stuff "fx_111_145 fx_ap"
	{spawn "metal_hit_br"}
	else stuff "fx_111_145 fx_cm"
	{spawn "metal_hit_fg"}
	else stuff "fx_111_145"
	{spawn "metal_hit_fg_big"}
	else stuff "fx_146_299 fx_ap"
	{spawn "metal_hit_br"}
	else stuff "fx_146_299 fx_cm"
	{spawn "metal_hit_fg_big"}
	else stuff "fx_146_299"	
	{spawn "metal_hit_fg_big"}
	else stuff "fx_upto15kg fx_cm"
	{spawn "metal_hit_fg_big"}
	else stuff "fx_upto15kg"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto50kg"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto250kg"
	{spawn "ex_air_extrabig"}
	else stuff "fx_upto1000kg"
	{spawn "ex_air_extrabig"}
	else stuff "molotov_coctail" 
	{spawn "ex_molot"}	
	else stuff "big sm"	
	else stuff "sm"		
	else stuff "fx_tos"	
	{spawn "ex_air_big"}	
	else stuff "fx_shmel"	
	{spawn "ex_air_big2"}
)

