
(Define "Supply_Trukk"
	{bone "ammo_trukk"
		{Position -4.64875	-5.21654	-43.5241}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Wartrukk_Chassis/Supply_Trukk/ammo_trukk.ply"}
		{bone "ammo_trukk_details2"
			{Position -69.421	15.9965	49.1483}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Wartrukk_Chassis/Supply_Trukk/ammo_trukk_details2.ply"}
		}
		{bone "ammo_trukk_details4"
			{Position 0	0	0}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Wartrukk_Chassis/Supply_Trukk/ammo_trukk_details4.ply"}
		}
		{bone "ammo_trukk_details1"
			{Position -8.64971	-14.3571	74.3991}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Wartrukk_Chassis/Supply_Trukk/ammo_trukk_details1.ply"}
		}
		{bone "ammo_trukk_details3"
			{Position -69.2187	-18.2622	49.2648}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Wartrukk_Chassis/Supply_Trukk/ammo_trukk_details3.ply"}
		}
		{bone "ammo_trukk_details5"
			{Position -8.64971	11.152	74.3991}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/Vehicles/Wartrukk_Chassis/Supply_Trukk/ammo_trukk_details5.ply"}
		}
	}
)