
{Volume "trackleft"
	{Polyhedron "trackleft.vol"}
	{Bone "trackl"}
	{Position 3.01628	-42.5334	0}
}
{Volume "trackright"
	{Polyhedron "trackright.vol"}
	{Bone "trackr"}
	{Position 3.01628	-42.5334	0}
}


{Volume "ammo"
	{Polyhedron "ammo.vol"}
	{Bone "hellhound_tank"}
	{Position -19.0561	0	31.6272}
}
{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Position 48.8429	-12.2869	10.2435}
}
{Volume "body2"
	{Polyhedron "body2.vol"}
	{Bone "body_tracks"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		-42.5334	-3.01626	0
	}
}
{Volume "body3"
	{Polyhedron "body3.vol"}
	{Bone "body_tracks"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		42.5394	-3.01624	0
	}
}
{Volume "body4"
	{Polyhedron "body4.vol"}
	{Bone "body"}
	{Position -24.8603	0	10.2435}
}
{Volume "body5"
	{Polyhedron "body5.vol"}
	{Bone "body"}
	{Position 46.0623	17.5708	10.2435}
}
{Volume "gun"
	{Box 31.4961 14.7638 7.28346}
	{Bone "barrel"}
	{Position 76.3799	-10.5733	66.1582}
}
{Volume "turret1"
	{Cylinder 18.1102 2.95276}
	{Bone "turret"}
	{Position 0.421204	0	-0.551493}
}
{Volume "turret2"
	{Polyhedron "turret2.vol"}
	{Bone "turret"}
	{Position 0	0	-0.0414238}
}
