

(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

(define "Pattern_SM_Unique_1"				("Skeleton" color(%color) skin(+models_%name)))	

(define "Pattern_SM_H_Apothecary_1"			("Skeleton" color(%color) skin(+models_h_apothecary)))
(define "Pattern_SM_H_Chaplain_1"			("Skeleton" color(%color) skin(+models_h_chaplain)))
(define "Pattern_SM_H_Commander_1"			("Skeleton" color(%color) skin(+models_h_commander)))
(define "Pattern_SM_H_Librarian_1"			("Skeleton" color(%color) skin(+models_h_librarian)))	
(define "Pattern_SM_H_Techmarine_1"			("Skeleton" color(%color) skin(+models_h_techmarine)))

(define "Pattern_SM_Sternguard_1"			("Skeleton" color(%color) skin(+models_strn)))
(define "Pattern_SM_Sternguard_Sgt_1"		("Skeleton" color(%color) skin(+models_strn_sgt)))

(define "Pattern_SM_Assault_1"				("Skeleton" color(%color) skin(+models_asslt)))
(define "Pattern_SM_Assault_Sgt_1"			("Skeleton" color(%color) skin(+models_asslt_sgt)))
(define "Pattern_SM_Assault_Vet_1"			("Skeleton" color(%color) skin(+models_asslt_vet)))
(define "Pattern_SM_Assault_Vet_Sgt_1"		("Skeleton" color(%color) skin(+models_asslt_vet_sgt)))

(define "Pattern_SM_Devastator_1"			("Skeleton" color(%color) skin(+models_dev)))
(define "Pattern_SM_Devastator_Sgt_1"		("Skeleton" color(%color) skin(+models_dev_sgt)))
(define "Pattern_SM_Devastator_Vet_1"		("Skeleton" color(%color) skin(+models_dev_vet)))	
(define "Pattern_SM_Devastator_Vet_Sgt_1"	("Skeleton" color(%color) skin(+models_dev_vet_sgt)))	

(define "Pattern_SM_Tactical_1"				("Skeleton" color(%color) skin(+models_tac)))
(define "Pattern_SM_Tactical_Sgt_1"			("Skeleton" color(%color) skin(+models_tac_sgt)))	
(define "Pattern_SM_Tactical_Vet_1"			("Skeleton" color(%color) skin(+models_tac_vet)))	
(define "Pattern_SM_Tactical_Vet_Sgt_1"		("Skeleton" color(%color) skin(+models_tac_vet_sgt)))	

; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** ULTRAMARINES ***

(define "Skin_Ultramarines_H_Apothecary_1"			("Pattern_SM_H_Apothecary_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_H_Chaplain_1"			("Pattern_SM_H_Chaplain_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_H_Commander_1"			("Pattern_SM_H_Commander_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_H_Librarian_1"			("Pattern_SM_H_Librarian_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_H_Techmarine_1"			("Pattern_SM_H_Techmarine_1"			color(sm_Ultramarines)))

(define "Skin_Ultramarines_Sternguard_1"			("Pattern_SM_Sternguard_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_Sternguard_Sgt_1"		("Pattern_SM_Sternguard_Sgt_1"			color(sm_Ultramarines)))

(define "Skin_Ultramarines_Tactical_1"				("Pattern_SM_Tactical_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_Tactical_Sgt_1"			("Pattern_SM_Tactical_Sgt_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_Tactical_Vet_1"			("Pattern_SM_Tactical_Vet_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_Tactical_Vet_Sgt_1"		("Pattern_SM_Tactical_Vet_Sgt_1"		color(sm_Ultramarines)))

(define "Skin_Ultramarines_Assault_1"				("Pattern_SM_Assault_1"					color(sm_Ultramarines)))
(define "Skin_Ultramarines_Assault_Sgt_1"			("Pattern_SM_Assault_Sgt_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_Assault_Vet_1"			("Pattern_SM_Assault_Vet_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_Assault_Vet_Sgt_1"		("Pattern_SM_Assault_Vet_Sgt_1"			color(sm_Ultramarines)))

(define "Skin_Ultramarines_Devastator_1"			("Pattern_SM_Devastator_1"				color(sm_Ultramarines)))
(define "Skin_Ultramarines_Devastator_Sgt_1"		("Pattern_SM_Devastator_Sgt_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_Devastator_Vet_1"		("Pattern_SM_Devastator_Vet_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_Devastator_Vet_Sgt_1"	("Pattern_SM_Devastator_Vet_Sgt_1"		color(sm_Ultramarines)))

; // *** DEATHWATCH ***
(define "Skin_Deathwatch_Tactical_1"				("Pattern_SM_Tactical_1"				color(sm_Deathwatch)))