
(Define "Tarantula_ML"
	{bone "tarantula_ml"
		{parameters "ID=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/tarantula_ml.ply"}
		{bone "ml_ammo00"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo00.ply"}
		}
		{bone "ml_ammo03"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo03.ply"}
		}
		{bone "ml_ammo02"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo02.ply"}
		}
		{bone "ml_ammo07"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo07.ply"}
		}
		{bone "ml_ammo06"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo06.ply"}
		}
		{bone "ml_ammo11"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo11.ply"}
		}
		{bone "ml_ammo10"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo10.ply"}
		}
		{bone "ml_ammo09"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo09.ply"}
		}
		{bone "ml_ammo08"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo08.ply"}
		}
		{bone "ml_ammo05"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo05.ply"}
		}
		{bone "ml_ammo04"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo04.ply"}
		}
		{bone "ml_ammo01"
			{parameters "ID=body;"}
			{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/tarantula_chassis/ml_ammo01.ply"}
		}
	}
)