
(Include "/set/interaction_entity/SC_Plataform/SC_allegiance.inc")


(Include "LV40k_orks/LV40k_call_ins-orks_digga.inc")
(Include "LV40k_orks/LV40k_call_ins-orks_stormboyz.inc")
(Include "LV40k_orks/LV40k_call_ins-orks_rokk.inc")


(Include "LV40k_tyranids/LV40k_call_ins-tyr_raveners.inc")
(Include "LV40k_tyranids/LV40k_call_ins-tyr_mycetic.inc")

(Include "LV40k_spacemarines/LV40k_call_ins-sms_terminators.inc")
(Include "LV40k_spacemarines/LV40k_call_ins-sms_tarantula.inc")
(Include "LV40k_spacemarines/LV40k_call_ins-sms_droppod.inc")
(Include "LV40k_spacemarines/LV40k_call_ins-sms_thunderhawk.inc")
(Include "Lv40k_spacemarines/LV40k_call_ins-sms_assaultmarines.inc")
(Include "Lv40k_spacemarines/LV40k_call_ins-sms_orbital_strike.inc")