
{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Position -17.6249	-0.0670869	10.6027}
}
{Volume "body"
	{Polyhedron "body.vol"}
	{Bone "body"}
	{Position 4.5013	0	19.9184}
}
{Volume "engine"
	{Polyhedron "engine.vol"}
	{Bone "body"}
	{Position -17.6249	-0.0670869	10.6027}
}
{Volume "mantlet"
	{Polyhedron "mantlet.vol"}
	{Bone "gun_rot"}
	{Matrix34
		1	0	0
		0	0	1
		0	-1	0
		2.04804	0.441544	-0.0670851
	}
}
{Volume "trackleft"
	{Polyhedron "trackleft.vol"}
	{Bone "wheelsl"}
	{Position -5.97847	18.6741	11.0308}
}
{Volume "trackright"
	{Polyhedron "trackright.vol"}
	{Bone "wheelsr"}
	{Position -5.97848	-18.8649	11.0308}
}
{Volume "turret1"
	{Polyhedron "turret1.vol"}
	{Bone "turret"}
	{Position 0	0	0}
}
{Volume "turret"
	{Polyhedron "turret.vol"}
	{Bone "turret"}
	{Position 5.97256	-0.00207259	-23.9509}
}
