
(include "lv40k_orks-cannons.inc")

(include "lv40k_orks-battlewagon.inc")
(include "lv40k_orks-deff_dread.inc")
(include "lv40k_orks-gorkanaut.inc")
(include "lv40k_orks-trukk.inc")
(include "lv40k_orks-kill_tank.inc")
(include "lv40k_orks-gun_wagon.inc")
(include "lv40k_orks-warbuggy.inc")
(include "lv40k_orks-warbike.inc")
(include "lv40k_orks-wartrakk.inc")
(include "lV40k_orks-grottank.inc")