

(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

(define "Pattern_SM_P_Tactical_1"				("Skeleton" color(%color) skin(+models_tac)))
(define "Pattern_SM_P_Tactical_Sgt_1"			("Skeleton" color(%color) skin(+models_tac_sgt)))	

(define "Pattern_SM_P_Sternguard_1"				("Skeleton" color(%color) skin(+models_strn)))
(define "Pattern_SM_P_Sternguard_Sgt_1"			("Skeleton" color(%color) skin(+models_strn_sgt)))

(define "Pattern_SM_P_Devastator_1"				("Skeleton" color(%color) skin(+models_dev)))
(define "Pattern_SM_P_Devastator_Sgt_1"			("Skeleton" color(%color) skin(+models_dev_sgt)))	

(define "Pattern_SM_P_Reiver_1"					("Skeleton" color(%color) skin(+models_reiver)))
(define "Pattern_SM_P_Reiver_Sgt_1"				("Skeleton" color(%color) skin(+models_reiver_sgt)))	

(define "Pattern_SM_P_Inceptor_1"				("Skeleton" color(%color) skin(+models_incp)))
(define "Pattern_SM_P_Inceptor_Sgt_1"			("Skeleton" color(%color) skin(+models_incp_sgt)))	

; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** ULTRAMARINES ***

(define "Skin_Ultramarines_P_Tactical_1"		("Pattern_SM_P_Tactical_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_P_Tactical_Sgt_1"	("Pattern_SM_P_Tactical_Sgt_1"		color(sm_Ultramarines)))

(define "Skin_Ultramarines_P_Sternguard_1"		("Pattern_SM_P_Sternguard_1"		color(sm_Ultramarines)))
(define "Skin_Ultramarines_P_Sternguard_Sgt_1"	("Pattern_SM_P_Sternguard_Sgt_1"	color(sm_Ultramarines)))

(define "Skin_Ultramarines_P_Devastator_1"		("Pattern_SM_P_Devastator_1"		color(sm_Ultramarines)))
(define "Skin_Ultramarines_P_Devastator_Sgt_1"	("Pattern_SM_P_Devastator_Sgt_1"	color(sm_Ultramarines)))

(define "Skin_Ultramarines_P_Reiver_1"			("Pattern_SM_P_Reiver_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_P_Reiver_Sgt_1"		("Pattern_SM_P_Reiver_Sgt_1"		color(sm_Ultramarines)))

(define "Skin_Ultramarines_P_Inceptor_1"		("Pattern_SM_P_Inceptor_1"			color(sm_Ultramarines)))
(define "Skin_Ultramarines_P_Inceptor_Sgt_1"	("Pattern_SM_P_Inceptor_Sgt_1"		color(sm_Ultramarines)))

(define "Skin_Ultramarines_P_Victrix_1"			("Skeleton" color(sm_Ultramarines) skin(+models_victrix)))		; // <- ULTRAMARINES only
