
(Define "WR_HB"
	{bone revolute "gun_rot2"
		{parameters "ID=aux_turret2;"}
		{Orientation
			1	0	0
			0	0	1
			0	-1	0
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/landraider_chassis/hbs_right.ply"}
		{bone "fxshell_wr_hb02"
			{Matrix34
				0	0	1
				1	0	0
				0	1	0
				18.1212	-7.09229	12.0302
			}
		}
		{bone "fxshell_wr_hb00"
			{Matrix34
				0	0	1
				1	0	0
				0	1	0
				12.3596	3.94186	12.0302
			}
		}
		{bone "fxshell_wr_hb03"
			{Matrix34
				0	0	1
				1	0	0
				0	1	0
				18.1212	-7.09229	-2.71795
			}
		}
		{bone "fxshell_wr_hb01"
			{Matrix34
				0	0	1
				1	0	0
				0	1	0
				12.3596	3.94186	-2.71795
			}
		}
		{bone "foresight_wr_hb"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				45.5204	1.2579	0.0797577
			}
		}
		{bone "barrel_wr_hb03"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				38.0223	-5.62279	-7.27841
			}
		}
		{bone "barrel_wr_hb02"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				38.0223	-5.62277	7.16818
			}
		}
		{bone "barrel_wr_hb01"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				31.4884	5.38963	-7.27841
			}
		}
		{bone "barrel_wr_hb00"
			{Matrix34
				1	0	0
				0	0	-1
				0	1	0
				31.4884	5.3896	7.16818
			}
		}
	}
)