;SDL
	{if stuff "shell 75to76 all_he"
		{spawn "killzone_dummy_75"}
	else stuff "shell size2 88to105 all_he"
		{spawn "killzone_dummy_88"}
	else stuff "shell size3 88to105 all_he"
		{spawn "killzone_dummy_105"}
	else stuff "shell 122to128 all_he"
		{spawn "killzone_dummy_122"}
	else stuff "shell 150to152 all_he"
		{spawn "killzone_dummy_150"}
	else stuff "shell size5 all_he"
		{spawn "killzone_dummy_200"}
	else stuff "shell size6 all_he"
		{spawn "killzone_dummy_200"}
	else stuff "shell size7 all_he"
		{spawn "killzone_dummy_200"}
	}