
{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		0	-19.9704	6.6132
	}
}
{Volume "body2"
	{Polyhedron "body2.vol"}
	{Bone "body"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		0	-0.197895	6.6132
	}
}
{Volume "engine"
	{Polyhedron "engine.vol"}
	{Bone "body"}
	{Matrix34
		0	-1	0
		1	0	0
		0	0	1
		0	38.6846	21.8
	}
}
{Volume "shield1"
	{Polyhedron "shield1.vol"}
	{Bone "pilot_shield"}
	{Position 12.1469	-7.4055	37.6765}
}
