

(Include "MDL_Skeleton.inc")
	

; ============================================================================================================== ;
; // PATTERNS
; ============================================================================================================== ;

(define "Pattern_Tyr_Venomthrope_1"	("Skeleton" color(%color) skin(+models_Venomthrope)))

; ============================================================================================================== ;
; // SKIN DEFINES
; ============================================================================================================== ;

; // *** KRAKEN ***
(define "Skin_Kraken_Venomthrope_1"		("Pattern_Tyr_Venomthrope_1"	color(kraken)))

; // *** LEVIATHAN ***
(define "Skin_Leviathan_Venomthrope_1"	("Pattern_Tyr_Venomthrope_1"	color(leviathan)))
