
{Smooth 0.05}

(Include "lv40k_orkboy_nw/_lv40k_orkboy.ext")
(Include "lv40k_orkboy/_lv40k_orkboy.ext")
(Include "lv40k_sms/_lv40k_sms.ext")
(Include "lv40k_scouts/_lv40k_scouts.ext")
(Include "lv40k_sync_deaths/_lv40k_sync_deaths.ext")

(Include "lv40k_tyranids/lv40k_ravener/_lv40k_ravener.ext")
(Include "lv40k_tyranids/lv40k_termagaunt/_lv40k_termagaunt.ext")
(Include "lv40k_tyranids/lv40k_zoanthrope/_lv40k_zoanthrope.ext")
(Include "lv40k_tyranids/lv40k_warrior/_lv40k_warrior.ext")
(Include "lv40k_tyranids/lv40k_venomthrope/_lv40k_venomthrope.ext")

