
(Define "Ork_Predator_Base"
	{bone "ork_predator_fuel_tank"
		{parameters "id=body;"}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/rhino_chassis/ork_looted_predator/ork_predator_fuel_tank.ply"}
	}
	{bone "ork_predator_details"
		{parameters "id=body;"}
		{Position 4.52161	0.393701	42.9293}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/rhino_chassis/ork_looted_predator/ork_predator_details.ply"}
	}
)