
(Define "W_Pintle_HB"
	{bone "heavy_bolter"
		{Matrix34
			0	0	-1
			-1	0	0
			0	1	0
			7.12612	4.97631	0.336987
		}
		{VolumeView "/entity/[+SC_DLC_LV40k]/+Models/vehicles/landspeeder_Chassis/heavy_bolter.ply"}
		{bone "fxshell_pintle_hb"
			{Matrix34
				-1	0	0
				0	-1	0
				0	0	1
				-1.93167	-3.89266	0.640259
			}
		}
		{bone "foresight_pintle_hb"
			{Matrix34
				0	-1	0
				1	0	0
				0	0	1
				0.397921	-14.9103	0
			}
		}
	}
)