
{Volume "body1"
	{Polyhedron "body1.vol"}
	{Bone "body"}
	{Position 37.5046	-12.2869	10.2435}
}
{Volume "body2"
	{Polyhedron "body2.vol"}
	{Bone "body_tracks"}
	{Position 3.01625	-42.5334	0}
}
{Volume "body3"
	{Polyhedron "body3.vol"}
	{Bone "body_tracks"}
	{Position 3.01625	42.5394	0}
}
{Volume "body4"
	{Polyhedron "body4.vol"}
	{Bone "body"}
	{Position -7.60458	0	10.2435}
}
{Volume "body5"
	{Polyhedron "body5.vol"}
	{Bone "body"}
	{Position 34.724	17.5708	10.2435}
}
{Volume "trackleft"
	{Polyhedron "trackleft.vol"}
	{Bone "trackl"}
	{Position 3.01628	-42.5334	0}
}
{Volume "trackright"
	{Polyhedron "trackright.vol"}
	{Bone "trackr"}
	{Position 3.01628	-42.5334	0}
}