
{Volume "fuel"
	{Polyhedron "fuel.vol"}
	{Bone "body"}
}
{Volume "body1"
	{Polyhedron "body_1.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "body2"
	{Polyhedron "body_2.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "body3"
	{Polyhedron "body_3.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "body4"
	{Polyhedron "body_4.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "body5"
	{Polyhedron "body_5.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "body6"
	{Polyhedron "body_6.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "engine"
	{Box 23.622 27.5591 20.6693}
	{Bone "body"}
	{Position 46.4596	-6.49973	-12.9372}
}
{Volume "shield15"
	{Cylinder 2.95276 50.1968}
	{Bone "parts2"}
	{Matrix34
		1	0	0
		0	0.956665	-0.291193
		0	0.291193	0.956665
		11.1991	36.3562	44.802
	}
}
{Volume "shield10"
	{Polyhedron "shield_10.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "shield11"
	{Polyhedron "shield_11.vol"}
	{Bone "parts3"}
	{Position 0	0	0}
}
{Volume "shield12"
	{Polyhedron "shield_12.vol"}
	{Bone "parts1"}
}
{Volume "shield13"
	{Polyhedron "shield_13.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "shield14"
	{Polyhedron "shield_14.vol"}
	{Bone "body"}
	{Position -4.64875	-5.21654	-43.5241}
}
{Volume "shield1"
	{Polyhedron "shield_1.vol"}
	{Bone "parts5"}
	{Position 0	0	0}
}
{Volume "shield2"
	{Polyhedron "shield_2.vol"}
	{Bone "parts7"}
	{Position 0	0	0}
}
{Volume "shield3"
	{Polyhedron "shield_3.vol"}
	{Bone "parts6"}
	{Position 0	0	0}
}
{Volume "shield4"
	{Polyhedron "shield_4.vol"}
	{Bone "parts11"}
}
{Volume "shield5"
	{Polyhedron "shield_5.vol"}
	{Bone "parts10"}
	{Position 0	0	0}
}
{Volume "shield6"
	{Polyhedron "shield_6.vol"}
	{Bone "parts9"}
	{Position 0	0	0}
}
{Volume "shield7"
	{Polyhedron "shield_7.vol"}
	{Bone "parts8"}
	{Position 0	0	0}
}
{Volume "shield8"
	{Polyhedron "shield_8.vol"}
	{Bone "backdoor"}
	{Position 59.3619	1.35644	-35.6662}
}
{Volume "shield9"
	{Polyhedron "shield_9.vol"}
	{Bone "parts4"}
	{Position 0	0	0}
}
{Volume "wheelleft1"
	{Cylinder 12.7953 13.2489}
	{Bone "wheel1l"}
	{Position -0.00780487	0	2.5061}
}
{Volume "wheelleft2"
	{Cylinder 16.7323 17.0276}
	{Bone "wheel2l"}
	{Position 0.126002	0.468614	0.825017}
}
{Volume "wheelleft3"
	{Cylinder 16.7323 17.0276}
	{Bone "wheel3l"}
	{Position -0.0119667	0.145009	0.678458}
}
{Volume "wheelright1"
	{Cylinder 12.7953 13.2489}
	{Bone "wheel1r"}
	{Position 0	0	-2.64708}
}
{Volume "wheelright2"
	{Cylinder 16.7323 17.0276}
	{Bone "wheel2r"}
	{Position 0.388042	0.207108	-1.22065}
}
{Volume "wheelright3"
	{Cylinder 16.7323 17.0276}
	{Bone "wheel3r"}
	{Position -0.022522	0.00993066	-0.405519}
}