
(Include "LV40k_sms-droppods.inc")
(Include "LV40k_sms-dreadnought.inc")
(Include "LV40k_sms-landspeeder.inc")
(Include "LV40k_sms-landraider.inc")
(Include "LV40k_sms-tarantula.inc")
(Include "LV40k_sms-thunderfire.inc")

; // Modulated for readability
(Include "LV40k_sms-rhino/LV40k_razorback.inc")
(Include "LV40k_sms-rhino/LV40k_predator.inc")
(Include "LV40k_sms-rhino/LV40k_rhino.inc")
(Include "LV40k_sms-rhino/LV40k_vindicator.inc")
(Include "LV40k_sms-rhino/LV40k_whirlwind.inc")
(Include "LV40k_sms-rhino/LV40k_damocles.inc")