;; ///////////////////////////// Modern Small Arms Defines For Code X by Diesel ///////////////////////////////////////////////////////////////////////
(define "DShK38_CodeX"
	 
	{link_sound		"HMG_Mid"		"weapon/shot/smallarms/s4/d2/RUS/DShK38/"}
	{link_sound		"HMG_Far"		"weapon/shot/smallarms/s4/d3/RUS/DShK38/"}
)

(define "M240_CodeX"				;Placeholder Universal Sounds
	{link_sound		"MG_Mid"		"weapon/shot/small-arms/s4/d2/M240/"}
	{link_sound		"MG_Far"		"weapon/shot/small-arms/s4/d3/M240/"} ; Placeholder
)

(define "PKT_CodeX"				;Placeholder Universal Sounds
	{link_sound		"MG_Mid"		"weapon/shot/small-arms/s4/d2/PKM/"}
	{link_sound		"MG_Far"		"weapon/shot/small-arms/s4/d3/PKM/"} ; Placeholder
)

(define "M2HB_CodeX"				;Placeholder Universal Sounds
	 
	{link_sound		"HMG_Mid"		"weapon/shot/small-arms/s4/d2/USA/M2HB/"}
	{link_sound		"HMG_Far"		"weapon/shot/small-arms/s4/d3/RUS/DShK38/"} ; Placeholder
)

(define "M134_CodeX"				;Placeholder Universal Sounds
	; 
	{link_sound		"HMG_Mid"		"weapon/shot/small-arms/s4/d2/M134/"}
	{link_sound		"HMG_Far"		"weapon/shot/small-arms/s4/d3/M134/"} ; Placeholder
)

(define "KPVT_CodeX"			;Placeholder Universal Sounds
	 
	{link_sound		"HMG_Mid"		"weapon/shot/small-arms/s4/d2/KPVT/"}
	{link_sound		"HMG_Far"		"weapon/shot/small-arms/s4/d3/KPVT/"}
)

(define "Kord_CodeX"			;Placeholder Universal Sounds
	 
	{link_sound		"HMG_Mid"		"weapon/shot/small-arms/s4/d2/Kord/"}
	{link_sound		"HMG_Far"		"weapon/shot/small-arms/s4/d3/Kord/"}
)

(define "AGS_CodeX"		;Placeholder Universal Sounds
	 
	{link_sound		"HMG_Mid"		"weapon/shot/small-arms/s4/d2/AGS_Systems/"}
	{link_sound		"HMG_Far"		"weapon/shot/small-arms/s4/d3/AGS_Systems/"}
)

(define "AGS30_CodeX"		;Placeholder Universal Sounds
	 
	{link_sound		"HMG_Mid"		"weapon/shot/small-arms/s4/d2/AGS30/"}
	{link_sound		"HMG_Far"		"weapon/shot/small-arms/s4/d3/AGS30/"}
)

(define "ATGMEast"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Atgm_Mid"		"weapon/shot/cannon/s1/d2/RUS/Eastern_ATGM/"}
	{link_sound		"Atgm_Far"		"weapon/shot/cannon/s1/d3/RUS/Eastern_ATGM/"}
)

(define "ATGMWest"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Atgm_Mid"		"weapon/shot/cannon/s1/d2/USA/Western_ATGM/"}
	{link_sound		"Atgm_Far"		"weapon/shot/cannon/s1/d3/USA/Western_ATGM/"}
)

(define "Bradley25mm"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/USA/Bradley_25mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/USA/Bradley_25mm/"}
)

(define "Bushmaster30mm_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/Nato/30mm_Bushmaster/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/Nato/30mm_Bushmaster/"}
)

(define "Nato40mmAuto_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/Nato/40mm_Nato_Autocannon/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/Nato/40mm_Nato_Autocannon/"}
)


(define "BMP73mm_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/RUS/BMP1_73mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/RUS/BMP1_73mm/"}
)

(define "Mortar_8cm_codex"
	{link_sound		"Recoil"		"weapon/shot/cannon/s2/recoil/Shared/Mortar/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s2/d2/Shared/Mortar/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s2/d3/Shared/Mortar/"}
)

(define "Mortar_12cm_codex"
	{link_sound		"Recoil"		"weapon/shot/cannon/s3/recoil/Shared/Mortar/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s3/d2/Shared/Mortar/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s3/d3/Shared/Mortar/"}
)

(define "ZU23mm_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/RUS/ZU_23mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/RUS/ZU_23mm/"}
)

(define "30mm2A42_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/RUS/BMP2_2A42/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/RUS/BMP2_2A42/"}
)

(define "30mm2A72_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/RUS/BTR_2A72/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/RUS/BTR_2A72/"}
)

(define "57mm_2A90_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s2/d2/Shared/Cannon_50to57mm_HV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s2/d3/Shared/Cannon_50to57mm_HV/"}
)

(define "100mm2A70_CodeX"		;Placeholder Universal Sounds
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_85to100mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_85to100mm/"}
)

(define "RUS_100HV_MT12"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_85to100mm_HV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_85to100mm_HV/"}
)

(define "Nato_100HV_MGS"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_85to100mm_HV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_85to100mm_HV/"}
)

(define "Hawkeye_105_MGS"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_105to130mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_105to130mm/"}
)

(define "Tankgun120_125mm_CodeX"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_105to130mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_105to130mm/"}
)

(define "Generic_122mm_CodeX"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_105to130mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_105to130mm/"}
)

(define "RUS_152mm_CodeX"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_105to130mm_LV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_105to130mm_LV/"}
)

(define "Nato_155mm_CodeX"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s3/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s5/d2/Shared/Cannon_150to210mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s5/d3/Shared/Cannon_150to210mm/"}
)

(define "Rus_203_Malka"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s3/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s5/d2/Shared/Cannon_150to210mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s5/d3/Shared/Cannon_150to210mm/"}
)
